### ISSUE TITLE
cannot getHtml() at an Android device with Android 7

### ISSUE THREAD

**Issue by Linzh7** [pichillilorenzo/flutter_inappwebview#1000]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.5.2 |
| Plugin version       | 5.3.2 |
| Android version      | Android 7.1.2 |
| iOS version          | x |
| Xcode version        |  x   |

Device information: 
didn't work:
MI 5C, Android 7.1.2, MIUI 11.0.3
did work:
Oneplus 9 plus, Android 11, OxygenOs 11.2.9.9

## Description

**Expected behavior:** 
After launch the website, the button could return the HTML(by getHtml()). Then I am able to process with this data.

**Current behavior:** 
print error messages which point to *package:flutter_inappwebview/src/types.dart*

from my point of view, it may relate with android version. 

## Steps to reproduce

1. create a InAppWebView with controller and set its URL
2. add a button or something, it will getHtml from the controller
3. while tap the button, the function will not work as we expect

## Stacktrace/Logcat   

E/chromium(15721): [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
W/ContentCatcher(15721): Failed to notify a WebView
D/mali_winsys(15721): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
E/flutter (15721): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'bool'
E/flutter (15721): #0      RendererPriorityPolicy.fromMap (package:flutter_inappwebview/src/types.dart:4595:38)
E/flutter (15721): #1      AndroidInAppWebViewOptions.fromMap (package:flutter_inappwebview/src/in_app_webview/android/in_app_webview_options.dart:422:61)
E/flutter (15721): #2      InAppWebViewGroupOptions.fromMap (package:flutter_inappwebview/src/in_app_webview/in_app_webview_options.dart:72:38)
E/flutter (15721): #3      InAppWebViewController.getOptions (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1555:39)
E/flutter (15721): <asynchronous suspension>
E/flutter (15721): #4      InAppWebViewController.getHtml (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:945:41)
E/flutter (15721): <asynchronous suspension>
E/flutter (15721): #5      _universityWebRouteState.build.<anonymous closure> (package:xxxx/xxxx/xxxx.dart:97:80)
E/flutter (15721): <asynchronous suspension>
E/flutter (15721):

**Comment by And96** [comment]
Simila problem here. GetHTML sometimes works and sometimes not.
In my case, I am on Android 11

**Comment by RodXander** [comment]
It also happened to me in Android 7.0, however, in Android 11 it worked correctly. 
Using `var html = await controller.evaluateJavascript(source: "window.document.getElementsByTagName('html')[0].outerHTML;");` worked on both though.

**Comment by lefo0755** [comment]
Maybe its the problem, https://github.com/lefo0755/flutter_inappwebview/commit/5f96c33eb78275c3251ae8fc100a63768c53aff4
