### ISSUE TITLE
App  Crash when the inappwebview calling from out main.dart

### ISSUE THREAD

**Issue by ismail4947** [pichillilorenzo/flutter_inappwebview#1001]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.26      |
| Plugin version       |        2.13       |
| Android version      |      4.1         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

I am using flutter_inappwebview: ^5.3.2 for implementation 3rd part payment gateway when I call the method from main.dart its running and working but when I call it from other like cart.dart,checkout.dart, urwaypayment.dart The App crash immediately before Webview appear

this is the Calling method

```
result = await Navigator.of(context).push(
            MaterialPageRoute<String>(builder: (BuildContext context) {
              return new TransactPage(inURL: compURL);
            }));
```

and this error meassage

```

I/Dialog  (30035): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
W/Gralloc4(30035): allocator 3.x is not supported
W/Gralloc3(30035): allocator 3.x is not supported
W/com.amart1.app(30035): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
E/AndroidRuntime(30035): FATAL EXCEPTION: main
E/AndroidRuntime(30035): Process: com.amart1.app, PID: 30035
E/AndroidRuntime(30035): java.lang.ExceptionInInitializerError
E/AndroidRuntime(30035): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
E/AndroidRuntime(30035): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:204)
E/AndroidRuntime(30035): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView.prepare(InAppWebView.java:184)
E/AndroidRuntime(30035): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:94)
E/AndroidRuntime(30035): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:26)
E/AndroidRuntime(30035): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/AndroidRuntime(30035): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:708)
E/AndroidRuntime(30035): 	at android.app.Dialog.show(Dialog.java:422)
E/AndroidRuntime(30035): 	at android.app.Presentation.show(Presentation.java:285)
E/AndroidRuntime(30035): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime(30035): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime(30035): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/AndroidRuntime(30035): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime(30035): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(30035): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(30035): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(30035): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(30035): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(30035): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(30035): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(30035): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(30035): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30035): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(30035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(30035): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
E/AndroidRuntime(30035): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
E/AndroidRuntime(30035): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
E/AndroidRuntime(30035): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
E/AndroidRuntime(30035): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
E/AndroidRuntime(30035): 	... 24 more
I/Process (30035): Sending signal. PID: 30035 SIG: 9
Lost connection to device.
```

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by And96** [comment]
Similar problem here. "flutter_inappwebview" crash if open the app from another application or from share menu.

I solved the proble disabling hybridComposition in options but now webview is much slower.

Example where app crash

  ```
 // For sharing or opening urls/text coming from outside the app while the app is in the memory
      _intentDataStreamSubscription =
          ReceiveSharingIntent.getTextStream().listen((String value) {
        if (value.toString().length > 5) {
          this.url = value;
          webViewController!.loadUrl(
              urlRequest: URLRequest(url: Uri.parse(value.toString())));
        }
      }, onError: (err) {
        print("getLinkStream error: $err");
      });
```
```

      // For sharing or opening urls/text coming from outside the app while the app is closed
      ReceiveSharingIntent.getInitialText().then((String? value) {
        if (value.toString().length > 5) {
          this.url = value.toString();
          webViewController!.loadUrl(
              urlRequest: URLRequest(url: Uri.parse(value.toString())));
        }
      });
    } catch (e) {
      print(e);
    }
```

**Comment by And96** [comment]
Actually I am using a workaround. My problem is when the app is called from external intent (Other apps)
I force close the app when in background. And then it restart when called.
For me it works but that's a terrible workaround.

**Comment by CoolBerry** [comment]
Same isuue and crash error info, app will crash after Navigator.push to the webview page. 
Can I have some temp ways to fix this error? 
Many thanks

**Comment by And96** [comment]
> Same isuue and crash error info, app will crash after Navigator.push to the webview page. 
> Can I have some temp ways to fix this error? 
> Many thanks

It's a bit ugly but you may find a workaround here: https://github.com/And96/MediumUnlimited/blob/main/lib/main.dart
