### ISSUE TITLE
Error: MissingPluginException(No implementation found for method loadUrl)

### ISSUE THREAD

**Issue by zyrouge** [pichillilorenzo/flutter_inappwebview#1030]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.6.0-12.0.pre.657 |
| Plugin version       | 5.3.2 |
| Android version      | 9 |
| iOS version          | - |
| Xcode version        | - |

Device information: Redmi 6 Pro

## Description

**Expected behavior:** The plugin loading the url.

## Code
This is how I create the webview.
```dart
HeadlessInAppWebView? webview = HeadlessInAppWebView(
   initialOptions: InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
         userAgent: HttpUtils.userAgent,
      ),
   ),
);
```

This is where the error occurs
```dart
await webview!.webViewController.loadUrl(urlRequest: URLRequest(url: uri));
```

## Stacktrace/Logcat
```
Error: MissingPluginException(No implementation found for method loadUrl on channel com.pichillilorenzo/flutter_inappwebview_11731001766432322481062304250211909819869)
Stack Trace:
  #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
  <asynchronous suspension>
  #1      InAppWebViewController.loadUrl (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1164:5)
  <asynchronous suspension>
...
```

I've tried `flutter clean` and all but that doesn't seem to fix this issue.

**Comment by zyrouge** [comment]
Apologies, calling `webview.run` was able to fix this.
