### ISSUE TITLE
Crash on Android, Fatal Exception:  Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by ankitsaini12** [pichillilorenzo/flutter_inappwebview#1058]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.8.0            |
| Plugin version       |       flutter_inappwebview: ^5.3.2        |

Device information: Nexus 5X Version:Android 8.1.0

## Description

On Android devices app crashes.

## Snack, code example, screenshot, or link to a repository:
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.onCreate(InAppBrowserActivity.java:70)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by EinatK** [comment]
same issue, and i see there are several bugs about this. 
Is there an expectation for a fix ?
Is this package still maintained ? I see its been 9 months since the last update.

**Comment by huangsir0** [comment]
any update?
