### ISSUE TITLE
soft keyboard issue in Android 12 Devices

### ISSUE THREAD

**Issue by AkhilSajiCodzoc** [pichillilorenzo/flutter_inappwebview#1083]
Couldn't open soft keyboard on Android 12 devices, but it's perfectly works on rest of all devices

**Comment by EnriqueMx** [comment]
Salme issue found on Android 12

**Comment by ljwdeveloper** [comment]
This may helpful : https://github.com/flutter/flutter/issues/96153#issue-1093901975

**Comment by EnriqueMx** [comment]
useHybridComposition  is set to true, works fine in all Android versions except Android 12.
It sends:
W/InputMethodManager: Ignoring showSoftInput() as view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{1bc916 VFEDHVCL. .F...... 0,0-1440,2425} is not served.
V/InputMethodManager: b/117267690: Display ID mismatch found. ViewRootImpl displayId=4 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
    java.lang.Throwable
        at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
        at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1843)
        at org.chromium.content.browser.input.ImeAdapterImpl.H(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:4)
        at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:30)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-02-07 12:00:10.056 8076-8076/im.ea.simplyfive V/InputMethodManager: b/117267690: Display ID mismatch found. ViewRootImpl displayId=4 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
    java.lang.Throwable
        at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
        at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1625)
        at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1617)
        at sH.d(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:3)
        at org.chromium.content.browser.input.ImeAdapterImpl.L(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:20)
        at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:32)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by EnriqueMx** [comment]
Ok, I was using setOptions to set useHybridComposition, it does not work there, it must be set only in InAppWebView creation. I added there and is now working.

**Comment by dhavaljani1990** [comment]
Awesome, its working!

**Comment by Nooshey** [comment]
@EnriqueMx can you share a sample code where you have added it? I'm having the same issue

**Comment by EnriqueMx** [comment]
> Ok, I was using setOptions to set useHybridComposition, it does not work there, it must be set only in InAppWebView creation. I added there and is now working.

InAppWebView(
                  key: webViewKey,
                   initialOptions: InAppWebViewGroupOptions(
                       crossPlatform: InAppWebViewOptions(
                         mediaPlaybackRequiresUserGesture: false,
                       ),
                       android: AndroidInAppWebViewOptions(
                        useHybridComposition: true,
                       ),
                       ios: IOSInAppWebViewOptions(
                         allowsInlineMediaPlayback: true,
                       )),
                      .....
)

**Comment by jananiDP** [comment]
> > Ok, I was using setOptions to set useHybridComposition, it does not work there, it must be set only in InAppWebView creation. I added there and is now working.
> 
> InAppWebView( key: webViewKey, initialOptions: InAppWebViewGroupOptions( crossPlatform: InAppWebViewOptions( mediaPlaybackRequiresUserGesture: false, ), android: AndroidInAppWebViewOptions( useHybridComposition: true, ), ios: IOSInAppWebViewOptions( allowsInlineMediaPlayback: true, )), ..... )

Thank you very much. This works.. 💯

**Comment by forgetW** [comment]
Does it work properly in Android 13? I have set it to not take effect

**Comment by GuiRitter** [comment]
> Does it work properly in Android 13? I have set it to not take effect

Not working for me 😢 (Samsung Galaxy Tab Active3)
