### ISSUE TITLE
MissingPluginException(No implementation found for method getTitle on channel com.pichillilorenzo/flutter_inappwebview_3)

### ISSUE THREAD

**Issue by huangsir0** [pichillilorenzo/flutter_inappwebview#1104]
## Error Info
``` dart
1	#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
2	<asynchronous suspension>
3	#1 InAppWebViewController.getTitle (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:923)
4	<asynchronous suspension>
5	#2 _FusionWebState._getTitleFromWeb (package:fusion_page/ui/fusion_web.dart:160)
6	<asynchronous suspension>
```

**Comment by a00012025** [comment]
Any suggestion? I got same issue on Android
