### ISSUE TITLE
PlatformException occurs when multi-touching at 3 points or more

### ISSUE THREAD

**Issue by MinByeongDon** [pichillilorenzo/flutter_inappwebview#1114]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.8.1, on macOS 12.2.1 21D62 darwin-arm |
| Plugin version       | 5.3.2 |
| Android version      | 12 |
| iOS version          |               |
| Xcode version        |               |

Device information: Samsung Galaxy S10 5G (SM G977N)

## Description

**Expected behavior:** No error occurs when multi-touching at 3 points or more

**Current behavior:** PlatformException occurs when multi-touching at 3 points or more

## Steps to reproduce

1. Muti-touch on 3 points or more
2. java.lang.IllegalArgumentException occoured

## Stacktrace/Logcat 

```txt
I[/ViewRootImpl]()@14e04eb[MainActivity](17894): ViewPostIme pointer 0
E[/MotionEvent-JNI]()(17894): pointerIndex out of range: pointerIndex 3, pointerCount 1
E[/MethodChannel]()#flutter[/platform_views]()(17894): Failed to handle method call
E[/MethodChannel]()#flutter[/platform_views]()(17894): java.lang.IllegalArgumentException: pointerIndex out of range
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.view.MotionEvent.nativeGetPointerId(Native Method)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.view.MotionEvent.getPointerId(MotionEvent.java:2760)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3631)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:314)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:176)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:206)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.os.Handler.handleCallback(Handler.java:938)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.os.Looper.loopOnce(Looper.java:226)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.os.Looper.loop(Looper.java:313)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at java.lang.reflect.Method.invoke(Native Method)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E[/MethodChannel]()#flutter[/platform_views]()(17894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
I[/flutter]() (17894): [WARNING] main - 💥 runZonedGurarded ERROR. PlatformException(error, pointerIndex out of range, null, java.lang.IllegalArgumentException: pointerIndex out of range
I[/flutter]() (17894): 	at android.view.MotionEvent.nativeGetPointerId(Native Method)
I[/flutter]() (17894): 	at android.view.MotionEvent.getPointerId(MotionEvent.java:2760)
I[/flutter]() (17894): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3631)
I[/flutter]() (17894): 	at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:314)
I[/flutter]() (17894): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:176)
I[/flutter]() (17894): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
I[/flutter]() (17894): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I[/flutter]() (17894): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
I[/flutter]() (17894): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:20
I[/ViewRootImpl]()@14e04eb[MainActivity](17894): ViewPostIme pointer 1
```

**Comment by ueman** [comment]
I'm also seeing this issue a lot in production, in a couple of different variations, as seen in the screenshots below. I'm also wondering whether this is actually an issue of this plugin or an issue of Flutter itself.
![Screenshot 2022-11-29 at 11 32 16](https://user-images.githubusercontent.com/1270149/204506147-181041fc-a0d2-4b60-bb6f-6ca1945b3447.png)
![Screenshot 2022-11-29 at 11 32 53](https://user-images.githubusercontent.com/1270149/204506286-434c18af-fea3-4f77-9c8c-aaa54d65c1a3.png)

**Comment by phamconganh** [comment]
I think the problem is from flutter's PlatformView, see https://github.com/flutter/engine/pull/34182

**Comment by MinByeongDon** [comment]
I have seen the issue no longer occur in the current environment as shown below.
**The issue seems to be resolved**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.85.1)
[✓] VS Code (version 1.90.0-insider)
[✓] Connected device (3 available)
[✓] Network resources
