### ISSUE TITLE
 java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by GalacticTitan** [pichillilorenzo/flutter_inappwebview#1121]
org.chromium.android_webview.AwDataDirLock.b (AwDataDirLock.java:27)
org.chromium.android_webview.AwBrowserProcess.i (AwBrowserProcess.java:5)
com.android.webview.chromium.c1.e (c1.java:39)

android.webkit.WebStorage.getInstance (WebStorage.java:194)
com.pichillilorenzo.flutter_inappwebview.MyWebStorage.<init> (MyWebStorage.java:29)
com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine (InAppWebViewFlutterPlugin.java:89)
com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine (InAppWebViewFlutterPlugin.java:68)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add (FlutterEngineConnectionRegistry.java:143)
io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:42)
com.bedwal.bijak.mvp.MainActivity.configureFlutterEngine (MainActivity.java:78)
io.flutter.embedding.android.FlutterFragment.configureFlutterEngine (FlutterFragment.java:1023)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:180)
io.flutter.embedding.android.FlutterFragment.onAttach (FlutterFragment.java:609)

**Comment by shirne** [comment]
same issue
```
11-06 10:06:36.508  7474  7506 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377, null, java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.webview.chromium.WebViewChromiumAwInit.startChromiumLocked(WebViewChromiumAwInit.java:63)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.webview.chromium.WebViewChromiumAwInitForP.startChromiumLocked(WebViewChromiumAwInitForP.java:3)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.webview.chromium.WebViewChromiumAwInit.ensureChromiumStartedLocked(WebViewChromiumAwInit.java:142)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.webview.chromium.WebViewChromiumAwInit.getStatics(WebViewChromiumAwInit.java:159)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(WebViewChromiumFactoryProvider.java:142)
11-06 10:06:36.508  7474  7506 E flutter :      at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:2145)
11-06 10:06:36.508  7474  7506 E flutter :      at com.pichillilorenzo.flutter_inappwebview.InAppWebViewStatic.onMethodCall(InAppWebViewStatic.java:105)
11-06 10:06:36.508  7474  7506 E flutter :      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
11-06 10:06:36.508  7474  7506 E flutter :      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
11-06 10:06:36.508  7474  7506 E flutter :      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
11-06 10:06:36.508  7474  7506 E flutter :      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
11-06 10:06:36.508  7474  7506 E flutter :      at android.os.Handler.handleCallback(Handler.java:873)
11-06 10:06:36.508  7474  7506 E flutter :      at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 10:06:36.508  7474  7506 E flutter :      at android.os.Looper.loop(Looper.java:220)
11-06 10:06:36.508  7474  7506 E flutter :      at android.app.ActivityThread.main(ActivityThread.java:7437)
11-06 10:06:36.508  7474  7506 E flutter :      at java.lang.reflect.Method.invoke(Native Method)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
11-06 10:06:36.508  7474  7506 E flutter :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
11-06 10:06:36.508  7474  7506 E flutter : )
11-06 10:06:36.508  7474  7506 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
11-06 10:06:36.508  7474  7506 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
11-06 10:06:36.508  7474  7506 E flutter : <asynchronous suspension>
11-06 10:06:36.508  7474  7506 E flutter : #2      AndroidInAppWebViewController.setWebContentsDebuggingEnabled (package:flutter_inappwebview/src/in_app_webview/android/in_app_webview_controller.dart:203:12)
11-06 10:06:36.508  7474  7506 E flutter : <asynchronous suspension>
11-06 10:06:36.508  7474  7506 E flutter : #3      _SplashPageState.initWeb (package:blocapp/src/pages/splash.dart:46:7)
11-06 10:06:36.508  7474  7506 E flutter : <asynchronous suspension>
11-06 10:06:36.508  7474  7506 E flutter : #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
11-06 10:06:36.508  7474  7506 E flutter : <asynchronous suspension>
11-06 10:06:36.508  7474  7506 E flutter : #5      _SplashPageState.init (package:blocapp/src/pages/splash.dart:31:5)
11-06 10:06:36.508  7474  7506 E flutter : <asynchronous suspension>
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.17)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

code:

```
// I add a global var to ensure this only be called once. but still does not work
if (isWebInitialed) {
      return;
 }
isWebInitialed = true;
if (!kIsWeb && Platform.isAndroid) {
      await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);

      final swAvailable = await AndroidWebViewFeature.isFeatureSupported(
          AndroidWebViewFeature.SERVICE_WORKER_BASIC_USAGE);
      final swInterceptAvailable =
          await AndroidWebViewFeature.isFeatureSupported(
              AndroidWebViewFeature.SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST);

      if (swAvailable && swInterceptAvailable) {
        AndroidServiceWorkerController serviceWorkerController =
            AndroidServiceWorkerController.instance();

        await serviceWorkerController.setServiceWorkerClient(
          AndroidServiceWorkerClient(
            shouldInterceptRequest: (request) async {
              log.d(request);
              return null;
            },
          ),
        );
      }
}
```

**Comment by shirne** [comment]
I delete the app and run again, it worked.
