### ISSUE TITLE
Crash on Android devices : - ChromeCustomTabsActivity.java line 15

### ISSUE THREAD

**Issue by srihari9n** [pichillilorenzo/flutter_inappwebview#1228]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.10.5         |
| Plugin version       |        5.3.2       |
| Android version      |       11        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

 I dont know how to reproduce this issue, this is caught by crashlytics. 

## Images 

 
<img width="1048" alt="Screenshot 2022-06-22 at 12 19 55 PM" src="https://user-images.githubusercontent.com/101564310/174963479-3b0528ae-f0e3-40f5-8ce1-29cacf3afc66.png">

## Stacktrace/Logcat 

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.<redacted>/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=0, data=null} to activity {com.<redacted>t/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.a.d.a.j.c(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4795)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4833)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2329)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:261)
       at android.app.ActivityThread.main(ActivityThread.java:8238)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by alectogeek** [comment]
How did you solve the problem?

**Comment by srihari9n** [comment]
@alectogeek  I had no idea on what was causing it, so I closed the issue until I can find any further info. Do you see this same crash?

**Comment by okzjapan** [comment]
I am struggling with the same problem :(
version 5.7.1

```
ChromeCustomTabsActivity.java line 21
com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.close
```

**Comment by edeuss** [comment]
@srihari9n Can you reopen the issue, seems to affect other people too.

**Comment by gaborszakacs** [comment]
I see this happening too. One thing to note is that Crashlytics categorizes this as an early crash, meaning, it's happening in the first 5 sec of a user session. This tells me it's happening on a warm start when the last activity was a ChromeCustomTab.

 I can't reproduce it with confidence, but a few times I managed to:
- open the app
- open a page in ChromeCustomTab
- send the app to the background
- do some other activity on the phone
- switch back to the app (it loads where you left it: the browser - warm start)
- click the close icon on the browser
- it crashes

Not sure if there's something else can I provide to help debug this issue, I'm happy to contribute.

**Comment by gaborszakacs** [comment]
Managed to get a better stack trace from a debug build, this tells me that the channel we're trying to call a method on became `null` in the meantime. This feels like a more general Flutter issue ([an example report](https://github.com/flutter/flutter/issues/76526)), but it seems like it was addressed in the 6.x branch and a null check was implemented ([commit](https://github.com/pichillilorenzo/flutter_inappwebview/commit/92abeea57f7d290d58280e3bd3e4e2383d0a413b#diff-7c18f4d341477eb0c02e88d32d49a5512475d168a49260d26c3662d4c4aac592)).

I'll try to upgrade to 6.x and see if it resolves the issue.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.close(ChromeCustomTabsActivity.java:278)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onActivityResult(ChromeCustomTabsActivity.java:240)
```

**Comment by gaborszakacs** [comment]
UPDATE: For me the issue went away after upgrading the plugin to the 6.x branch.

**Comment by leo-neon** [comment]
Same issue here, is there already an estimate for stable release?

**Comment by srihari9n** [comment]
@pichillilorenzo  can you please provide an update on the 6.x version's stable release?

**Comment by felipecastrosales** [comment]
I'm facing with the same issue here in my app. Any news about the update to stable, @pichillilorenzo?

**Comment by Hamza3620** [comment]
Hi, I am also facing the same issue with my app. Is there any update regarding its resolution? As this is coming from the package, it's really hard to avoid it.
