### ISSUE TITLE
JavaScript Communication for Flutter Web

### ISSUE THREAD

**Issue by wujekbogdan** [pichillilorenzo/flutter_inappwebview#1329]
In [this topic](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1243) I found that `flutter_inappwebview` works on the web. I gave it a try and indeed the webview renders inside an `<iframe>`, but I'm not able to implement [JavaScript Communication](https://inappwebview.dev/docs/javascript/communication/). 

1. In case of [JavaScript Handlers](https://inappwebview.dev/docs/javascript/communication/#JavaScript-Handlers) the `window.flutter_inappwebview.callHandler` ("outside" the iframe, in the global scope) resolves with `undefined`
2. [Web Message Listeners]( https://inappwebview.dev/docs/javascript/communication/#JavaScript-Handlers#Web-Message-Listeners) don't work either: `window. myObject` object resolves with `undefined` when accessed from the "inside" of the iframe.

I'm getting a bunch of errors in the console:

```
DOMException: Blocked a frame with origin "http://localhost:5005" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:5005/packages/flutter_inappwebview/assets/web/web_support.js:46:65)
web_support.js:77 DOMException: Blocked a frame with origin "http://localhost:5005" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:5005/packages/flutter_inappwebview/assets/web/web_support.js:54:61)
web_support.js:191 DOMException: Blocked a frame with origin "http://localhost:5005" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:5005/packages/flutter_inappwebview/assets/web/web_support.js:81:74)
web_support.js:227 DOMException: Blocked a frame with origin "http://localhost:5005" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:5005/packages/flutter_inappwebview/assets/web/web_support.js:197:59)
```

Is it expected? Is Javascript Communication supposed to be working already in the `develop` branch?

**Comment by pichillilorenzo** [comment]
It's not possible to use javascript handlers on Web platform.
`iframe` objects are very very limited, unfortunately.
To know if a method/event/class is supported on Web, check the code docs directly.

**Comment by ert485** [comment]
+1
From outside the webview (in dart), it's possible to push in javascript to get run with `eval`. But there's no way to hear anything back - other than the (synchronous) return value. 

If there were any sort of way to get dart code to run based on an event triggered inside the webview (in javascript), that would be very helpful.

**Comment by ert485** [comment]
Although it would be a bit of a hack, it should be currently possible to use `onConsoleMessage` (a callback parameter for `InAppWebView` constructor) as a way to listen to things happening in javascript.

**Comment by jyr** [comment]
> Although it would be a bit of a hack, it should be currently possible to use `onConsoleMessage` (the callback parameter for `InAppWebView` constructor) as a way to trigger dart things based on a JS statement (e.g. `console.log(JSON.stringify({type: 'callback', name: 'foo', value: 'bar'}))`).

I don't understand what happen, I'm using the inappwebview v6.0.0-beta.22 and saw the [documentation](https://inappwebview.dev/docs/webview/javascript/injection) that javascript injection should works. But i have the same errors:

```
DOMException: Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:63239/assets/packages/flutter_inappwebview/assets/web/web_support.js:49:65)
js_primitives.dart:30
DOMException: Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:63239/assets/packages/flutter_inappwebview/assets/web/web_support.js:57:61)
DOMException: Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:63239/assets/packages/flutter_inappwebview/assets/web/web_support.js:84:74)
DOMException: Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:63239/assets/packages/flutter_inappwebview/assets/web/web_support.js:200:59)
```

And I get null value when run 

```
onLoadStop: (controller, url) async {
                    var result =
                        await controller.evaluateJavascript(source: "1 + 1");
                    print(result.runtimeType); // int
                    print(result); // 2
                  }
```

Here my WebView

```
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:url_launcher/url_launcher.dart';

class BelvoInAppWebView extends StatefulWidget {
  const BelvoInAppWebView({
    Key? key,
    required this.url,
    this.width,
    this.height,
    this.bypass = false,
    this.horizontalScroll = false,
    this.verticalScroll = false,
  }) : super(key: key);

  final bool bypass;
  final bool horizontalScroll;
  final bool verticalScroll;
  final double? height;
  final double? width;
  final String url;

  @override
  _BelvoInAppWebViewState createState() => new _BelvoInAppWebViewState();
}

class _BelvoInAppWebViewState extends State<BelvoInAppWebView> {
  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;
  InAppWebViewSettings settings = InAppWebViewSettings(
      useShouldOverrideUrlLoading: true,
      mediaPlaybackRequiresUserGesture: false,
      allowsInlineMediaPlayback: true,
      iframeAllow: "camera; microphone",
      iframeAllowFullscreen: true);

  PullToRefreshController? pullToRefreshController;
  String url = "";
  double progress = 0;
  final urlController = TextEditingController();

  @override
  void initState() {
    super.initState();

    pullToRefreshController = kIsWeb
        ? null
        : PullToRefreshController(
            settings: PullToRefreshSettings(
              color: Colors.blue,
            ),
            onRefresh: () async {
              if (defaultTargetPlatform == TargetPlatform.android) {
                webViewController?.reload();
              } else if (defaultTargetPlatform == TargetPlatform.iOS) {
                webViewController?.loadUrl(
                    urlRequest:
                        URLRequest(url: await webViewController?.getUrl()));
              }
            },
          );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Official InAppWebView website")),
        body: SafeArea(
            child: Column(children: <Widget>[
          TextField(
            decoration: InputDecoration(prefixIcon: Icon(Icons.search)),
            controller: urlController,
            keyboardType: TextInputType.url,
            onSubmitted: (value) {
              var url = WebUri(value);
              if (url.scheme.isEmpty) {
                url = WebUri("https://www.google.com/search?q=" + value);
              }
              webViewController?.loadUrl(urlRequest: URLRequest(url: url));
            },
          ),
          Expanded(
            child: Stack(
              children: [
                InAppWebView(
                  key: webViewKey,
                  initialUrlRequest:
                      URLRequest(url: WebUri("https://flutter.dev")),
                  initialSettings: settings,
                  pullToRefreshController: pullToRefreshController,
                  onWebViewCreated: (controller) {
                    debugPrint('onWebViewCreated');
                    webViewController = controller;
                  },
                  onLoadStart: (controller, url) {
                    debugPrint('onLoadStart');
                    setState(() {
                      this.url = url.toString();
                      urlController.text = this.url;
                    });
                  },
                  onPermissionRequest: (controller, request) async {
                    return PermissionResponse(
                        resources: request.resources,
                        action: PermissionResponseAction.GRANT);
                  },
                  shouldOverrideUrlLoading:
                      (controller, navigationAction) async {
                    var uri = navigationAction.request.url!;

                    if (![
                      "http",
                      "https",
                      "file",
                      "chrome",
                      "data",
                      "javascript",
                      "about"
                    ].contains(uri.scheme)) {
                      if (await canLaunchUrl(uri)) {
                        // Launch the App
                        await launchUrl(
                          uri,
                        );
                        // and cancel the request
                        return NavigationActionPolicy.CANCEL;
                      }
                    }

                    return NavigationActionPolicy.ALLOW;
                  },
                  onLoadStop: (controller, url) async {
                    var result =
                        await controller.evaluateJavascript(source: "1 + 1");
                    print(result.runtimeType); // int
                    print(result); // 2
                  },
                  onReceivedError: (controller, request, error) {
                    pullToRefreshController?.endRefreshing();
                  },
                  onProgressChanged: (controller, progress) {
                    if (progress == 100) {
                      pullToRefreshController?.endRefreshing();
                    }
                    setState(() {
                      this.progress = progress / 100;
                      urlController.text = this.url;
                    });
                  },
                  onUpdateVisitedHistory: (controller, url, androidIsReload) {
                    setState(() {
                      this.url = url.toString();
                      urlController.text = this.url;
                    });
                  },
                  onConsoleMessage: (controller, consoleMessage) {
                    print(consoleMessage);
                  },
                ),
                progress < 1.0
                    ? LinearProgressIndicator(value: progress)
                    : Container(),
              ],
            ),
          ),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Icon(Icons.arrow_back),
                onPressed: () {
                  webViewController?.goBack();
                },
              ),
              ElevatedButton(
                child: Icon(Icons.arrow_forward),
                onPressed: () {
                  webViewController?.goForward();
                },
              ),
              ElevatedButton(
                child: Icon(Icons.refresh),
                onPressed: () {
                  webViewController?.reload();
                },
              ),
            ],
          ),
        ])));
  }
}

```

**Comment by ert485** [comment]
@jyr 
> Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.

This is a web security feature that is built into the browser you view your app from (and every common web browser). See here:

> initialUrlRequest: URLRequest(url: WebUri("https://flutter.dev")),

... since the iframe url is a different origin than your flutter app (`flutter.dev` is different than `localhost:63239`), you won't be able to do javascript communication across the barrier. If instead you loaded `localhost:63239/some-other-page` into the web view, then the error would go away.

This is mentioned in the docs [here](https://inappwebview.dev/docs/webview/in-app-webview)
![Screen Shot 2023-03-27 at 8 56 32 AM](https://user-images.githubusercontent.com/6201488/227979096-16802014-1725-4ec9-a796-fe8b0626b14a.png)

**Comment by jyr** [comment]
> @jyr
> 
> > Blocked a frame with origin "http://localhost:63239" from accessing a cross-origin frame.
> 
> This is a web security feature that is built into the browser you view your app from (and every common web browser). See here:
> 
> > initialUrlRequest: URLRequest(url: WebUri("https://flutter.dev")),
> 
> ... since the iframe url is a different origin than your flutter app (`flutter.dev` is different than `localhost:63239`), you won't be able to do javascript communication across the barrier. If instead you loaded `localhost:63239/some-other-page` into the web view, then the error would go away.

Does works with inappwebview 6xxx? because I disabled the cors with:

`flutter run -d chrome --web-browser-flag "--disable-web-security"`

and same errors

**Comment by ert485** [comment]
The inappwebview version shouldn't have any effect on this bug (since all versions are implemented in Web with `iframe`). I'm not sure what scope `--disable-web-security` all has (how many security features it disables). It's not exactly CORS because it's not a network request that's being blocked, it's javascript execution.

**Comment by jyr** [comment]
> If instead you loaded `localhost:63239/some-other-page` into the web view, then the error would go away.

So, is it impossible to use a WebView with a external link? or Do I have to insert the external link in `localhost:63239/some-other-page` and this page loading it in a WebView?

**Comment by ert485** [comment]
> So, is it impossible to use a WebView with a external link?

In general, yes it's impossible (assuming you need javascript communication, and are in Flutter Web). 

It's a browser security feature because evaluating arbitrary javascript would let you do things like steal passwords/tokens/cookies/etc. from the user. 

For example, the attack could be:
> You go to "fake-google.com" thinking it's the real "google.com" (and it looks exactly like google.com because it's an iframe), and put in your password to log in. Now the owner of "fake-google.com" has your password, because they injected a keystroke logger into the iframe.

I'm kinda surprised the security feature isn't there for Android Webviews etc. But then again, nothing is stopping an app that is implementing its own "web browser" from skipping web security features.

There might be ways that the "external" page could allow certain data in/out (I would maybe look into things like "web messages"), but that would hanging on the person developing that external page.

**Comment by fvisticot** [comment]
Using in Web platform with ^6.0.0-beta.23 version

In my case the HTML is local html injected with initialData
In that case of **local injected HTML** (with initialData) is it possible to have communication between JS and Flutter ?  are the 2 different piece of code (Flutter and JS) in the same origin ?

```
InAppWebView(
              initialData: InAppWebViewInitialData(data: html, encoding: 'utf-8'),
              onLoadStop: (controller, url) async {
                var result = await controller.evaluateJavascript(source: "1 + 1");
                print("===>${result.runtimeType}"); // int
                print("===>Result: $result"); // 2
                print("====>onLoadStop");
              },
```

I get the same cross origin frame error
```
DOMException: Blocked a frame with origin "http://localhost:64428" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:64428/assets/packages/flutter_inappwebview/assets/web/web_support.js:49:65)
web_support.js:80 DOMException: Blocked a frame with origin "http://localhost:64428" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:64428/assets/packages/flutter_inappwebview/assets/web/web_support.js:57:61)
```
