### ISSUE TITLE
flutter_inappwebview - using local asset - java.io.FileNotFoundException: flutter_assets/assets/index.html

### ISSUE THREAD

**Issue by codingforfun4481** [pichillilorenzo/flutter_inappwebview#1418]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  Flutter 3.3.7            |
| Plugin version  |  v3.52.0 |
| Android version |  build.gradle: compileSdkVersion 32     |
| iOS version     |       N/A        |
| macOS version   |     N/A          |
| Xcode version   |     N/A          |

Device information: 

**## Description**
Develop with Visual Studio Code v 1.73.0 a flutter App

In main.dart flutter_inappwebview is imported via
import package:flutter_inappwebview/flutter_inappwebview.dart';

in build.gradle: compileSdkVersion 32
in pubspec.yaml is defined:
assets:
    - assets/index.html

A local stored index.html file should be loaded via "webView.loadFile(assetFilePath: "assets/index.html");"

Error message is: "W/System.err(30582): java.io.FileNotFoundException: flutter_assets/assets/index.html"

index.html is located in the defined folder.

**Added in AndroidManifest.xml:**

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

****Expected behavior:**** 
flutter_inappwebview loads a local stored index.html via
- initialFile: "http://localhost:8080/assets/index.html",
or
webView.loadFile(assetFilePath: "assets/index.html");

****Current behavior:**** 
webView.loadFile(assetFilePath: "assets/index.html"); leads to
Error message is: "W/System.err(30582): java.io.FileNotFoundException: flutter_assets/assets/index.html

initialFile: "http://localhost:8080/assets/index.html"," leads to
Result: "E/IAWFlutterWebView(30582): http://localhost:8080/assets/index.html asset file cannot be found!"

## Steps to reproduce

The impotant code snippet:

class _MyHomePageState extends State<MyHomePage> {
  late InAppWebViewController webView;
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (await webView.canGoBack()) {
          webView.goBack();
          return false;
        }
        return true;
      },
      child: Scaffold(
        body: Container(
            child: Column(children: <Widget>[
          Expanded(
            child: Container(
              margin: const EdgeInsets.only(top: 30.0),
              child: InAppWebView(
                //initialFile: "http://localhost:8080/assets/index.html",
                onWebViewCreated: (InAppWebViewController controller) {
                  webView = controller;
                  **webView.loadFile(assetFilePath: "assets/index.html");**
                },
              ),
            ),
          )
        ])),
      ),
    );
  }

## Stacktrace/Logcat 
I/flutter (30582): Server running on http://localhost:8080
W/System.err(30582): java.io.FileNotFoundException: flutter_assets/http://localhost:8080/assets/index.html
W/System.err(30582): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(30582): 	at android.content.res.AssetManager.open(AssetManager.java:881)
W/System.err(30582): 	at android.content.res.AssetManager.open(AssetManager.java:858)
W/System.err(30582): 	at com.pichillilorenzo.flutter_inappwebview.Util.getFileAsset(Util.java:97)
W/System.err(30582): 	at com.pichillilorenzo.flutter_inappwebview.Util.getUrlAsset(Util.java:75)
W/System.err(30582): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView.loadFile(InAppWebView.java:556)
W/System.err(30582): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.FlutterWebView.makeInitialLoad(FlutterWebView.java:110)
W/System.err(30582): 	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:34)
W/System.err(30582): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
W/System.err(30582): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
W/System.err(30582): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)

**Comment by codingforfun4481** [comment]
Thanks!
initialUrl: "http://localhost:8080/assets/index.html", => The named parameter 'initialUrl' isn't defined for InAppWebView.

Following works:
initialUrlRequest: URLRequest(
                    url: Uri.parse("http://localhost:8080/assets/index.html")),

But there is still the open question:
why leads
webView.loadFile(assetFilePath: "assets/index.html"); 
to
Error message is: "W/System.err(30582): java.io.FileNotFoundException: flutter_assets/assets/index.html
