### ISSUE TITLE
Unexpected addWebMessageListener behaviour

### ISSUE THREAD

**Issue by HenryQuan** [pichillilorenzo/flutter_inappwebview#1422]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.3.7       |
| Plugin version  |     5.4.3+7          |
| Android version |       Any        |
| iOS version     |        Any       |
| macOS version   |       -        |
| Xcode version   |          13.1     |

Device information: 

## Description
I have a main screen with one InAppWebView. The main screen navigates to another screen with a simple list. From the list, it can navigate to another screen with one InAppWebView. `addWebMessageListener` is called twice using the same name in two places.

**Expected behavior:** 
The main screen should still receive web messages when my another screen goes back to the list and returns to the main screen.

**Current behavior:** 
The main screen can no longer receive any web messages. All messages are sent to the other screen, but it should be gone due to navigation.

The assert fails because the webview sees that the listener is already there. However, this is not true.
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart': Failed assertion: line 2497 pos 9: '!_webMessageListenerObjNames.contains(webMessageListener.jsObjectName)': jsObjectName mobileTarget was already added.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      InAppWebViewController.addWebMessageListener (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:2497:9)
```
This also freezes the iOS app in release.

**Comment by HenryQuan** [comment]
![log](https://user-images.githubusercontent.com/6754708/201567669-a61c6a33-5b0d-455d-b45a-6d58ed095456.png)
The issue is triggered after `WebMessageListener - dealloc` is printed out to the console. Then, the webview is cleared and becomes nil. I figure Flutter is then very confused because the webview is nil all of a sudden so the UI is frozen. However, dealloc shouldn't be called because the webview is still in use. Not sure if there is a reference issue or something. The second webview should be cleared, but not the first one.
@pichillilorenzo Am I using it incorrectly? So there should be only one webview in the entire app, not two at a time.

**Comment by HenryQuan** [comment]
I have located the issue down to `channel?.setMethodCallHandler(nil)`. However, it seems fine until the unexpected dealloc which freezes the app completely. Not sure what triggers this behaviour.

**Comment by filipenanclarez** [comment]
Hi, i think have the same problem here.

Basically the `addWebMessageListener` works on global scope. So i think, if we try use two webviews, the last webview override the listener, and then the first webview cannot receive any messages.

I made a reproducible example, using both `flutter_webview` and `flutter_inappwebview` plugins, one per tab. In flutter_webview's tabs (FWV1 and FWV2), messages can received in both tabs without problem. But in flutter_inappwebview tabs (InApp1 and InApp2) we can see the problem. When switch to tab InApp2, the timer start count and the InApp1 counter stops. Then never go back count.

To help find out the bug, i put keys inside widgets, and show them in receive message event, so we can easily check who is send messages and who is listen them.

I hope this minimal reproducible example can help to solve this issue.

For now, sadly i need stop use `flutter_inappwebview` in my project because of this issue.

Here the repository:

[https://github.com/filipenanclarez/poc_inappwebviews_with_tabs](https://github.com/filipenanclarez/poc_inappwebviews_with_tabs)

**Comment by pichillilorenzo** [comment]
@HenryQuan could you provide a sample code that reproduce your issue?

**Comment by pichillilorenzo** [comment]
I think I found out the problem.
When a `WebMessageListener` is created, it will use `'com.pichillilorenzo/flutter_inappwebview_web_message_listener_$jsObjectName'` as `MethodChannel` to communicate with the native side.
So, if another `InAppWebView` will add a `WebMessageListener` with the same name as the first `InAppWebView`, the oldest `WebMessageListener` will not receive any message because the `MethodChannel` will have the same name as the second one and they will be wrongly "redirected" to the `WebMessageListener` last one.

So, I must use a different name for the `MethodChannel` otherwise there will be conflicts.
I will try to fix it in the next release for versions 5 and 6.

**Comment by pichillilorenzo** [comment]
Released new versions `5.7.2+2` and`6.0.0-beta.20` with that fix.
