### ISSUE TITLE
java.lang.Throwable Application attempted to call on a destroyed WebView 

### ISSUE THREAD

**Issue by gujintao1900** [pichillilorenzo/flutter_inappwebview#1429]
- [y] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [y] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.3.8          |
| Plugin version  |      5.7.1         |
| Android version |       9        |

Device information: 
Vivo Z3 V1813BT Android 9 
Android System WebView 68.0.3440.91

## Description

**Expected behavior:**
screen will not flicker.

**Current behavior:** 
page A is flutter 
page B is flutter inclode InAppWebView
Sometimes, when i navigation back from page B to page A, screen will flicker one time.

## Steps to reproduce

**Only `transparentBackground` and `useHybridComposition` are both `true` will have this problem.**

Anorid 9 will be of frequent occurence.
Anorid 10 also have this problem but not frequent.

```dart
final options  = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      transparentBackground: true, 
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
);

```

## Images   

https://user-images.githubusercontent.com/48408513/202371358-d983b697-4350-40ef-a0a0-9d6e5651b58f.mp4

## Stacktrace/Logcat   
```log
I/UMLog   ( 4997): onPageStart:/app_pages/web
I/PlatformViewsController( 4997): Using hybrid composition for platform view: 15
I/flutter ( 4997): AppWebViewController == onWebViewCreated
I/flutter ( 4997): AppWebViewController == onLoadStart https://m.huabbao.com/pay_item/draw/5608?inject=1&p=android&v=2.7.0
I/flutter ( 4997): AppWebViewController == onLoadStop https://m.huabbao.com/pay_item/draw/5608?inject=1&p=android&v=2.7.0
I/UMLog   ( 4997): onPageEnd:/app_pages/web
I/flutter ( 4997): AppWebViewController == dispose
W/cr_AwContents( 4997): Application attempted to call on a destroyed WebView
W/cr_AwContents( 4997): java.lang.Throwable
W/cr_AwContents( 4997): 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:320)
W/cr_AwContents( 4997): 	at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:292)
W/cr_AwContents( 4997): 	at org.chromium.android_webview.AwContents.getTitle(AwContents.java:544)
W/cr_AwContents( 4997): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.loadingStateChanged(AwWebContentsDelegateAdapter.java:161)
W/cr_AwContents( 4997): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/cr_AwContents( 4997): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/cr_AwContents( 4997): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents( 4997): 	at android.os.Looper.loop(Looper.java:243)
W/cr_AwContents( 4997): 	at android.app.ActivityThread.main(ActivityThread.java:7172)
W/cr_AwContents( 4997): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents( 4997): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
W/cr_AwContents( 4997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
W/cr_ChildProcessConn( 4997): onServiceDisconnected (crash or killed by oom): pid=6526
W/System  ( 4997): A resource failed to call response.body().close().
```

**Comment by gujintao1900** [comment]
## Workaround 

``` dart
import 'package:device_info_plus/device_info_plus.dart';
final info = await DeviceInfoPlugin().androidInfo;
final useHybridComposition = info.version.sdkInt > 29;
```

**Comment by Brislis** [comment]
> ## Workaround
> ```dart
> import 'package:device_info_plus/device_info_plus.dart';
> final info = await DeviceInfoPlugin().androidInfo;
> final useHybridComposition = info.version.sdkInt > 29;
> ```

我也碰到了你同样的问题，useHybridComposition 设置为false就不会闪烁，请问下，如果这样写SDK等级大于29不也是会闪烁吗？
