### ISSUE TITLE
Crash on Android devices:  ChromeCustomTabsActivity.java line 21

### ISSUE THREAD

**Issue by manhit77** [pichillilorenzo/flutter_inappwebview#1499]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |               |
| Plugin version  |      5.5.0         |
| Android version |       10        |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by ne3Vubeki** [comment]
the same for me

Device
Brand:Xiaomi
Model:Redmi Note 10 5G
Orientation: Portrait
Version:Android 12

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.quppy/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=0, data=null} to activity {com.quppy/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void m6.k.c(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4917)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2318)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8306)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by leo-neon** [comment]
Same for me, a fix would be amazing. We just launched some (news)-apps and their core feature is basically the in app web view. Now we see some crashes due to that.

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void ld.k.c(java.lang.String, java.lang.Object)' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.close(ChromeCustomTabsActivity.java:278)
       at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onActivityResult(ChromeCustomTabsActivity.java:240)
       at android.app.Activity.dispatchActivityResult(Activity.java:8110)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
