### ISSUE TITLE
ContentBlocker Exception for android 

### ISSUE THREAD

**Issue by heralight** [pichillilorenzo/flutter_inappwebview#1533]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |               |
| Plugin version  |  6.0.0-beta.22             |
| Android version |    33           |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 
ContentBlocker working well on android and ios.

**Current behavior:** 
Work well on ios, throw an exception on android
The exception come from line 265 of content_blocker.dart :
        type: ContentBlockerActionType.fromNativeValue(map["type"])!,

where ContentBlockerActionType.fromNativeValue(map["type"])! loop for all type but have some equals to null for example cookie for android in the switch.

## Steps to reproduce

just run the sample inside an android emulator with the version 6.0.0-beta.22 

## Stacktrace/Logcat
```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (20162): #0      ContentBlockerAction.fromMap (package:flutter_inappwebview/src/content_blocker.dart:265:68)
E/flutter (20162): #1      ContentBlocker.fromMap (package:flutter_inappwebview/src/content_blocker.dart:27:38)
E/flutter (20162): #2      _deserializeContentBlockers.<anonymous closure> (package:flutter_inappwebview/src/in_app_webview/in_app_webview_settings.dart:45:42)
E/flutter (20162): #3      _Array.forEach (dart:core-patch/array.dart:40:8)
E/flutter (20162): #4      _deserializeContentBlockers (package:flutter_inappwebview/src/in_app_webview/in_app_webview_settings.dart:44:28)
E/flutter (20162): #5      InAppWebViewSettings.fromMap (package:flutter_inappwebview/src/in_app_webview/in_app_webview_settings.g.dart:1415:9)
E/flutter (20162): #6      InAppWebViewController.getSettings (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:2253:35)
```

Thank you,

Alexandre

**Comment by saveliy-kremen** [comment]
types ContentBlockerActionType.IGNORE_PREVIOUS_RULES and ContentBlockerActionType.BLOCK_COOKIES are not released for Android and return Null which is the cause of the error
