### ISSUE TITLE
java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL

### ISSUE THREAD

**Issue by ctemkar** [pichillilorenzo/flutter_inappwebview#1611]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |               |
| Plugin version  |               |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 
Should work

**Current behavior:** 
Webview doesn't come up

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
2023-04-04 16:46:36.357 23360-23360 MethodChan...form_views com.vimvest.android.staging2         E  Failed to handle method call
                                                                                                    java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
                                                                                                    	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
                                                                                                    	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
                                                                                                    	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:44)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
                                                                                                    	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
                                                                                                    	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-04-04 16:46:36.467 23360-23406 flutter                 com.vimvest.android.staging2         E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature REQUESTED_WITH_HEADER_CONTROL, null, java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
                                                                                                    	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
                                                                                                    	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
                                                                                                    	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:44)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
                                                                                                    	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
                                                                                                    	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    )
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1081:5)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:801:5)
                                                                                                    <asynchronous suspension>
[inappwebview-flutter-error-log.tx
[main.txt](https://github.com/pichillilorenzo/flutter_inappwebview/files/11153455/main.txt)
t](https://github.com/pichillilorenzo/flutter_inappwebview/files/11153443/inappwebview-flutter-error-log.txt)

**Comment by MischaKr** [comment]
I'm getting the same error after upgrading to latest version of Flutter. (3.7.10)

**Comment by jaroslawdabrowski** [comment]
So I had the same issue. I spent some time to find the reason. It seems that this is due to the dependency bot that have updated the androidx.webkit version from 1.5.0 to 1.6.0 and later also to 1.6.1. The new version of android webkit does not know anything about the REQUESTED_WITH_HEADER_CONTROL and therefore we see this exception.

@pichillilorenzo can you or someone from your team take care of it? It seems that REQUESTED_WITH_HEADER_CONTROL is not longer supported, so it has to be removed and cleaned up. Thanks.

**Comment by ctemkar** [comment]
Thanks a lot, will try it
