### ISSUE TITLE
Incompatibility with latest background_downloader

### ISSUE THREAD

**Issue by mgilberti-horta** [pichillilorenzo/flutter_inappwebview#1836]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.16.0-12.0.pre.19  |
| Plugin version  | 6.0.0-beta.25 |
| Android version | 13              |

Device information: 
Samsung A14 5G

## Description
Simply adding background_downloader (7.10.1) import is causing our flutter_inappwebview (6.0.0-beta.25) based app to crash on Android in release mode (debug is working fine on both physical device and emulator).

**Expected behavior:** 
I was expecting it to work properly as in debug mode.

## Steps to reproduce
1. Create a new flutter_inappwebview base app (even examples are fine)
2. Add background_downloader to the pubspec.yaml
3. Add import 'package:background_downloader/background_downloader.dart'; to your main.dart
4. Run in release mode on a physical device or on emulator

## Stacktrace/Logcat   
[  +45 ms] E/flutter ( 5721): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: com.pichillilorenzo/flutter_inappwebview
[        ] E/flutter ( 5721): 	at io.flutter.plugin.platform.c0.M(SourceFile:1)
[        ] E/flutter ( 5721): 	at io.flutter.plugin.platform.c0$a.g(SourceFile:1)
[        ] E/flutter ( 5721): 	at b2.l$a.c(SourceFile:1)
[        ] E/flutter ( 5721): 	at b2.l$a.onMethodCall(SourceFile:1)
[        ] E/flutter ( 5721): 	at c2.i$a.a(SourceFile:1)
[        ] E/flutter ( 5721): 	at u1.c.k(SourceFile:1)
[        ] E/flutter ( 5721): 	at u1.c.l(SourceFile:1)
[        ] E/flutter ( 5721): 	at u1.c.d(SourceFile:1)
[        ] E/flutter ( 5721): 	at u1.b.run(SourceFile:1)
[        ] E/flutter ( 5721): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/flutter ( 5721): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/flutter ( 5721): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/flutter ( 5721): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/flutter ( 5721): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[        ] E/flutter ( 5721): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter ( 5721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/flutter ( 5721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] E/flutter ( 5721): , null, null)
[        ] E/flutter ( 5721): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
[        ] E/flutter ( 5721): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
[        ] E/flutter ( 5721): <asynchronous suspension>
[        ] E/flutter ( 5721): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1081)
[        ] E/flutter ( 5721): <asynchronous suspension>
[        ] E/flutter ( 5721): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804)
[        ] E/flutter ( 5721): <asynchronous suspension>
[        ] E/flutter ( 5721):

[full_verbose.log](https://github.com/pichillilorenzo/flutter_inappwebview/files/12926265/full_verbose.log)

**Comment by mgilberti-horta** [comment]
It turns out that code shrinking via R8 (enabled by default in release mode) was removing plugin registrations.
To fix it one can disable code shrinking by editing build.gradle:
```
   buildTypes {
       release {
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.release
       }
   }
```
or use a properly configured proguard file.
