### ISSUE TITLE
On Android onShowFileChooser sometimes throws an unhandled IllegalArgumentException which crashes the app with native SIGTRAP logs

### ISSUE THREAD

**Issue by DeArviss** [pichillilorenzo/flutter_inappwebview#1885]
This crash was responsible for ~2% crash rate for our app according to google play console crashlytics. I fixed it by adding a try-catch in a place where an unhandled exception is thrown (I used inappwebview as a local library). Last time I checked a few weeks ago, this crash was present in the latest flutter_inappwebview versions as well.

In google play this crash appeared as a SIGTRAP crash:
```
[base.apk!libmonochrome.so]
SIGTRAP

There was also a long native stack trace but I don't think it's relevant.
```

But if I catch and log the exception that apparently leads to this crash with stack trace, I get this:
```
java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.paypaypay.debug.flutter_inappwebview.fileprovider
                                                                                                    	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
                                                                                                    	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
                                                                                                    	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
                                                                                                    	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:449)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getOutputUri(InAppWebViewChromeClient.java:1158)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getPhotoIntent(InAppWebViewChromeClient.java:1026)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.startPickerIntent(InAppWebViewChromeClient.java:969)
                                                                                                    	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.onShowFileChooser(InAppWebViewChromeClient.java:801)
                                                                                                    	at WV.KY.h(chromium-TrichromeWebViewGoogle6432.aab-stable-604506733:36)
                                                                                                    	at WV.s8.runFileChooser(chromium-TrichromeWebViewGoogle6432.aab-stable-604506733:34)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:186)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

The fix I use was to wrap `getPhotoIntent` with try-catch. I didn't see any bugs or unexpected behaviour but I do realize that this is a crude fix so I decided to write an issue instead of making a PR.

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |            3.10.6 
| Plugin version  |       5.8.0        |
| Android version |       5 to 13        |
| iOS version     |         -      |
| macOS version   |      -         |
| Xcode version   |         -      |

Device information: Various Android devices. In google play crashlytics there were no any apparent patterns that could be applicable to devices. This crash happened on a wide range of phones.

## Description

**Expected behavior:** 
No crashes.

**Current behavior:** 
The app sometimes crashes when attempting to open the file picker of web content inside flutter_inappwebview

## Steps to reproduce

It's not really clear how to reproduce it exactly, it does not always happen when opening file picker.  But I manage to get this crash fairly often if I do something for a while and then try to use the file picker.

## Images   

https://github.com/pichillilorenzo/flutter_inappwebview/assets/117997531/ecd4c3d8-caba-4237-bd8d-56a02f2a8505

**Comment by pichillilorenzo** [comment]
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1890#issuecomment-1835665495
