### ISSUE TITLE
The issue with the "useHybridComposition" property.

### ISSUE THREAD

**Issue by wenshuoGong** [pichillilorenzo/flutter_inappwebview#1959]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology         | Version                                                       |
|-----------------| ---------------------------------------  |
| Flutter version    |    3.16.2
| Plugin version     |    6.0.0                                                        |
| Android version  |   AndroidX/12                                             |
| SDK version        |  compileSdk 34 / minSdkVersion 24       |

I created a Flutter module that imports the inappwebview 6.0.0 version. When I run the module as a Flutter app on an Android device, everything works fine. However, when I package the project as an AAR and import it into an Android app, it throws the following error in profile/release mode:
```
Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
```
The error does not occur in debug mode.

I tried setting the useHybridComposition property to false, which fixes the problem for a single webview container. However, the error is still thrown when multiple webview containers are opened. The error message is as follows:
```
java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
```
Is there any solution to this problem?

**Comment by wenshuoGong** [comment]
please T-T

**Comment by pichillilorenzo** [comment]
It seems more a problem with Flutter itself than my plugin.
The first errors says that it didn’t find the Flutter native channel for Flutter Platform Views, not my plugin channels.

**Comment by wenshuoGong** [comment]
> Can you post here full log of the second error?

The first error is likely caused by the FlutterEngine being created at the wrong time during Flutter embedding. My colleague created the FlutterEngine in onCreateView(), which caused the error "Channel not found" when the "useHybridComposition" property is set to "true". My temporary solution is to not register the plugin when creating the FlutterEngine, but to register it manually after FlutterEngineCache.getInstance().put(). However, I still feel that this is not a reasonable solution.

As for the second error, the complete log is as follows. It is worth noting that this issue also exists in inappwebview 5.8.0.

```
FATAL EXCEPTION: main
                                                                                                    Process: cbs.enterprise.com, PID: 10740
                                                                                                    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
                                                                                                    	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1683)
                                                                                                    	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1929)
                                                                                                    	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1235)
                                                                                                    	at It.c(chromium-TrichromeWebView.apk-stable-410310633:2)
                                                                                                    	at org.chromium.content.browser.input.ImeAdapterImpl.p0(chromium-TrichromeWebView.apk-stable-410310633:3)
                                                                                                    	at Ct.run(chromium-TrichromeWebView.apk-stable-410310633:31)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8401)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1102)
```

**Comment by wenshuoGong** [comment]
> Can you post here full log of the second error?

Thank you so much! I've been following your plugin for a few years now. It's really great. Unfortunately, this is my first time using it in production, so I've encountered a lot of new issues that I haven't encountered before. Thank you again for your answer.

**Comment by wenshuoGong** [comment]
、

> From what I can see for the second error log, there isn't any error coming directly from my plugin Android package. It seems there are no references at all, such as `at com.pichillilorenzo.flutter_inappwebview_android...`. I don't know what's going on, if it is something related to how you created the Flutter Engine or not.
> 
> As you said:
> 
> > When I run the module as a Flutter app on an Android device, everything works fine.
> 
> Maybe you should play around with your Flutter Engine, but other than that, I don't know. Unfortunately, I don't have any solution to that or I don't know what you need to do to setup a Flutter Engine correctly.

The second error also crashes when running Flutter standalone, but not on all Android devices. This happens when I turn off the "useHybridComposition" property.

**Comment by pichillilorenzo** [comment]
Are you able to share a minimal code example and steps to reproduce the issue?

**Comment by wenshuoGong** [comment]
> Are you able to share a minimal code example and steps to reproduce the issue?
```
GetX<CbsBaseWebviewController>(
        init: controller,
        global: false,
        builder: (_) {
                return Scaffold(
              extendBody: true,
              resizeToAvoidBottomInset: false,
              backgroundColor: _.backgroundColor.value,
              extendBodyBehindAppBar: _.extendBodyBehindAppBar.value,
              appBar: _.showAppbar.value
                  ? CBSWebviewAppBarView(
                      key: _.appbarKey,
                      controller: _.appBarController,
                      back: _.back.value,
                    )
                  : null,
              body: InAppWebview(
                      initialOptions: InAppWebViewGroupOptions(
                        crossPlatform: InAppWebViewOptions(
                          transparentBackground: true,
                          javaScriptEnabled: true,
                          useShouldOverrideUrlLoading: true,
                          supportZoom: false,
                        ),
                        android: AndroidInAppWebViewOptions(
                          supportMultipleWindows: true,
                          useHybridComposition:
                              true, //_.useHybridComposition.value,
                        ),
                        ios: IOSInAppWebViewOptions(
                          allowsBackForwardNavigationGestures: true,
                        ),
                      ),
                      initialUrlRequest: URLRequest(
                        // url: WebUri.uri(Uri.parse(_.url)),
                        url: Uri.parse(
                            'https://www.google.com/'),
                      )
              )
        }
)
```

The code is just like this.
In most devices, there is no problem after closing useHybridComposition. Currently, only one device in my hand has a problem.
The configuration of the device is as follows:
```
CPU: Unisoc T610
Memory: 4.0GB
Storage: 64GB
Android version: 10
Kernel version: 4.14.133+android@localhost # Wed Jan 1 19:38:22 CST 2023
Carrier firmware version: FM_BASE_19C_W22.49.5 | shark | 5pro_modem | 12-14-2022
```

**Comment by wenshuoGong** [comment]
New problem:
My Android app's home page has a FlutterFragment. Through the FlutterFragment, a FlutterActivity can be opened. The FlutterActivity has an inappwebview. If useHybridComposition is false, it will crash when there are multiple webviews, as in the previous problem. When useHybridComposition is true, it runs normally. However, when this FlutterActivity is closed, the FlutterFragment below becomes unresponsive, unable to render again, and can occasionally be clicked when the rendering mode is RenderMode.surface or RenderMode.image. When the rendering mode is changed to RenderMode.surface, the FlutterFragment becomes invisible after returning to the FlutterFragment.

**Comment by pichillilorenzo** [comment]
Please, post any useful logs.

**Comment by rRemix** [comment]
@wenshuoGong same issue..do you have any suggestion?

**Comment by cooaer** [comment]
I had the same problem. In my case, Android SDK <= 29 and useHybridComposition = true will cause this crash, so when Android SDK <= 29, I set useHybridComposition to false.
