### ISSUE TITLE
Android emulator app crash when API level below 34

### ISSUE THREAD

**Issue by asiteandroid** [pichillilorenzo/flutter_inappwebview#2020]
Application crash on emulator API level below 34 it's working fine in real device and also in emulator API level 34.
Every time it's give error **java.lang.IllegalArgumentException: statusCode can't be greater than 599.**
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |         3.13.8      |
| Plugin version        |         6.0.0      |
| Android version       |       34.0.0      |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
java.lang.IllegalArgumentException: statusCode can't be greater than 599.
E/AndroidRuntime(15191): 	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:149)
E/AndroidRuntime(15191): 	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:93)
E/AndroidRuntime(15191): 	at dF0.d(chromium-TrichromeWebViewGoogle6432.apk-stable-506007134:212)
E/AndroidRuntime(15191): 	at Sa.handleMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-506007134:215)
E/AndroidRuntime(15191): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15191): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(15191): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(15191): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(15191): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15191): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(15191): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by asiteandroid** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/assets/58687792/8db0b9f9-3d82-40fb-a021-9a8720cb9e4a

We have tried the sample demo of inAppwebview. Please find attached video for the reference.

You can notice that application is stuck after some navigation. Same thing is working fine in API level 34. 

Emulator details: Galaxy Nexus API 29

InAppWebView version: 6.0.0

**Comment by asiteandroid** [comment]
@pichillilorenzo Any update regrading this?

**Comment by jhva** [comment]
have you solved this problem?...

**Comment by asiteandroid** [comment]
@pichillilorenzo, can you please look into this issue as we experiencing it repeatedly.
