### ISSUE TITLE
App closes when I close the file picker (camera or file manager) without picking an image

### ISSUE THREAD

**Issue by RishabhPathak1211** [pichillilorenzo/flutter_inappwebview#2048]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |      3.19.1         |
| Plugin version        |      6.0.0         |

Device information: Multiple Android Devices

## Description

**Expected behavior:** Even if no file is selected in the file manager or no image is clicked using the camera and the file picker is closed, the app should simply return to the webview without crashing or closing.

**Current behavior:** If no file is selected using the above mentioned methods, the app immediately closes.

## Stacktrace/Logcat
This is the log I get before the app closes

```
E/AndroidRuntime( 5698): FATAL EXCEPTION: main
E/AndroidRuntime( 5698): Process: com.applicate.salescode.app, PID: 5698
E/AndroidRuntime( 5698): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.applicate.salescode.app/com.applicate.salescode.app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 5698): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5344)
E/AndroidRuntime( 5698): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5383)
E/AndroidRuntime( 5698): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 5698): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 5698): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 5698): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 5698): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
E/AndroidRuntime( 5698): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5698): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 5698): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 5698): 	at android.app.ActivityThread.main(ActivityThread.java:7892)
E/AndroidRuntime( 5698): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5698): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 5698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 5698): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 5698): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 5698): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
E/AndroidRuntime( 5698): 	at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:183)
E/AndroidRuntime( 5698): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
E/AndroidRuntime( 5698): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime( 5698): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:853)
E/AndroidRuntime( 5698): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
E/AndroidRuntime( 5698): 	at android.app.Activity.dispatchActivityResult(Activity.java:8608)
E/AndroidRuntime( 5698): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5337)
E/AndroidRuntime( 5698): 	... 13 more
I/Process ( 5698): Sending signal. PID: 5698 SIG: 9
```

**Comment by faaqi** [comment]
Hi @RishabhPathak1211 , were u able to resolve this issue? 

I'm facing pretty much same error when trying to upload the image from gallery.

[Issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2108)
