### ISSUE TITLE
Native method - J.N.MgWRfeHz (ANR)

### ISSUE THREAD

**Issue by tjoshi03** [pichillilorenzo/flutter_inappwebview#2063]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.7.12          |
| Plugin version        |       5.8.0        |
| Android version       |        13       |
| iOS version           |        -       |
| macOS version         |      -         |
| Xcode version         |       -        |
| Google Chrome version |        -       |

## Description

**Expected behavior:** 
it should not break

**Current behavior:** 
Getting lot of ANR on Android play console and firebase

## Stacktrace/Logcat 

"main" tid=1 Native
  #00  pc 0x0000000000089af0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
  #01  pc 0x000000000008e4d8  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
  #02  pc 0x00000000000f489c  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
  #03  pc 0x0000000002c1c6d8  /data/app/~~IdYCUvKv6qooxNu0NCYYnQ==/com.google.android.trichromelibrary_626106433-YPbid2s2RlKTkwWqkdUXSw==/base.apk (BuildId: ee35a0c07bc2fed2bbd74d50a745a65bc91c2e5e)
  #04  pc 0x0000000002c1b888  /data/app/~~IdYCUvKv6qooxNu0NCYYnQ==/com.google.android.trichromelibrary_626106433-YPbid2s2RlKTkwWqkdUXSw==/base.apk (BuildId: ee35a0c07bc2fed2bbd74d50a745a65bc91c2e5e)
  #05  pc 0x0000000002c1b594  /data/app/~~IdYCUvKv6qooxNu0NCYYnQ==/com.google.android.trichromelibrary_626106433-YPbid2s2RlKTkwWqkdUXSw==/base.apk (BuildId: ee35a0c07bc2fed2bbd74d50a745a65bc91c2e5e)
  #06  pc 0x0000000002c1c65c  /data/app/~~IdYCUvKv6qooxNu0NCYYnQ==/com.google.android.trichromelibrary_626106433-YPbid2s2RlKTkwWqkdUXSw==/base.apk (BuildId: ee35a0c07bc2fed2bbd74d50a745a65bc91c2e5e)
  #07  pc 0x000000000472f8a0  /data/app/~~IdYCUvKv6qooxNu0NCYYnQ==/com.google.android.trichromelibrary_626106433-YPbid2s2RlKTkwWqkdUXSw==/base.apk (BuildId: ee35a0c07bc2fed2bbd74d50a745a65bc91c2e5e)
  at J.N.MgWRfeHz (Native method)
  at com.android.webview.chromium.a.flush (chromium-TrichromeWebViewGoogle6432.aab-stable-626106433:17)
  at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewClient.onPageFinished (InAppWebViewClient.java:226)
  at WV.e00.b (chromium-TrichromeWebViewGoogle6432.aab-stable-626106433:12)
  at WV.D6.handleMessage (chromium-TrichromeWebViewGoogle6432.aab-stable-626106433:261)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:211)
  at android.os.Looper.loop (Looper.java:300)
  at android.app.ActivityThread.main (ActivityThread.java:8432)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:560)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:954)

**Comment by tianlang321** [comment]
me too


J.N.MgWRfeHz(Native Method)
2
a7.flush(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3)
3
com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebViewClientCompat.onPageFinished(InAppWebViewClientCompat.java:9)
4
Fa.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2)
5
Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410683:65)
6
android.os.Handler.dispatchMessage(Handler.java:110)
7
android.os.Looper.loop(Looper.java:219)
8
android.app.ActivityThread.main(ActivityThread.java:8679)
9
java.lang.reflect.Method.invoke(Native Method)
10
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
11
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by endyquang** [comment]
I'm also seeing lots of this ANR on Play console. It started spiking after I upgraded Flutter from `3.19` to `3.27`.
Probably something is blocking the main thread in `InAppWebViewClientCompat.onPageFinished`?

```
  #00  pc 0x000000000005df98  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x0000000000063ab5  /apex/com.android.runtime/lib/bionic/libc.so (__futex_wait_ex+92)
This native synchronization routine is blocking the main thread, causing an ANR. [Learn more](https://developer.android.com/topic/performance/anrs/find-unresponsive-thread#lock-contention)

  #02  pc 0x00000000000ad83b  /apex/com.android.runtime/lib/bionic/libc.so (pthread_cond_wait+32)
  #03  pc 0x00000000029a763f  /data/app/~~IObxTglK3GEW-br6MTT1UQ==/com.google.android.trichromelibrary_694312130-vjZSwBUOoQKPHjwYuCYUAw==/base.apk (BuildId: 729e52a44bfbb3a04be0e98d3fcc9e5fbe48183d)
  #04  pc 0x000000000291c8c1  /data/app/~~IObxTglK3GEW-br6MTT1UQ==/com.google.android.trichromelibrary_694312130-vjZSwBUOoQKPHjwYuCYUAw==/base.apk (BuildId: 729e52a44bfbb3a04be0e98d3fcc9e5fbe48183d)
  #05  pc 0x000000000291c621  /data/app/~~IObxTglK3GEW-br6MTT1UQ==/com.google.android.trichromelibrary_694312130-vjZSwBUOoQKPHjwYuCYUAw==/base.apk (BuildId: 729e52a44bfbb3a04be0e98d3fcc9e5fbe48183d)
  #06  pc 0x0000000000f805f9  /data/app/~~IObxTglK3GEW-br6MTT1UQ==/com.google.android.trichromelibrary_694312130-vjZSwBUOoQKPHjwYuCYUAw==/base.apk (BuildId: 729e52a44bfbb3a04be0e98d3fcc9e5fbe48183d)
  #07  pc 0x0000000000f7fbfb  /data/app/~~IObxTglK3GEW-br6MTT1UQ==/com.google.android.trichromelibrary_694312130-vjZSwBUOoQKPHjwYuCYUAw==/base.apk (BuildId: 729e52a44bfbb3a04be0e98d3fcc9e5fbe48183d)
  at androidx.core.view.VelocityTrackerFallback._V_JO (VelocityTrackerFallback.java)
  at com.android.webview.chromium.a.flush (chromium-TrichromeWebViewGoogle.aab-stable-694312130:18)
  at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebViewClientCompat.onPageFinished (InAppWebViewClientCompat.java:235)
  at WV.OZ.b (chromium-TrichromeWebViewGoogle.aab-stable-694312130:12)
  at WV.m7.handleMessage (chromium-TrichromeWebViewGoogle.aab-stable-694312130:258)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8919)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:578)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
```

**Comment by endyquang** [comment]
I think I found the cause. I can produce it consistently on my Android 14 device now.
It may be because of the `shouldInterceptRequest`. Removing it fixed my problem.
`flutter_inappwebview@6.1.5` and `@6.2.0-beta.2`

<details>
<summary>Steps with code example to reproduce</summary>

1. Run this code.
2. Keep tapping the floating button to refresh until the app freezes. For me it takes from 2 to 5 times.
3. Remove the `shouldInterceptRequest`
4. Restart the app and keep tapping again, expect no problem

```dart
// main.dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Test', home: const MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final InAppWebViewController _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InAppWebView(
        initialUrlRequest: URLRequest(url: WebUri('https://www.amazon.com/')),
        initialSettings: InAppWebViewSettings(),
        onWebViewCreated: (controller) => _controller = controller,
        shouldInterceptRequest: (controller, request) async => null,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _controller.reload(),
        tooltip: 'Reload',
        child: const Icon(Icons.refresh),
      ),
    );
  }
}
```
</details>


<details>
<summary>Stacktrace/Logs</summary>

```
[AndroidInAppWebViewController] (android) WebView ID 0 calling "shouldInterceptRequest" using {headers: {User-Agent: Mozilla/5.0 (Linux; Android 14; 22041216UC Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/134.0.6998.39 Mobile Safari/537.36, Referer: https://www.amazon.com/, sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Android WebView";v="134", sec-ch-ua-mobile: ?1, Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8, sec-ch-ua-platform: "Android"}, isRedirect: false, method: GET, hasGesture: false, isForMainFrame: false, url: https://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:144-1794739-5301636:SYNDCMT3MEH0WSQGS6WZ$uedata=s:%2Frd%2Fuedata%3Fld%26v%3D0.308124.0%26id%3DSYNDCMT3MEH0WSQGS6WZ%26ctb%3D1%26sc0%3Due_sushi_v1%26bb0%3D981%26pc0%3D981%26ld0%3D981%26t0%3D1742329359932%26pty%3Dexports-gateway-phone-web%26spty%3Dmobile%26pti%3Dmobile%26tid%3D0YXN5FB46JV3HC6JPJS2%26aftb%3D1%26lob%3D1:981}
[AndroidInAppWebViewController] (android) WebView ID 0 calling "shouldInterceptRequest" using {headers: {sec-ch-viewport-width: 392, X-Requested-With: XMLHttpRequest, Accept: text/html,*/*, downlink: 10, dpr: 2.75, User-Agent: Mozilla/5.0 (Linux; Android 14; 22041216UC Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/134.0.6998.39 Mobile Safari/537.36, Referer: https://www.amazon.com/, device-memory: 8, sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Android WebView";v="134", viewport-width: 392, sec-ch-dpr: 2.75, sec-ch-ua-mobile: ?1, rtt: 0, sec-ch-ua-platform: "Android", ect: 4g, sec-ch-device-memory: 8, sec-ch-ua-platform-version: "14.0.0"}, isRedirect: false, method: GET, hasGesture: false, isForMainFrame: false, url: https://www.amazon.com/portal-migration/hz/glow/get-rendered-toaster?pageType=exports-gateway-phone-web&aisTransitionState=null&rancorLocationSource=IP_GEOLOCATION&_=1742329359944}
W/MIUIScout App(28028): Enter APP_SCOUT_WARNING State
W/MIUIScout App(28028):  (Current message: duration=2870ms seq=2035 late=37ms h=WV.r7 w=9)
D/AppScoutStateMachine(28028): dump trace dirName = 2025-03-19-03-22-42-28028-APP_SCOUT_WARNING-com.example.test_wb
W/MIUIScout App(28028): Event:APP_SCOUT_WARNING Thread:main backtrace:
W/MIUIScout App(28028):     at J.N.VJO(Native Method)
W/MIUIScout App(28028):     at com.android.webview.chromium.a.flush(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:18)
W/MIUIScout App(28028):     at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebViewClientCompat.onPageFinished(InAppWebViewClientCompat.java:235)
W/MIUIScout App(28028):     at WV.l00.b(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:12)
W/MIUIScout App(28028):     at WV.r7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:258)
W/MIUIScout App(28028):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(28028):     at android.os.Looper.loopOnce(Looper.java:222)
W/MIUIScout App(28028):     at android.os.Looper.loop(Looper.java:314)
W/MIUIScout App(28028):     at android.app.ActivityThread.main(ActivityThread.java:8716)
W/MIUIScout App(28028):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(28028):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
W/MIUIScout App(28028):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
I/example.test_wb(28028): Thread[6,tid=31158,WaitingInMainSignalCatcherLoop,Thread*=0xb4000073ad02a000,peer=0x77980258,"Signal Catcher"]: reacting to signal 3
I/example.test_wb(28028): 
I/example.test_wb(28028): Wrote stack traces to tombstoned
W/MIUIScout App(28028): Enter APP_SCOUT_HANG state
W/MIUIScout App(28028):  (Current message: duration=5374ms seq=2035 late=37ms h=WV.r7 w=9)
D/AppScoutStateMachine(28028): dump trace dirName = 2025-03-19-03-22-45-28028-APP_SCOUT_HANG-com.example.test_wb
W/MIUIScout App(28028): Event:APP_SCOUT_HANG Thread:main backtrace:
W/MIUIScout App(28028):     at J.N.VJO(Native Method)
W/MIUIScout App(28028):     at com.android.webview.chromium.a.flush(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:18)
W/MIUIScout App(28028):     at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebViewClientCompat.onPageFinished(InAppWebViewClientCompat.java:235)
W/MIUIScout App(28028):     at WV.l00.b(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:12)
W/MIUIScout App(28028):     at WV.r7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:258)
W/MIUIScout App(28028):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(28028):     at android.os.Looper.loopOnce(Looper.java:222)
W/MIUIScout App(28028):     at android.os.Looper.loop(Looper.java:314)
W/MIUIScout App(28028):     at android.app.ActivityThread.main(ActivityThread.java:8716)
W/MIUIScout App(28028):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(28028):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
W/MIUIScout App(28028):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
I/example.test_wb(28028): Thread[6,tid=31158,WaitingInMainSignalCatcherLoop,Thread*=0xb4000073ad02a000,peer=0x77980258,"Signal Catcher"]: reacting to signal 3
I/example.test_wb(28028): 
I/example.test_wb(28028): Wrote stack traces to tombstoned
I/example.test_wb(28028): Thread[6,tid=31158,WaitingInMainSignalCatcherLoop,Thread*=0xb4000073ad02a000,peer=0x77980258,"Signal Catcher"]: reacting to signal 3
I/example.test_wb(28028): 
D/MIUIScout ANR(28028): get period history msg: (Current message: duration=8483ms seq=2035 late=37ms h=WV.r7 w=9)
D/MIUIScout ANR(28028): get period history msg:messages for the same target android.view.Choreographer$FrameHandler execute time>50ms (count=181 totalwalltime=497ms h=android.view.Choreographer$FrameHandler whatORcallback=android.view.Choreographer$FrameDisplayEventReceiver)
D/MIUIScout ANR(28028): get period history msg:messages for the same target android.os.Handler execute time>50ms (count=64 totalwalltime=53ms h=android.os.Handler whatORcallback=com.pichillilorenzo.flutter_inappwebview_android.Util$1)
D/MIUIScout ANR(28028): get period history msg:In recent 20s, total historyMsgCount=512
W/MIUIScout ANR(28028): Print Message Id: 0 MessageInfo: { when=-8s520ms callback=android.view.Choreographer$FrameDisplayEventReceiver target=android.view.Choreographer$FrameHandler }
W/MIUIScout ANR(28028): Print Message Id: 1 MessageInfo: { when=-8s516ms barrier=601 }
W/MIUIScout ANR(28028): Print Message Id: 2 MessageInfo: { when=-8s504ms callback=android.graphics.HardwareRendererObserver$$ExternalSyntheticLambda0 target=android.view.ViewRootImpl$ViewRootHandler }
W/MIUIScout ANR(28028): Print Message Id: 3 MessageInfo: { when=-8s501ms callback=com.pichillilorenzo.flutter_inappwebview_android.Util$1 target=android.os.Handler }
W/MIUIScout ANR(28028): Print Message Id: 4 MessageInfo: { when=-8s500ms callback=com.pichillilorenzo.flutter_inappwebview_android.Util$1 target=android.os.Handler }
W/MIUIScout ANR(28028): (Print messages: 5, polling=false, quitting=false)
I/example.test_wb(28028): Wrote stack traces to tombstoned
```
</details>

@pichillilorenzo Please check. Thanks!

**Comment by tulioccalazans** [comment]
I'm also seeing lots of this ANR on Play console. It is also related to InAppWebViewClientCompat.onPageFinished.

`          main (native):tid=1 systid=13195 
#00 pc 0x902fc libc.so (syscall + 28) (BuildId: 84a42637b3a421b801818f5793418fca)
#01 pc 0x950d0 libc.so (__futex_wait_ex + 144) (BuildId: 84a42637b3a421b801818f5793418fca)
#02 pc 0x101028 libc.so (pthread_cond_wait + 72) (BuildId: 84a42637b3a421b801818f5793418fca)
#03 pc 0x5567664 base.apk + 9289728 (BuildId: 5d8a33cef9acb1363647f3d581bf728d3bd14151)
#04 pc 0x54c20b0 base.apk + 9289728 (BuildId: 5d8a33cef9acb1363647f3d581bf728d3bd14151)
#05 pc 0x556749c base.apk + 9289728 (BuildId: 5d8a33cef9acb1363647f3d581bf728d3bd14151)
#06 pc 0x20097e0 base.apk + 9289728 (BuildId: 5d8a33cef9acb1363647f3d581bf728d3bd14151)
       at J.N.VJO(Native method)
       at com.android.webview.chromium.a.flush(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:18)
       at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebViewClientCompat.onPageFinished(InAppWebViewClientCompat.java:235)
       at WV.l00.b(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:12)
       at WV.r7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-699803933:258)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at android.app.ActivityThread.main(ActivityThread.java:8779)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1090)
        `

**Comment by hyo-choi** [comment]
@tulioccalazans Hi, we are also experiencing ANR issue with exactly the same stack trace, without using `shouldInterceptRequest`. Do you have any progress?

**Comment by stonemaster** [comment]
I am also experiencing ANRs that relate to  `InAppWebViewClientCompat.onPageFinished` using the latest stable Version of this plugin, as well as Flutter 3.29.2.

The problem is just on Android, iOS is unaffected.

**Comment by hyo-choi** [comment]
@stonemaster @tulioccalazans 
Hi, our team was thinking about this issue and found that [the flush method of CookieManager is a synchronous method that performs I/O operations](https://developer.android.com/reference/android/webkit/CookieManager#flush()), so we assumed that this line was the cause of the problem.
So we forked the flutter_inappwebview repository, removed [this line(and other `flush` calls)](https://github.com/pichillilorenzo/flutter_inappwebview/blob/0aaf7a0bfc01d61a4d1453cefb57fb6783b6e676/flutter_inappwebview_android/android/src/main/java/com/pichillilorenzo/flutter_inappwebview_android/webview/in_app_webview/InAppWebViewClient.java#L249), and when we made our app use the forked version, the ANR was no longer reported.
If you ever need a quick fix, give it a try.

**Comment by jin-motemote** [comment]
https://issues.chromium.org/issues/404563944

**Comment by stonemaster** [comment]
I can confirm what @hyo-choi suggested: commenting those lines out in a forked version of flutter_inappwebview_android is enough to get rid of the ANRs for now. I am unsure about the implications yet, as the code suggest that flushing the `CookieManager` was needed at some point in time.

**Comment by tulioccalazans** [comment]
Thanks I commented out these lines of code and I will test it

**Comment by namnh-0652** [comment]
We have this ANR too. We use **Flutter 3.24.5** & **flutter_inappwebview 6.1.5**

here is our console log
```log
"main" tid=1 Native
  #00  pc 0x000000000004dc5c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x00000000000524b8  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
  #02  pc 0x00000000000b42bc  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+84)
  #03  pc 0x00000000055630c4  /data/app/~~sjrFs2BN7CW22EqVu4zLWA==/com.google.android.trichromelibrary_699813533-bp906ZKaBq56kobynZZEzg==/base.apk (BuildId: e8dcb611cc3cb26f7babf3e164d9395cfcab25c8)
  #04  pc 0x00000000054bd9d8  /data/app/~~sjrFs2BN7CW22EqVu4zLWA==/com.google.android.trichromelibrary_699813533-bp906ZKaBq56kobynZZEzg==/base.apk (BuildId: e8dcb611cc3cb26f7babf3e164d9395cfcab25c8)
  #05  pc 0x0000000005562efc  /data/app/~~sjrFs2BN7CW22EqVu4zLWA==/com.google.android.trichromelibrary_699813533-bp906ZKaBq56kobynZZEzg==/base.apk (BuildId: e8dcb611cc3cb26f7babf3e164d9395cfcab25c8)
  #06  pc 0x000000000200c6e0  /data/app/~~sjrFs2BN7CW22EqVu4zLWA==/com.google.android.trichromelibrary_699813533-bp906ZKaBq56kobynZZEzg==/base.apk (BuildId: e8dcb611cc3cb26f7babf3e164d9395cfcab25c8)
  at J.N.VJO (Native method)
  at com.android.webview.chromium.a.flush (chromium-TrichromeWebViewGoogle6432.aab-stable-699813533:18)
  at com.pichillilorenzo.flutter_inappwebview_android.MyCookieManager.setCookie (MyCookieManager.java:191)
  at com.pichillilorenzo.flutter_inappwebview_android.MyCookieManager.onMethodCall (MyCookieManager.java:67)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:267)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:292)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:319)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:346)
  at android.os.Looper.loop (Looper.java:475)
  at android.app.ActivityThread.main (ActivityThread.java:7889)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1009)
```

**Comment by akhilesh-sharma-GSY** [comment]
@pichillilorenzo is there any plan for triaging this bug?

**Comment by PhilippeNormand-norsys** [comment]
It seems that Android is aware of this issue, that can be found under the update 134 android webview.
https://issues.chromium.org/issues/404563944
A fix is apparently coming with the update 136.
