### ISSUE TITLE
A AndroidPullToRefreshController was used after being disposed

### ISSUE THREAD

**Issue by maxmitz** [pichillilorenzo/flutter_inappwebview#2104]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

[Lorenzo Pichilli](https://github.com/pichillilorenzo) Thanks for maintaining the InAppWebView!

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.19.3          |
| Plugin version        |       6.0.0        |
| Android version       |     33.0.1      |
| iOS version           |        17.4.1       |
| macOS version         |         -      |
| Xcode version         |       15.0        |
| Google Chrome version |     -          |

Device information:  reproducible on emulators and on  real devices

## Description

I am not 100% sure if this is a bug or intended. I think it is a bug.

When I reload the web view fast multiple times. The AndroidInAppWebViewWidget wants to dispose the AndroidPullToRefreshController but the controller was already disposed. 

For the given example, there should be a timeout or something similar on the floatingActionButton but in general, I think that this should be the responsibility of the plugin to check if the pulltorefreshcontroller was already disposed, or do I oversee something?

https://github.com/pichillilorenzo/flutter_inappwebview/issues/1997#issuecomment-1921084524

In this comment [Lorenzo Pichilli](https://github.com/pichillilorenzo) stated that the InAppWebViewController is null if it was disposed. Shouldn't the same apply to the RefreshController? 

From in_app_webview.dart
    params.pullToRefreshController?.dispose(isKeepAlive: isKeepAlive);

**Expected behavior:** 

The plugin should check if PulltoRefreshController was disposed.

**Current behavior:** 

The implementing developer has to check if the PullToRefreshController has been disposed

## Steps to reproduce

1. Run code
2. Click fast multiple times on the floatingActionButton.
3. Error occurs.

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  UniqueKey key = UniqueKey();

  @override
  Widget build(BuildContext context) {
    final pullToRefreshController = PullToRefreshController();

    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: InAppWebView(
              key: key,
              pullToRefreshController: pullToRefreshController,
              onLoadStop: (_, __) {
                pullToRefreshController.endRefreshing();
              },
              initialUrlRequest:
                  URLRequest(url: WebUri.uri(Uri.parse("https://flutter.dev"))),
            ),
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            key = UniqueKey();
          });
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

## Images   

<img width="1468" alt="Bildschirmfoto 2024-04-15 um 13 07 36" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/72440045/a7239b93-fc7d-4748-ba74-0ba71df94d51">

## Stacktrace/Logcat   

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A AndroidPullToRefreshController was used after being disposed.
Once the AndroidPullToRefreshController has been disposed, it can no longer be used.

When the exception was thrown, this was the stack:
#0      ChannelController.debugAssertNotDisposed.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:595:9)
util.dart:595
#1      ChannelController.debugAssertNotDisposed (package:flutter_inappwebview_platform_interface/src/util.dart:602:6)
util.dart:602
#2      InternalChannelController.channel (package:flutter_inappwebview_platform_interface/src/util.dart:611:30)
util.dart:611
#3      InternalChannelController.disposeChannel (package:flutter_inappwebview_platform_interface/src/util.dart:641:7)
util.dart:641
#4      AndroidPullToRefreshController.dispose (package:flutter_inappwebview_android/src/pull_to_refresh/pull_to_refresh_controller.dart:152:5)
pull_to_refresh_controller.dart:152
#5      AndroidInAppWebViewWidget.dispose (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview.dart:467:37)
in_app_webview.dart:467
#6      _InAppWebViewState.dispose (package:flutter_inappwebview/src/in_app_webview/in_app_webview.dart:673:21)
in_app_webview.dart:673
#7      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689:11)
framework.dart:5689
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076:13)
framework.dart:2076

**Comment by Julied5** [comment]
Is there any update on this ? I'm getting the same issue since 6.0.0 upgrade, does someone have a way to prevent this error ?

**Comment by 2x2xplz** [comment]
Same issue. This appears to be a leftover debugging artifact that could be removed from the release version. If the developer manually disposes the webview and its controller, eventually the library internally calls its own `dispose()` method, which calls `debugAssertNotDisposed()`. This method throws an error below when the controller has already been disposed. Maybe the controller could be checked for disposal further up the stack rather than in this `assert`.

In the meantime, you can avoid this error by manually `dispose()`ing your webview, but NOT disposing the controller. But I think I'd rather dispose them both myself rather than just assume it will happen automatically.

```dart
  static bool debugAssertNotDisposed(ChannelController controller) {
    assert(() {
      if (controller.disposed) {
        throw FlutterError(
          'A ${controller.runtimeType} was used after being disposed.\n'
          'Once the ${controller.runtimeType} has been disposed, it '
          'can no longer be used.',
        );
      }
      return true;
    }());
    return true;
  }
```

```
E/flutter ( 4982): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A AndroidInAppWebViewController was used after being disposed.
E/flutter ( 4982): Once the AndroidInAppWebViewController has been disposed, it can no longer be used.
E/flutter ( 4982): #0      ChannelController.debugAssertNotDisposed.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:595:9)
E/flutter ( 4982): #1      ChannelController.debugAssertNotDisposed (package:flutter_inappwebview_platform_interface/src/util.dart:602:6)
E/flutter ( 4982): #2      InternalChannelController.channel (package:flutter_inappwebview_platform_interface/src/util.dart:611:30)
E/flutter ( 4982): #3      InternalChannelController.disposeChannel (package:flutter_inappwebview_platform_interface/src/util.dart:641:7)
E/flutter ( 4982): #4      AndroidInAppWebViewController.dispose (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart:2756:5)
E/flutter ( 4982): #5      AndroidHeadlessInAppWebView.dispose (package:flutter_inappwebview_android/src/in_app_webview/headless_in_app_webview.dart:427:25)
```

**Comment by Harishwarrior** [comment]
> Same issue. This appears to be a leftover debugging artifact that could be removed from the release version. If the developer manually disposes the webview and its controller, eventually the library internally calls its own `dispose()` method, which calls `debugAssertNotDisposed()`. This method throws an error below when the controller has already been disposed. Maybe the controller could be checked for disposal further up the stack rather than in this `assert`.
> 
> In the meantime, you can avoid this error by manually `dispose()`ing your webview, but NOT disposing the controller. But I think I'd rather dispose them both myself rather than just assume it will happen automatically.
> 
> ```dart
>   static bool debugAssertNotDisposed(ChannelController controller) {
>     assert(() {
>       if (controller.disposed) {
>         throw FlutterError(
>           'A ${controller.runtimeType} was used after being disposed.\n'
>           'Once the ${controller.runtimeType} has been disposed, it '
>           'can no longer be used.',
>         );
>       }
>       return true;
>     }());
>     return true;
>   }
> ```
> 
> ```
> E/flutter ( 4982): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A AndroidInAppWebViewController was used after being disposed.
> E/flutter ( 4982): Once the AndroidInAppWebViewController has been disposed, it can no longer be used.
> E/flutter ( 4982): #0      ChannelController.debugAssertNotDisposed.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:595:9)
> E/flutter ( 4982): #1      ChannelController.debugAssertNotDisposed (package:flutter_inappwebview_platform_interface/src/util.dart:602:6)
> E/flutter ( 4982): #2      InternalChannelController.channel (package:flutter_inappwebview_platform_interface/src/util.dart:611:30)
> E/flutter ( 4982): #3      InternalChannelController.disposeChannel (package:flutter_inappwebview_platform_interface/src/util.dart:641:7)
> E/flutter ( 4982): #4      AndroidInAppWebViewController.dispose (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart:2756:5)
> E/flutter ( 4982): #5      AndroidHeadlessInAppWebView.dispose (package:flutter_inappwebview_android/src/in_app_webview/headless_in_app_webview.dart:427:25)
> ```

How can you dispose the webview instead of the controller?
