### ISSUE TITLE
Android issue: Unknown feature SUPPRESS_ERROR_PAGE, webview not displaying at all

### ISSUE THREAD

**Issue by kasperkowalski** [pichillilorenzo/flutter_inappwebview#2150]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       | Flutter (Channel stable, 3.22.1) |
| Plugin version        | ^6.0.0 |
| Android version       | Android toolchain - develop for Android devices (Android SDK version 34.0.0) |
| iOS version           | 17.2 |
| macOS version         | macOS 14.1.2 23B92 darwin-arm64 |
| Xcode version         | 15.1 |
| Google Chrome version | 124.0.6367.179 |
| Gradle | 8.4 |

Device information: 
| SM G950F (mobile) | android-arm64 | Android 9 (API 28) |
|  sdk gphone64 arm64 (mobile) | android-arm64 | Android 13 (API 33) (emulator) |

## Description

**Expected behavior:** 
Widget with webview should be visible.

**Current behavior:** 
Widget with webview is not visible on Android after upgrade plugin to v.6.0.0, 
worked fine on v.5.8.0 and is working fine on iOS in both versions.

## Steps to reproduce

1. Widget code:
```dart
Widget build(BuildContext context) {

final html = """
    <html lang="pl">
    <meta name="viewport" content="width=100, initial-scale=1, user-scalable=no">
    <style>iframe {max-width:100%; border: 0; overflow:hidden;} </style>
    <style>html,body { margin: 0; } </style>
    <body>
      <div class="container" id="_flutter_target_do_not_delete">$replacedHtml</div>
      <script>
      function outputsize() {
          if (typeof window.flutter_inappwebview !== "undefined" && typeof window.flutter_inappwebview.callHandler !== "undefined")
              window.flutter_inappwebview.callHandler('newHeight', document.getElementById("_flutter_target_do_not_delete").firstChild.offsetHeight);
          }
        new ResizeObserver(outputsize).observe(_flutter_target_do_not_delete)
      </script>
    </body>
    </html>
""";

    final Widget webviewWidget = SizedBox(
      height: height,
      width: double.infinity,
      child: InAppWebView(
        initialData: InAppWebViewInitialData(data: html),
        initialSettings: InAppWebViewSettings(
          transparentBackground: true,
          supportZoom: false,
          disableHorizontalScroll: true,
          disableVerticalScroll: true,
        ),
        onWebViewCreated: (InAppWebViewController controller) {
          controller.addJavaScriptHandler(
            handlerName: 'newHeight',
            callback: (List<dynamic> arguments) async {
              final contentHeight = await controller.getContentHeight();
              final zoomScale = await controller.getZoomScale();
              final htmlHeight = contentHeight!.toDouble() * zoomScale!;
              final htmlHeightFixed =
                  double.parse(htmlHeight.toStringAsFixed(2));
              if (htmlHeightFixed == 0.0) {
                return;
              }

              final int? innerHeight;
              if (arguments.isNotEmpty) {
                innerHeight = arguments[0] as int;
              } else {
                innerHeight = await controller.getContentHeight();
              }

              if (mounted) {
                setState(
                  () =>
                      height = (innerHeight != null &&
                              innerHeight.toDouble() > htmlHeightFixed)
                          ? innerHeight.toDouble()
                          : htmlHeightFixed,
                );
              }
            },
          );
        },
      ),
    );

    if (widget.disablePadding ?? false) {
      return webviewWidget;
    }

    return Column(
      children: [
        TabletMargins(
          mobilePadding: AppSpacing.lg,
          child: webviewWidget,
        ),
        const SizedBox(),
      ],
    );
```
2. console output:
```log
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 0
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 1
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 0
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 1
I/flutter (16853): Fetching article: 40431721
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 0
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 1
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 0
D/InAppWebView(16853): Using InAppWebViewClientCompat implementation
W/cr_SupportWebSettings(16853): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings(16853): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views(16853): Failed to handle method call
E/MethodChannel#flutter/platform_views(16853): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views(16853): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:640)
E/MethodChannel#flutter/platform_views(16853): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:609)
E/MethodChannel#flutter/platform_views(16853): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:600)
E/MethodChannel#flutter/platform_views(16853): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views(16853): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views(16853): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:525)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:170)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(16853): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(16853): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#flutter/platform_views(16853): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(16853): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#flutter/platform_views(16853): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/MethodChannel#flutter/platform_views(16853): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(16853): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#flutter/platform_views(16853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
[log] PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
      	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:640)
      	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:609)
      	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:600)
      	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
      	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
      	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
      	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:525)
      	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:170)
      	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
      	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
      	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
      	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
      	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
      	at android.os.Handler.handleCallback(Handler.java:873)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loop(Looper.java:214)
      	at android.app.ActivityThread.main(ActivityThread.java:7050)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
      )
[log] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
      <asynchronous suspension>
      #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
      <asynchronous suspension>
      #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
      <asynchronous suspension>
D/ViewRootImpl@8159f1b[MainActivity](16853): ViewPostIme pointer 1
```

**Comment by kasperkowalski** [comment]
after some debugging I've noticed it's not the issue of version 6.0.0, it was working correctly on that version yesterday, i'm going to make some more checks what has changed

**Comment by kasperkowalski** [comment]
I'm not yet 100% sure but I think the issue was caused by bumping other dependency: `webview_flutter_android` from version `3.16.1` to `3.16.2`
it's changelog says for this version:
*Bumps androidx.webkit:webkit from 1.7.0 to 1.10.0.*

**Comment by SuhwanCha** [comment]
> I'm not yet 100% sure but I think the issue was caused by bumping other dependency: `webview_flutter_android` from version `3.16.1` to `3.16.2` it's changelog says for this version: _Bumps androidx.webkit:webkit from 1.7.0 to 1.10.0._

This also works for me. I had webview_flutter_android dependency in other packages, but it works when I fixed it to 3.16.1.
webview_flutter_android 3.16.2 was released 21 hours ago. It's an issue that happened after that

https://pub.dev/packages/webview_flutter_android/versions

**Comment by Dkdeveloper24** [comment]
I'm using the webview 6.0.0 in flutterflow. For me downgrading webview_flutter_android is not working. Any solution?

**Comment by kasperkowalski** [comment]
@Dkdeveloper24 maybe some other library in your stack is using never version of androidx.webkit:webkit, but first I would check if correct version is added to dependency overrides and all caches are clear.

**Comment by jlcool** [comment]
``` dart
dependency_overrides:
  webview_flutter_android: 3.16.1
```

**Comment by moshe5745** [comment]
Trying deleting pub-cache + pub-cached directories
Solved this in our place

**Comment by NoboChai** [comment]
In my case, to avoid the error,
webview_flutter_android: 3.16.1
In addition to doing this in /myproject/android/app/build.gradle
dependencies {
     implementation("com.google.android.gms:play-services-ads:23.1.0")
}
part of
"com.google.android.gms:play-services-ads:23.0.0"
I had to downgrade to .

**Comment by ttb-inc** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

In my case, this worked for me.
We hope to have the package stabilised soon.

Thanks a lot.

**Comment by moshe5745** [comment]
> Try to delete pub-cache + pub-cached directories Solved this in our place

I would suggest try this before anything else
Not need to add some overrides if it’s just a cache problem

**Comment by cloudygeek** [comment]
Same issue, and even using 
dependency_overrides:
  webview_flutter_android: 3.16.1
doesn't fix. have deleted all ~/.pub-cache, same.

**Comment by moshe5745** [comment]
> Same issue, and even using dependency_overrides: webview_flutter_android: 3.16.1 doesn't fix. have deleted all ~/.pub-cache, same.

Did you run “flutter clean” before?

**Comment by mahitechnologies259** [comment]
Any latest Solutions?

**Comment by ThanhPhungTien** [comment]
In my case, go back to 5.8.0 worked for me.

**Comment by dileepvarmau** [comment]
In my case switching the flutter sdk back to 3.19.6 stable version and dependency_overrides of webview_flutter_android to 3.16.1 worked.

**Comment by hisham-safade** [comment]
dependency_overrides:
  webview_flutter_android: 3.16.1
worked for me thank you.

**Comment by Aleksandar1204** [comment]
I had the same problem on InAppWebView plugin v.6.0.0, any update?

**Comment by ayechan-maung** [comment]
dependency_overrides: 

is not work for me (;

**Comment by AYoungXXX** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

I had the same problem with oppo phones and it worked

**Comment by a-v-ebrahimi** [comment]
Same problem here, this solved it :
```
    dependency_overrides:
      webview_flutter_android: 3.16.1
```

**Comment by emadzeebrix305** [comment]
> Same problem here, this solved it :
> 
> ```
>     dependency_overrides:
>       webview_flutter_android: 3.16.1
> ```

Thanks this wokred for me on android 13

**Comment by Aleksandar1204** [comment]
> dependency_overrides:
>       webview_flutter_android: 3.16.1

dependency_overrides:
      webview_flutter_android: 3.16.1

work

**Comment by dooully** [comment]
> Same problem here, this solved it :
> 
> ```
>     dependency_overrides:
>       webview_flutter_android: 3.16.1
> ```

Thank you. 
It helped me, too.

**Comment by MariusBelciug** [comment]
I had the same issue and moving back to flutter_inappwebview: ^5.8.0 solved it.

**Comment by shivam2702** [comment]
Do anyone know the ticket in android regarding this issue?

**Comment by JgomesAT** [comment]
I have the same problem, any schedule to correct this?

**Comment by kayces** [comment]
same problem ,  i fond remove  google_mobile_ads  is ok .  Please fix this, it's killing me

**Comment by MMoarales** [comment]
> same problem , i fond remove google_mobile_ads is ok . Please fix this, it's killing me

Try this, it works for me.
```dart
dependency_overrides:
  webview_flutter_android: 3.16.1
```

**Comment by ShafieaGabr** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

worked for me.. thanks

**Comment by najmulmyself** [comment]
had the same problem. this snippet fixed my code:

<meta-data
                android:name="android.webkit.WebView.EnableSafeBrowsing"
                android:value="true" />
            <meta-data
                android:name="flutterEmbedding"
                android:value="2" />

**Comment by harry-odinson-369** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

This also worked for me!

**Comment by JgomesAT** [comment]
HI,

this work dependency_overrides:
  webview_flutter_android: 3.16.1
  
  but any prevision for a final solution

**Comment by rkverma2022** [comment]
> In my case, to avoid the error, webview_flutter_android: 3.16.1 In addition to doing this in /myproject/android/app/build.gradle dependencies { implementation("com.google.android.gms:play-services-ads:23.1.0") } part of "com.google.android.gms:play-services-ads:23.0.0" I had to downgrade to .

worked for me

Also add permissions follow this doc: https://inappwebview.dev/docs/intro

**Comment by Manuito83** [comment]
#2182 removes references to SUPPRESS_ERROR_PAGE, which was [discontinued ](https://cs.android.com/androidx/platform/frameworks/support/+/071a5be0e7583c5ded85015ff94dc2ab7a7f0d62)in webkit's development.

**Comment by phamconganh** [comment]
While waiting for the next release, you can hotfix by forcing androidx.webkit:webkit:1.8.0. Add this to android/build.gradle
```
allprojects {
    /// TODO: remove. hotfix for flutter_inappwebview (using androidx.webkit:webkit:1.8.0)
    /// webview_flutter_android: ^3.16.2 androidx.webkit:webkit ^1.9.0 remove SUPPRESS_ERROR_PAGE
    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }
}
 ```

**Comment by nine-zet** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

worked for me. thx.

**Comment by frankenten13** [comment]
> While waiting for the next release, you can hotfix by forcing androidx.webkit:webkit:1.8.0. Add this to android/build.gradle
> 
> ```
> allprojects {
>     /// TODO: remove. hotfix for flutter_inappwebview (using androidx.webkit:webkit:1.8.0)
>     /// webview_flutter_android: ^3.16.2 androidx.webkit:webkit ^1.9.0 remove SUPPRESS_ERROR_PAGE
>     configurations.all {
>         resolutionStrategy {
>             force 'androidx.webkit:webkit:1.8.0'
>         }
>     }
> }
> ```

worked for me, thanks.

**Comment by segyoungpark** [comment]
any solutions mentioned here didnt work for me. any other solutions?

**Comment by esaiamuthan** [comment]
yes same issue for me also SUPPRESS_ERROR_PAGE

**Comment by segyoungpark** [comment]
> yes same issue for me also SUPPRESS_ERROR_PAGE

i solved the problem by doing this!
https://sseymorr.github.io/flutter/errors/suppress-error-page/ 

```gradle
allprojects {
    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }
}
```

```yaml
dependency_overrides:
  webview_flutter_android: 3.16.1
```

**Comment by foozaweb** [comment]
hot fixing by forcing androidx.webkit:webkit:1.8.0 worked for me.
Add this to android/build.gradle

`allprojects {
    
...
    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }

...
}`

**Comment by foozaweb** [comment]
hot fixing by forcing androidx.webkit:webkit:1.8.0 worked for me.
Add this to android/build.gradle


`allprojects {
    repositories {
        google()
        mavenCentral()
    }

    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }
}`

**Comment by esaiamuthan** [comment]
yes working for me, can you explain why this error came ?

**Comment by foozaweb** [comment]
> yes working for me, can you explain why this error came ?

The error message indicates that there is a problem with the configuration or implementation of the flutter_inappwebview package. The specific error message "Unknown feature SUPPRESS_ERROR_PAGE" suggests that the package is trying to use a feature that is not available or not properly configured.

**Comment by Manuito83** [comment]
> yes working for me, can you explain why this error came ?

I explained the reason [here](https://github.com/pichillilorenzo/flutter_inappwebview/pull/2182)

**Comment by Xoshbin** [comment]
`dependency_overrides:
  webview_flutter_android: 3.16.1`

This worked for me too.

**Comment by Xoshbin** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

This worked, Thank you

**Comment by tkreuder** [comment]
> hot fixing by forcing androidx.webkit:webkit:1.8.0 worked for me. Add this to android/build.gradle
> 
> allprojects {
> 
> ```
> configurations.all {
>     resolutionStrategy {
>         force 'androidx.webkit:webkit:1.8.0'
>     }
> }
> ```
> 
> }

Only this solution worked for me. 

This did not work: https://github.com/pichillilorenzo/flutter_inappwebview/pull/2182#issuecomment-2236442823 for me.

**Comment by Logochega** [comment]
Hello, resolved with the following method, watch the video to understand.
Olá resolvido com o seguinte método veja o video para entender.


em pub
dependency_overrides:
  webview_flutter_android: 3.16.1

em build.gradle
android/app/build.gradle dependencies { implementation("com.google.android.gms:play-services-ads:23.1.0") } parte de "com.google.android.gms:play-services-ads:23.0.0" tive que fazer o downgrade para .


[youtube](https://www.youtube.com/watch?v=oHZeY1yfwos)

**Comment by alitalaee** [comment]
dependency_overrides:
  webview_flutter_android: 3.16.1
  
  it is worked for me THANKS

**Comment by DontSerious** [comment]
> While

it is worked for me THANKS

**Comment by DontSerious** [comment]
> While waiting for the next release, you can hotfix by forcing androidx.webkit:webkit:1.8.0. Add this to android/build.gradle
> 
> ```
> allprojects {
>     /// TODO: remove. hotfix for flutter_inappwebview (using androidx.webkit:webkit:1.8.0)
>     /// webview_flutter_android: ^3.16.2 androidx.webkit:webkit ^1.9.0 remove SUPPRESS_ERROR_PAGE
>     configurations.all {
>         resolutionStrategy {
>             force 'androidx.webkit:webkit:1.8.0'
>         }
>     }
> }
> ```

it is worked for me THANKS

**Comment by ao305** [comment]
> > While waiting for the next release, you can hotfix by forcing androidx.webkit:webkit:1.8.0. Add this to android/build.gradle
> > ```
> > allprojects {
> >     /// TODO: remove. hotfix for flutter_inappwebview (using androidx.webkit:webkit:1.8.0)
> >     /// webview_flutter_android: ^3.16.2 androidx.webkit:webkit ^1.9.0 remove SUPPRESS_ERROR_PAGE
> >     configurations.all {
> >         resolutionStrategy {
> >             force 'androidx.webkit:webkit:1.8.0'
> >         }
> >     }
> > }
> > ```
> 
> it is worked for me THANKS

this solution , it is worked for me , thanks

**Comment by BaoTrung37** [comment]
> ```dart
> dependency_overrides:
>   webview_flutter_android: 3.16.1
> ```

It is worked for me.

**Comment by JHCalasans** [comment]
> dependency_overrides: webview_flutter_android: 3.16.1 worked for me thank you.

It worked for me.

**Comment by hamed-rezaee** [comment]
This issue is fixed in the version [1.6.0](https://pub.dev/packages/flutter_inappwebview/changelog#610).

```
Change log:

Added initial Windows support
Added InAppWebView widget MacOS support
Added privacy manifest for MacOS
Migrated web support to package:web.
Updated minimum supported SDK version to Flutter 3.24/Dart 3.5.
Updated androidx.webkit:webkit:1.8.0 to androidx.webkit:webkit:1.12.0
Updated androidx.browser:browser:1.6.0 to androidx.browser:browser:1.8.0
Fixed "[MACOS] launching InAppBrowser with 'hidden: true' calls onExit immediately" [#1939](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1939)
Fixed XCode 16 build
Removed unsupported WebViewFeature.SUPPRESS_ERROR_PAGE
Merged "Add privacy manifest for iOS" [#2029](https://github.com/pichillilorenzo/flutter_inappwebview/pull/2029) (thanks to [ueman](https://github.com/ueman))
Merged "Remove references to deprecated v1 Android embedding" [#2176](https://github.com/pichillilorenzo/flutter_inappwebview/pull/2176) (thanks to [gmackall](https://github.com/gmackall))
```

**Comment by mkhtradm01** [comment]
After I updated `flutter_inappwebview` to version `6.1.5`, this is no longer an issue to me. Below is the output of my `flutter doctor -v` command:

`
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale xx-XX)
    • Flutter version 3.24.3 on channel stable at /Users/username/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/username/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • My iPhone 14 Pro (mobile)  • xxx-xxxxxx • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!`
