### ISSUE TITLE
[web] WebView in production: Null check operator used on a null value

### ISSUE THREAD

**Issue by kevinpthorne** [pichillilorenzo/flutter_inappwebview#2192]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |   3.19.3            |
| Plugin version        |    6.0.0           |
| Android version       |   n/a            |
| iOS version           |   n/a            |
| macOS version         |  (host) 14.4.1             |
| Xcode version         |   n/a            |
| Google Chrome version |    124.0.6367.208 (arm64)           |

Device information: n/a 

## Description

**Expected behavior:** `InAppWebView` renders the iframe as it does in Flutter dev mode

**Current behavior:** No iframe rendered. `Null check operator used on a null value` with obfuscated stacktrace

## Steps to reproduce

1. Make a widget with
```dart
  @override
  Widget build(BuildContext context) {
    return InAppWebView(
      initialData: InAppWebViewInitialData(data: "hello world"),
    );
  }
```
2. Run `flutter run -d chrome` -- verify it is functioning
3. Run `flutter build web`
4. Run some HTTP server in the `build/web` directory (e.g. `python3 -m http.server --directory build/web 8002`)
5. Visit the different http server, observe error

## Images   
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/8848627/23609f4b-6e9b-46ff-89c1-88f64a8300d8)

## Stacktrace/Logcat   
```txt
Null check operator used on a null value
main.dart.js:28785     at Object.aTi (http://localhost:8002/main.dart.js:25467:19)
main.dart.js:28785     at Object.aS7 (http://localhost:8002/main.dart.js:25461:26)
main.dart.js:28785     at TG.I (http://localhost:8002/main.dart.js:49797:10)
main.dart.js:28785     at Si.bi (http://localhost:8002/main.dart.js:75771:18)
main.dart.js:28785     at Si.kN (http://localhost:8002/main.dart.js:75747:9)
main.dart.js:28785     at Si.BR (http://localhost:8002/main.dart.js:75699:10)
main.dart.js:28785     at Si.YS (http://localhost:8002/main.dart.js:75700:18)
main.dart.js:28785     at Si.Ey (http://localhost:8002/main.dart.js:75745:11)
main.dart.js:28785     at Si.fc (http://localhost:8002/main.dart.js:75744:6)
main.dart.js:28785     at rd.vv (http://localhost:8002/main.dart.js:75612:3)
```

**Comment by kevinpthorne** [comment]
Any tips on decoding this stacktrace? That's where I am stuck currently

**Comment by kevinpthorne** [comment]
Looks like this was a case of my browser or dart compiler caching things -- now I'm just working around flutter/flutter#86833' since I am serving HTML and CSS assets...on the web inappwebview (I know its weird)

Tips for posterity:
- If you're using something like `python3 -m http.server` to serve the compiled web folder, be sure to cycle ports as you troubleshoot
- `flutter clean` is always a good nuke option
- Don't use the workaround here https://github.com/flutter/flutter/issues/86833#issuecomment-1658018656. For some reason this messed with everything.
- Ensure the flutter source map json is getting generated using debug flags on `flutter build` (i.e. https://github.com/flutter/flutter/issues/101888#issuecomment-1099488815)
