### ISSUE TITLE
`No host specified in URI file:///` and `No virtual method isEngagementSignalsApiAvailable` Error on opening a webpage

### ISSUE THREAD

**Issue by lokesh-univest** [pichillilorenzo/flutter_inappwebview#2203]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |  3.16.7  |
| Plugin version        |  ^6.0.0   |
| Android version       |   All   |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 
Comes in all android devices

## Description
I have got below 2 Errors in this plugin and it's increase the crash rates on of my application.

Error 1:

This is regarding that in your plugin may be you are using any catch image in wrong way so when i open any page in web it's shows me NetworkImage ```Invalid argument(s): No host specified in URI file:///``` issue.

Error 2:

This Error comes when I am open a page using ``` MyChromeSafariBrowser``` function.

code:

```
MyChromeSafariBrowser().open(
                          url: WebUri(url),
                          settings: ChromeSafariBrowserSettings(
                            shareState: CustomTabsShareState.SHARE_STATE_OFF,
                            barCollapsingEnabled: true,
                            packageName: 'com.android.chrome'
                          ),
                        );
```

## Stacktrace/Logcat   

Error 1:

```
======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2752:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2628:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:104:59)
#3      NetworkImage.loadImage (package:flutter/src/painting/_network_image_io.dart:66:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:520:39)
#5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:377:22)
#6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:517:81)
#7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:104:19)
#8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:366:9)
#9      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:479:24)
#10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#11     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:476:9)
#12     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:363:5)
#13     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1110:16)
#14     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1060:5)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5631:13)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#23     _invoke (dart:ui/hooks.dart:312:13)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#25     _drawFrame (dart:ui/hooks.dart:283:31)
Image provider: NetworkImage("", scale: 1.0)
Image key: NetworkImage("", scale: 1.0)
====================================================================================================
```

Error 2:

```
D/CustomTabsActivity(18347): Custom Tabs Engagement Signals API not supported
D/CustomTabsActivity(18347): java.lang.NoSuchMethodError: No virtual method isEngagementSignalsApiAvailable(Landroid/os/Bundle;)Z in class Landroidx/browser/customtabs/CustomTabsSession; or its super classes (declaration of 'androidx.browser.customtabs.CustomTabsSession' appears in /data/app/~~tATxK04CBNS15AQv44F9bQ==/com.univest.capp.uat-mm1A3Yzxpht4KvcdrJV3Vw==/base.apk)
D/CustomTabsActivity(18347): 	at com.pichillilorenzo.flutter_inappwebview_android.chrome_custom_tabs.ChromeCustomTabsActivity.customTabsConnected(ChromeCustomTabsActivity.java:224)
D/CustomTabsActivity(18347): 	at com.pichillilorenzo.flutter_inappwebview_android.chrome_custom_tabs.ChromeCustomTabsActivity$1.onCustomTabsConnected(ChromeCustomTabsActivity.java:117)
D/CustomTabsActivity(18347): 	at com.pichillilorenzo.flutter_inappwebview_android.chrome_custom_tabs.CustomTabActivityHelper.onServiceConnected(CustomTabActivityHelper.java:152)
D/CustomTabsActivity(18347): 	at com.pichillilorenzo.flutter_inappwebview_android.chrome_custom_tabs.ServiceConnection.onCustomTabsServiceConnected(ServiceConnection.java:24)
D/CustomTabsActivity(18347): 	at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
D/CustomTabsActivity(18347): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2198)
D/CustomTabsActivity(18347): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2231)
D/CustomTabsActivity(18347): 	at android.os.Handler.handleCallback(Handler.java:958)
D/CustomTabsActivity(18347): 	at android.os.Handler.dispatchMessage(Handler.java:99)
D/CustomTabsActivity(18347): 	at android.os.Looper.loopOnce(Looper.java:205)
D/CustomTabsActivity(18347): 	at android.os.Looper.loop(Looper.java:294)
D/CustomTabsActivity(18347): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
D/CustomTabsActivity(18347): 	at java.lang.reflect.Method.invoke(Native Method)
D/CustomTabsActivity(18347): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
D/CustomTabsActivity(18347): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[AndroidChromeSafariBrowser] (android) AndroidChromeSafariBrowser ID 11332525311222022812269671639021252245188122 calling "onServiceConnected" using {}
D/SessionLifecycleClient(18347): Sending lifecycle 2 to service

```

**Comment by lokesh-univest** [comment]
I have search the issue but i am not get any proper solution.
