### ISSUE TITLE
[Android] Fatal Exception: java.lang.IllegalArgumentException: Given view not a child InAppWebView.onFloatingActionGlobalLayout

### ISSUE THREAD

**Issue by ho-doan-ominext** [pichillilorenzo/flutter_inappwebview#2207]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.19.0        |
| Plugin version        |       ^6.0.0        |
| Android version       |        Android 10       |

Device information: 
- Brand:Sony
- Model:Xperia XZ3
- RAM free: 332.39 MB
- Operating System Version: Android 10

## Description

1. This error is in the firebase crashlytics, I tried to reproduce the bug but couldn't

## Stacktrace/Logcat <detail>
Fatal Exception: java.lang.IllegalArgumentException: Given view not a child of com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView{f843dc VFEDHVCL. ......ID 0,0-1440,2257}
       at android.view.ViewGroup.updateViewLayout(ViewGroup.java:4944)
       at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.onFloatingActionGlobalLayout(:64)
       at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView$16.onReceiveValue(:64)
       at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView$16.onReceiveValue(:2)
       at WV.vb.onResult(chromium-TrichromeWebViewGoogle6432.aab-stable-647807133:3)
       at org.chromium.base.Callback.a(chromium-TrichromeWebViewGoogle6432.aab-stable-647807133:1)
       at WV.ub.run(chromium-TrichromeWebViewGoogle6432.aab-stable-647807133:5)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:359)
       at android.app.ActivityThread.main(ActivityThread.java:7418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
</detail>

**Comment by ho-doan-ominext** [comment]
sample code 
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Stack(
        children: [
          Column(
            children: [
              Expanded(
                child: InAppWebView(
                  onGeolocationPermissionsShowPrompt:
                      (controller, origin) async {
                    final geoLocationPermission =
                        GeolocationPermissionShowPromptResponse(
                      origin: origin,
                      allow: true,
                      retain: true,
                    );
                    return geoLocationPermission;
                  },
                  key: _inAppWebViewKey,
                  initialUrlRequest: URLRequest(
                    url: WebUri.uri(Uri.parse(widget.url)),
                    headers: {'header': 'Header'},
                  ),
                  initialUserScripts: UnmodifiableListView<UserScript>([]),
                  initialSettings: InAppWebViewSettings(
                    userAgent: '...agent',
                    useShouldOverrideUrlLoading: true,
                    transparentBackground: true,
                    useHybridComposition: false,
                    layoutAlgorithm: LayoutAlgorithm.TEXT_AUTOSIZING,
                  ),
                  onPermissionRequest: (controller, permissionRequest) async {
                    return PermissionResponse(
                      resources: permissionRequest.resources,
                      action: PermissionResponseAction.GRANT,
                    );
                  },
                  shouldOverrideUrlLoading:
                      (controller, navigationAction) async {
                    // ...
                    return NavigationActionPolicy.ALLOW;
                  },
                  onReceivedHttpAuthRequest: (
                    controller,
                    authenticationChallenge,
                  ) async {
                    log('BaseInAppWebView'
                        '#onReceivedHttpAuthRequest');
                    return null;
                  },
                  onCreateWindow: (controller, createWindowAction) async {
                    return null;
                  },
                ),
              ),
              BottomBar(),
            ],
          ),
        ],
      ),
    );
  }
```
