### ISSUE TITLE
Crash on IOS opened webview command

### ISSUE THREAD

**Issue by GabriAlbarosa** [pichillilorenzo/flutter_inappwebview#2232]
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
Dart 3.4.3 • DevTools 2.34.3
| Plugin version        6.0.0
Testing Device: Iphone 15 Pro max
| macOS version          14.5
| Xcode version          15.3

## Description

**Expected behavior:** 
We expecting same behavior in both os system. On android we can complete Transak Flow, in ios we keep have crashing issues related to the library.

This is the class related to the issue.
[buy_aft_webview.dart.zip](https://github.com/user-attachments/files/16335155/buy_aft_webview.dart.zip)
We try to breakpoint flutter code but we re stuck on the point below.

## Stacktrace/Logcat 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < com.pichillilorenzo/flutter_inappwebview >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
If you are not the author of the PlatformView, make sure to call `GeneratedPluginRegistrant.register`., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:918:36)
<asynchro<…>

**Comment by tungthanh1497** [comment]
Following the official docs here: https://inappwebview.dev/docs/intro/#setup-ios

I added the following to **ios/Runner/Info.plist**:

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
<key>NSAllowsLocalNetworking</key>
<true/>
<key>NSAllowsArbitraryLoadsInWebContent</key>
<true/>
```

After making those changes and rebuilding the app, the crash no longer occurred and the WebView worked as expected.
