### ISSUE TITLE
6.1.1 Crash: java.lang.IncompatibleClassChangeError: Found class androidx.webkit.ScriptHandler, but interface was expected (declaration of 'androidx.webkit.ScriptHandler' appears in ...

### ISSUE THREAD

**Issue by mflutter3** [pichillilorenzo/flutter_inappwebview#2302]
Flutter: 3.24.3
PC: macOS 14
ENV: Android 14

There is a crash when close the webview in android. Log:

```log
E/AndroidRuntime(23273): FATAL EXCEPTION: main
E/AndroidRuntime(23273): Process: com.jdl.core_kit.example, PID: 23273
E/AndroidRuntime(23273): java.lang.IncompatibleClassChangeError: Found class androidx.webkit.ScriptHandler, but interface was expected (declaration of 'androidx.webkit.ScriptHandler' appears in /data/app/~~gNZW6qkHQ8QeGyVKVp6WeQ==/com.jdl.core_kit.example-3QxLBo7agc2NYTGnx8QoJA==/base.apk)
E/AndroidRuntime(23273): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.removeAllUserOnlyScripts(UserContentController.java:244)
E/AndroidRuntime(23273): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.dispose(UserContentController.java:469)
E/AndroidRuntime(23273): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.dispose(InAppWebView.java:2051)
E/AndroidRuntime(23273): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.dispose(FlutterWebView.java:154)
E/AndroidRuntime(23273): 	at io.flutter.plugin.platform.PlatformViewsController$1.dispose(PlatformViewsController.java:254)
E/AndroidRuntime(23273): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:150)
E/AndroidRuntime(23273): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:58)
E/AndroidRuntime(23273): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(23273): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(23273): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(23273): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(23273): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(23273): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23273): 	at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime(23273): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(23273): 	at android.app.ActivityThread.main(ActivityThread.java:8839)
E/AndroidRuntime(23273): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23273): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(23273): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/Process (23273): Sending signal. PID: 23273 SIG: 9
```

**Comment by mflutter3** [comment]
Sorry, the version of webkit was forced to be 1.8.0, it is ok when removed this config.
```
configurations.configureEach {
    resolutionStrategy {
        force 'androidx.webkit:webkit:1.8.0'
    }
}
```
