### ISSUE TITLE
android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter

### ISSUE THREAD

**Issue by grove86dipesh** [pichillilorenzo/flutter_inappwebview#2397]
This issue was capture on The Google Firebase Crashlytics dashboard. I have attached all details with this message.

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter, null, java.lang.ClassCastException: android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter
	at Ye0.convertSettings(chromium-TrichromeWebViewGoogle.apk-stable-443021036:2)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:423)
	at Zc.invoke(chromium-TrichromeWebViewGoogle.apk-stable-443021036:5)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1008)
	at $Proxy3.convertSettings(Unknown Source)
	at androidx.webkit.internal.WebkitToCompatConverter.convertSettings(SourceFile:5)
	at androidx.webkit.WebSettingsCompat.getAdapter(SourceFile:5)
	at androidx.webkit.WebSettingsCompat.setForceDarkStrategy(SourceFile:9)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(SourceFile:81)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(SourceFile:214)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(SourceFile:102)
	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(SourceFile:41)
	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(SourceFile:16)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(SourceFile:123)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(SourceFile:176)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:18)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(SourceFile:19)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(SourceFile:42)
	at io.flutter.embedding.engine.dart.DartMessenger.a(SourceFile:1)
	at io.flutter.embedding.engine.dart.a.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(<truncated: 385 chars>
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at ExpensiveAndroidViewController._sendCreateMessage(platform_views.dart:1104)
       at AndroidViewController.create(platform_views.dart:827)
```
</details>

### Flutter version

v3.24.3

### Operating System, Device-specific and/or Tool

Device: OnePlus
Operating system: Android 11 

### Plugin version

v6.1.5

### Additional information

![Screenshot 2024-11-05 at 12 27 01 PM](https://github.com/user-attachments/assets/e7721620-c1dc-47ab-9e2e-77161191efb7)
![Screenshot 2024-11-05 at 12 27 12 PM](https://github.com/user-attachments/assets/b0fbc073-7d25-4fbc-9b46-fd25f2e40278)
![Screenshot 2024-11-05 at 12 32 23 PM](https://github.com/user-attachments/assets/2aafddf2-bc9a-4446-a342-9713b895e2f9)

**Comment by pichillilorenzo** [comment]
I found the same issue, it should be fixed with the next version 6.2.0

**Comment by grove86dipesh** [comment]
When can we expect this version 6.2.0?

**Comment by pichillilorenzo** [comment]
Today I should release the new `6.2.0-beta.1` version

**Comment by Den-creator** [comment]
The same issue. @pichillilorenzo  when beta will become stable ?
