### ISSUE TITLE
[WEB] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callHandler')

### ISSUE THREAD

**Issue by zakharpodyakov** [pichillilorenzo/flutter_inappwebview#2435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I call the window.flutter_inappwebview.callHandler method, I get the error Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callHandler')

### Expected Behavior

The method is called successfully and I get a message in flutter

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart

class _PaymentState extends State<PaymentPage> {
  InAppWebViewController? _webViewController;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) => InAppWebView(
        onWebViewCreated: (controller) {
          _webViewController = controller;
          _webViewController?.addJavaScriptHandler(
            handlerName: 'flutterHandler',
            callback: (args) {
              print(args);
            },
          );
        },
        initialSettings: InAppWebViewSettings(
          javaScriptEnabled: true,
          useShouldOverrideUrlLoading: true,
          useOnLoadResource: true,
          cacheEnabled: true,
        ),
        initialData: InAppWebViewInitialData(
          data: '''
                <script src="https://widget.cloudpayments.ru/bundles/paymentblocks.js"></script>
                <div id="element" style="margin: 100 auto; width: 500px; "></div>
                <script>

                    var domElement = document.getElementById('element');
                    
                    var element = new cp.PaymentBlocks({
                        publicId: 'pk_..',
                        amount: ${widget.amount},
                        currency: '${widget.currency}',
                        accountId: '${widget.accountId}',
                        email: ${widget.email},
                        debug: ${widget.debug},
                    });
                    
                    element.mount(domElement);
                    
                    element.on("destroy", () => {
                        window.flutter_inappwebview.callHandler('flutterHandler', 'Destroy');
                        console.log("destroy");
                    });
                    
                    element.on("success", (result) => {
                        window.flutter_inappwebview.callHandler('flutterHandler', 'Success');
                        console.log("success", result);
                    });
                    
                    element.on("fail", (result) => {
                        window.flutter_inappwebview.callHandler('flutterHandler', 'Fail');
                        console.log("fail", result);
                    });
                </script>
          ''',
          encoding: 'utf-8',
        ),
      );
}
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callHandler')
    at data:text/html,%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cscript%20src%3D%22https%3A%2F%2Fwidget.cloudpayments.ru%2Fbundles%2Fpaymentblocks.js%22%3E%3C%2Fscript%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20id%3D%22element%22%20style%3D%22margin%3A%20100%20auto%3B%20width%3A%20500px%3B%20%22%3E%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cscript%3E%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20domElement%20%3D%20document.getElementById('element')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20element%20%3D%20new%20cp.PaymentBlocks(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20publicId%3A%20'pk_a2736c042b234dfa6810ad6064ece'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20amount%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20currency%3A%20'RUB'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20accountId%3A%20'%2B79088189006'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20email%3A%20null%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20debug%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.mount(domElement)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.on(%22destroy%22%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20window.flutter_inappwebview.callHandler('flutterHandler'%2C%20'Destroy')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22destroy%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.on(%22success%22%2C%20(result)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20window.flutter_inappwebview.callHandler('flutterHandler'%2C%20'Success')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22success%22%2C%20result)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.on(%22fail%22%2C%20(result)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20window.flutter_inappwebview.callHandler('flutterHandler'%2C%20'Fail')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22fail%22%2C%20result)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fscript%3E%0A%20%20%20%20%20%20%20%20%20%20:24:53
    at e.<anonymous> (https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:122913)
    at Array.forEach (<anonymous>)
    at e.value (https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:122861)
    at e.<anonymous> (https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:122541)
    at t.<anonymous> (https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:113459)
    at https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:82280
    at new Promise (<anonymous>)
    at https://widget.cloudpayments.ru/bundles/paymentblocks.js:1:8223
```
</details>

### Flutter version

3.24.2

### Operating System, Device-specific and/or Tool

Web

### Plugin version

^6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
JavaScript channels are not supported currently on Web platform.
Check the docs for each event or method before using it.

**Comment by zakharpodyakov** [comment]
@pichillilorenzo how can I implement this logic in web?
