### ISSUE TITLE
NPE when window.prompt

### ISSUE THREAD

**Issue by AlexVincent525** [pichillilorenzo/flutter_inappwebview#261]
## Environment

**Flutter version:** 1.12.13+hotfix.5
**Plugin version:**  3.0.0 9c7ac0d
**Android version:**  Android 10 
**Device information:**  OnePlus 6T

## Description

**Expected behavior:** No NPE or crash.

**Current behavior:** App crashed when prompt was shown.

## Steps to reproduce

1. Running apps under debug environment.
2. Open a web page including prompt function.
3. Call `window.prompt`.
4. App crashed.

## Logcat
```
2020-01-16 15:06:38.623 4560-4560/com.alexv525.someapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.alexv525.someapp, PID: 4560
    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1638)
        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1889)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1196)
        at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InputAwareWebView$1.run(InputAwareWebView.java:193)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by AlexVincent525** [comment]
As I investigate, this is related to flutter/flutter#38375

**Comment by AlexVincent525** [comment]
Please test this with https://www.w3school.com.cn/tiy/t.asp?f=hdom_prompt
