### ISSUE TITLE
App crashes after closing by pressing the BACK button (java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.)

### ISSUE THREAD

**Issue by furiousdazzewizard** [pichillilorenzo/flutter_inappwebview#281]
## Environment

**Flutter version: v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17763.973]
**Plugin version: Flutter plugin version 43.0.1, on Android Studio 3.5
                               Dart plugin version 191.8593
                               Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
**Android version: Android 9 (API 28)
**iOS version: N/A
**Xcode version: N/A
**Device information: SM J400M • 42006eb568b2a543 • android-arm • Android 9 (API 28)

## Description

When exiting the APP by pressing the back button it crashes with the following exception:

2020-02-11 13:07:55.141 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: py.com.megahard.megahard_medidoronline_v1_1, PID: 26780
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-02-11 13:07:55.180 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/Process: Sending signal. PID: 26780 SIG: 9

**Expected behavior: to exit without exception, without crash.

**Current behavior: complete log follows:

2020-02-11 13:07:36.925 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: ViewPostIme pointer 0
2020-02-11 13:07:36.988 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: ViewPostIme pointer 1
2020-02-11 13:07:37.098 26780-27010/py.com.megahard.megahard_medidoronline_v1_1 I/flutter: usuario registrado.. ID: 1
2020-02-11 13:07:37.527 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/Dialog: mIsSamsungBasicInteraction = false
2020-02-11 13:07:37.527 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2020-02-11 13:07:37.732 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ConnectivityManager: requestNetwork; CallingUid : 10274, CallingPid : 26780
2020-02-11 13:07:37.737 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ConnectivityManager: requestNetwork; CallingUid : 10274, CallingPid : 26780
2020-02-11 13:07:37.791 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
2020-02-11 13:07:37.792 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
2020-02-11 13:07:37.793 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.793 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.794 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.794 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.794 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.794 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2020-02-11 13:07:37.830 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden field Landroid/view/View;->mContext:Landroid/content/Context; (light greylist, reflection)
2020-02-11 13:07:37.896 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-02-11 13:07:37.908 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
2020-02-11 13:07:37.909 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
2020-02-11 13:07:37.909 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
2020-02-11 13:07:37.967 26780-27060/py.com.megahard.megahard_medidoronline_v1_1 W/idoronline_v1_: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
2020-02-11 13:07:38.006 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/DecorView: createDecorCaptionView >> DecorView@49f9e48[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
2020-02-11 13:07:38.015 26780-27060/py.com.megahard.megahard_medidoronline_v1_1 W/cr_media: Requires BLUETOOTH permission
2020-02-11 13:07:38.064 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel constructed: fd=173
2020-02-11 13:07:38.065 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@cb9ee60[MainActivity]: setView = DecorView@49f9e48[MainActivity] TM=true MM=false
2020-02-11 13:07:38.163 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/ac4
2020-02-11 13:07:38.169 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/x-ima
2020-02-11 13:07:38.190 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/eac3-joc
2020-02-11 13:07:38.197 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 V/InputMethodManager: Not IME target window, ignoring
2020-02-11 13:07:38.208 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/mpeg-L1
2020-02-11 13:07:38.210 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/mpeg-L2
2020-02-11 13:07:38.226 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/AudioCapabilities: Unsupported mime audio/x-ms-wma
2020-02-11 13:07:38.304 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2020-02-11 13:07:38.314 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@cb9ee60[MainActivity]: Relayout returned: old=[0,0][720,555] new=[0,0][720,555] result=0x7 surface={true 3249930240} changed=true
2020-02-11 13:07:38.316 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x555]-format:1
2020-02-11 13:07:38.316 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/OpenGLRenderer: eglCreateWindowSurface = 0xc1a34240, 0xc1b60008
2020-02-11 13:07:38.326 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unsupported mime video/mp43
2020-02-11 13:07:38.347 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
2020-02-11 13:07:38.347 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
2020-02-11 13:07:38.347 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
2020-02-11 13:07:38.354 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unsupported mime video/wvc1
2020-02-11 13:07:38.371 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unsupported mime video/wvc1
2020-02-11 13:07:38.402 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
2020-02-11 13:07:38.409 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
2020-02-11 13:07:38.457 26780-27175/py.com.megahard.megahard_medidoronline_v1_1 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2020-02-11 13:07:38.483 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: HSIFW - flag : 0 Pid : 26780
2020-02-11 13:07:38.497 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@cb9ee60[MainActivity]: MSG_RESIZED: frame=[0,0][720,555] ci=[0,0][0,0] vi=[0,0][0,0] or=2
2020-02-11 13:07:38.713 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: MSG_RESIZED: frame=[0,0][720,1280] ci=[0,42][0,0] vi=[0,42][0,0] or=1
2020-02-11 13:07:38.745 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={true 3391635456} changed=false
2020-02-11 13:07:38.849 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: HSIFW - flag : 0 Pid : 26780
2020-02-11 13:07:38.849 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/InputMethodManager: hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :io.flutter.embedding.android.FlutterView{6d64769 VFE...... .F....I. 0,0-720,1280}
2020-02-11 13:07:38.974 26780-26824/py.com.megahard.megahard_medidoronline_v1_1 E/BufferQueueProducer: [SurfaceTexture-0-26780-0] disconnect: not connected (req=1)
2020-02-11 13:07:38.982 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/Dialog: mIsSamsungBasicInteraction = false
2020-02-11 13:07:38.982 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2020-02-11 13:07:39.056 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/DecorView: createDecorCaptionView >> DecorView@ac6d5e4[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
2020-02-11 13:07:39.109 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel constructed: fd=158
2020-02-11 13:07:39.110 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@c25a34e[MainActivity]: setView = DecorView@ac6d5e4[MainActivity] TM=true MM=false
2020-02-11 13:07:39.125 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 V/InputMethodManager: Not IME target window, ignoring
2020-02-11 13:07:39.182 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@c25a34e[MainActivity]: Relayout returned: old=[0,0][720,1140] new=[0,0][720,1140] result=0x7 surface={true 3261437952} changed=true
2020-02-11 13:07:39.189 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1140]-format:1
2020-02-11 13:07:39.189 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/OpenGLRenderer: eglCreateWindowSurface = 0xe4436600, 0xc2659808
2020-02-11 13:07:39.202 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 W/libEGL: EGLNativeWindowType 0xc1b60008 disconnect failed
2020-02-11 13:07:39.202 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/OpenGLRenderer: eglDestroySurface = 0xc1a34240, 0xc1b60000
2020-02-11 13:07:39.202 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@cb9ee60[MainActivity]: dispatchDetachedFromWindow
2020-02-11 13:07:39.211 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel destroyed: fd=173
2020-02-11 13:07:39.282 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@c25a34e[MainActivity]: MSG_RESIZED_REPORT: frame=[0,0][720,1140] ci=[0,0][0,0] vi=[0,0][0,0] or=1
2020-02-11 13:07:41.205 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: prepareNavigationBarInfo() DecorView@9f8a6a[MainActivity]
2020-02-11 13:07:41.205 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: getNavigationBarColor() -855310
2020-02-11 13:07:41.205 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 V/InputMethodManager: Starting input: tba=py.com.megahard.megahard_medidoronline_v1_1 ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-02-11 13:07:41.205 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: startInputInner - Id : 0
2020-02-11 13:07:41.209 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-02-11 13:07:41.214 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel constructed: fd=189
2020-02-11 13:07:41.214 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel destroyed: fd=139
2020-02-11 13:07:53.967 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: ViewPostIme key 0
2020-02-11 13:07:53.994 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: ViewPostIme key 1
2020-02-11 13:07:54.157 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2020-02-11 13:07:54.157 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: prepareNavigationBarInfo() DecorView@9f8a6a[MainActivity]
2020-02-11 13:07:54.158 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: getNavigationBarColor() -855310
2020-02-11 13:07:54.259 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel destroyed: fd=189
2020-02-11 13:07:54.602 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/SurfaceView: onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{e64e33c V.E...... ......I. 0,0-720,1280} of ViewRootImpl@d466237[MainActivity]
2020-02-11 13:07:54.604 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/SurfaceView: show() Surface(name=SurfaceView - py.com.megahard.megahard_medidoronline_v1_1/py.com.megahard.megahard_medidoronline_v1_1.MainActivity@e64e33c@0[26780])/@0xa9938c5 io.flutter.embedding.android.FlutterSurfaceView{e64e33c V.E...... ......I. 0,0-720,1280}
2020-02-11 13:07:54.606 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/SurfaceView: surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{e64e33c V.E...... ......I. 0,0-720,1280}
2020-02-11 13:07:54.618 26780-27012/py.com.megahard.megahard_medidoronline_v1_1 W/libEGL: EGLNativeWindowType 0xca284808 disconnect failed
2020-02-11 13:07:54.620 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/SurfaceView: destroy() Surface(name=SurfaceView - py.com.megahard.megahard_medidoronline_v1_1/py.com.megahard.megahard_medidoronline_v1_1.MainActivity@e64e33c@0[26780])/@0xa9938c5 io.flutter.embedding.android.FlutterSurfaceView{e64e33c V.E...... ......I. 0,0-720,1280}
2020-02-11 13:07:54.623 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 W/libEGL: EGLNativeWindowType 0xca284008 disconnect failed
2020-02-11 13:07:54.624 26780-27085/py.com.megahard.megahard_medidoronline_v1_1 D/OpenGLRenderer: eglDestroySurface = 0xe334ff80, 0xca284000
2020-02-11 13:07:54.655 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={false 0} changed=true
2020-02-11 13:07:54.662 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: stopped(true) old=false
2020-02-11 13:07:54.663 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/SurfaceView: windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{e64e33c V.E...... ......I. 0,0-720,1280} of ViewRootImpl@d466237[MainActivity]
2020-02-11 13:07:54.665 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/FlutterView: Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@3395509
2020-02-11 13:07:54.668 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 E/InputMethodManager: prepareNavigationBarInfo() rootView is null
2020-02-11 13:07:54.668 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 V/InputMethodManager: Starting input: tba=py.com.megahard.megahard_medidoronline_v1_1 ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-02-11 13:07:54.669 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputMethodManager: startInputInner - Id : 0
2020-02-11 13:07:54.669 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-02-11 13:07:54.699 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/FlutterActivityAndFragmentDelegate: Detaching FlutterEngine from the Activity that owns this Fragment.
2020-02-11 13:07:54.704 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/FlutterEngine: Destroying.
2020-02-11 13:07:54.704 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/FlutterEnginePluginRegistry: Destroying.
2020-02-11 13:07:54.777 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/ViewRootImpl@d466237[MainActivity]: dispatchDetachedFromWindow
2020-02-11 13:07:54.788 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/InputTransport: Input channel destroyed: fd=132
2020-02-11 13:07:55.138 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 D/AndroidRuntime: Shutting down VM
2020-02-11 13:07:55.141 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: py.com.megahard.megahard_medidoronline_v1_1, PID: 26780
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-02-11 13:07:55.180 26780-26780/py.com.megahard.megahard_medidoronline_v1_1 I/Process: Sending signal. PID: 26780 SIG: 9

## Steps to reproduce

1. Build a project with the webview to show a give url, for example:
.
.
.
@override
  Widget build(BuildContext context) {
    data = ModalRoute.of(context).settings.arguments;
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Medidor Online, v1.1 - Panel de\nVisualización',
          style: GoogleFonts.indieFlower(),
        ),
        elevation: 15.0,
      ),
      body: InAppWebView(
        initialUrl: data['url'],
        initialHeaders: {},
        initialOptions: InAppWebViewWidgetOptions(
          crossPlatform: InAppWebViewOptions(
            preferredContentMode: InAppWebViewUserPreferredContentMode.DESKTOP,
          ),
          android: AndroidInAppWebViewOptions(
            useWideViewPort: true,
            loadWithOverviewMode: true,
            supportZoom: true,
            builtInZoomControls: true,
            displayZoomControls: true,
          ),
        ),
        onWebViewCreated: (InAppWebViewController controller) {
          webView = controller;
        },
        ),
    );
  }

2. then run the app from the IDE
3. you will get the logs with the error in the logcat window.

**Comment by mrme2014** [comment]
I also have the problem,   how do you  fix it?

**Comment by furiousdazzewizard** [comment]
Hi @mrme2014 ... truth to be told, I didn't get any response from the developer. So, the only workaround I managed to implement was to install and use the **move_to_background** flutter plugin from pub.dev (you can download [here](https://pub.dev/packages/move_to_background)). With that plugin you can catch the "back button" pressed event by means of a WillPopScope widget and do a safe movement to background of your app with something like this:

WillPopScope(
  child: MaterialApp(...),
  onWillPop: () async {
    MoveToBackground.moveTaskToBack();
    return false;
  },
);

The above works fine, no more crashing. Hope it helps you too.

BR/
