### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by Iampato** [pichillilorenzo/flutter_inappwebview#301]
## Environment

**Flutter version:** 
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
**Plugin version:**    
 v 2.1.0+1
**Android version:**    
Android 8.1.0 Go edition
**Device information:**    
Huawei DRA LX5

## Description
On loading it crashes

**Expected behavior:** 
Load the app
**Current behavior:** 
Crashes

## Steps to reproduce

1. Clone the plugin official repo
2. cd into the example dir 
3. flutter run

## Stacktrace/Logcat   
```
 Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/pato/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/pato/Android/Sdk/platform-tools/adb start-server
[   +4 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +31 ms] Using gradle from /home/pato/IdeaProjects/legacyapp/android/gradlew.
[   +1 ms] /home/pato/IdeaProjects/legacyapp/android/gradlew mode: 33277 rwxrwxr-x.
[  +17 ms] executing: [/home/pato/IdeaProjects/legacyapp/android/] /home/pato/IdeaProjects/legacyapp/android/gradlew -Pverbose=true
-Ptarget=/home/pato/IdeaProjects/legacyapp/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm assembleDebug
[+10714 ms] Starting a Gradle Daemon, 1 busy and 1 stopped Daemons could not be reused, use --status for details

[+64755 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +93 ms] executing: [/home/pato/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [ +241 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +2 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] [        ] executing: [/home/pato/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +196 ms] [ +206 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.14.6-0-gfabeb2a
[        ] [  +12 ms] executing: [/home/pato/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [/home/pato/development/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[  +98 ms] [ +119 ms] executing: [/home/pato/development/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +34 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +98 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +198 ms] [ +282 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +194 ms] [ +106 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[+1699 ms] [+1783 ms] Skipping target: kernel_snapshot
[  +99 ms] [  +77 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[+2199 ms] [+2135 ms] debug_android_application: Complete
[        ] [  +56 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 4,542ms.
[ +699 ms] > Task :app:packLibsflutterBuildDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[ +799 ms] > Task :app:checkDebugManifest
[ +299 ms] > Task :app:generateDebugBuildConfig
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[ +299 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[ +299 ms] > Task :app:mergeDebugShaders
[ +199 ms] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[        ] > Task :app:mergeDebugAssets
[ +499 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug
[ +399 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[+5700 ms] > Task :app:mergeDebugResources
[ +100 ms] > Task :app:createDebugCompatibleScreenManifests
[+1499 ms] > Task :app:processDebugManifest
[+5200 ms] > Task :app:processDebugResources
[+18100 ms] > Task :app:compileDebugKotlin
[        ] > Task :app:javaPreCompileDebug
[+2599 ms] > Task :app:compileDebugJavaWithJavac
[        ] > Task :app:compileDebugSources
[  +98 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +300 ms] > Task :app:checkDebugDuplicateClasses
[+4807 ms] > Task :app:mergeDebugJavaResource
[+4992 ms] > Task :app:desugarDebugFileDependencies
[+1499 ms] > Task :app:transformClassesWithDexBuilderForDebug
[  +99 ms] > Task :app:validateSigningDebug
[ +200 ms] > Task :app:signingConfigWriterDebug
[ +199 ms] > Task :app:mergeDebugJniLibFolders
[+3899 ms] > Task :app:mergeDebugNativeLibs
[+1700 ms] Unable to strip library
'/home/pato/IdeaProjects/legacyapp/build/app/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/libflutter.so' due to missing strip tool
for ABI 'ARMEABI_V7A'. Packaging it as is.
[ +300 ms] > Task :app:stripDebugDebugSymbols
[        ] Compatible side by side NDK version was not found.
[        ] Unable to strip library '/home/pato/IdeaProjects/legacyapp/build/app/intermediates/merged_native_libs/debug/out/lib/x86/libflutter.so'
due to missing strip tool for ABI 'X86'. Packaging it as is.
[   +1 ms] Unable to strip library
'/home/pato/IdeaProjects/legacyapp/build/app/intermediates/merged_native_libs/debug/out/lib/x86_64/libflutter.so' due to missing strip tool for ABI
'X86_64'. Packaging it as is.
[+3898 ms] > Task :app:mergeExtDexDebug
[+1000 ms] > Task :app:mergeDexDebug
[+14899 ms] > Task :app:packageDebug
[  +17 ms] > Task :app:assembleDebug
[+1683 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[  +99 ms] BUILD SUCCESSFUL in 2m 35s
[  +99 ms] 30 actionable tasks: 29 executed, 1 up-to-date
[+3708 ms] Running Gradle task 'assembleDebug'... (completed in 160.2s, longer than expected)
[  +71 ms] calculateSha: LocalDirectory: '/home/pato/IdeaProjects/legacyapp/build/app/outputs/apk'/app.apk
[ +627 ms] calculateSha: reading file took 626us
[+1236 ms] calculateSha: computing sha took 1235us
[  +36 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[ +141 ms] executing: /home/pato/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/pato/IdeaProjects/legacyapp/build/app/outputs/apk/app.apk
AndroidManifest.xml
[ +604 ms] Exit code 0 from: /home/pato/Android/Sdk/build-tools/29.0.3/aapt dump xmltree
/home/pato/IdeaProjects/legacyapp/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="app.legacy.legacyapp.legacyapp" (Raw: "app.legacy.legacyapp.legacyapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="legacyapp" (Raw: "legacyapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="app.legacy.legacyapp.legacyapp.MainActivity" (Raw: "app.legacy.legacyapp.legacyapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +17 ms] Stopping app 'app.apk' on DRA LX5.
[   +1 ms] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 shell am force-stop app.legacy.legacyapp.legacyapp
[ +407 ms] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 shell pm list packages app.legacy.legacyapp.legacyapp
[+1927 ms] Installing APK.
[   +3 ms] executing: /home/pato/Android/Sdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/pato/Android/Sdk/platform-tools/adb
[        ] executing: /home/pato/Android/Sdk/platform-tools/adb start-server
[   +9 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 install -t -r
/home/pato/IdeaProjects/legacyapp/build/app/outputs/apk/app.apk
[+8520 ms] Performing Streamed Install
                    Success
[        ] Installing build/app/outputs/apk/app.apk... (completed in 8.5s)
[   +4 ms] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 shell echo -n 72f9a5450c8bc51ed05fd6de760c0646cdcc0417 >
/data/local/tmp/sky.app.legacy.legacyapp.legacyapp.sha1
[  +67 ms] DRA LX5 startApp
[   +4 ms] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
app.legacy.legacyapp.legacyapp/app.legacy.legacyapp.legacyapp.MainActivity
[ +586 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=app.legacy.legacyapp.legacyapp/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[+3269 ms] Observatory URL on device: http://127.0.0.1:44578/I8LFLGruARg=/
[   +3 ms] executing: /home/pato/Android/Sdk/platform-tools/adb -s VUY9K19305903265 forward tcp:0 tcp:44578
[   +8 ms] 45784
[        ] Forwarded host port 45784 to device port 44578 for Observatory
[  +19 ms] Connecting to service protocol: http://127.0.0.1:45784/I8LFLGruARg=/
[ +923 ms] Successfully connected to service protocol: http://127.0.0.1:45784/I8LFLGruARg=/
[  +10 ms] Sending to VM service: getVM({})
[  +49 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: MT6739WW, operatingSystem: android, targetCPU: arm, version:
2.8.0-dev.5.0.flutter-fc3af737c7 (Fri Jan 24 09:53:26 2020 +0000) on "android_arm", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid:...
[  +15 ms] Sending to VM service: getIsolate({isolateId: isolates/1674315418879931})
[   +9 ms] Sending to VM service: _flutter.listViews({})
[  +56 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xa5058510, isolate: {type: @Isolate, fixedId: true, id:
isolates/1674315418879931, name: main.dart$main-1674315418879931, number: 1674315418879931}}]}
[  +12 ms] DevFS: Creating new filesystem on the device (null)
[   +2 ms] Sending to VM service: _createDevFS({fsName: legacyapp})
[   +4 ms] D/HWUIExtension(30627): createProgram 0x0000000000000000, binary 0xa1d60000, length 10736, format 37168 within 24074ns
[        ] E/GED     (30627): Failed to get GED Log Buf, err(0)
[        ] D/HWUIExtension(30627): createProgram 0x0000000800000000, binary 0xa1d9e61f, length 10736, format 37168 within 627ns
[  +49 ms] Result: {type: Isolate, id: isolates/1674315418879931, name: main, number: 1674315418879931, _originNumber: 1674315418879931, startTime:
1583556634094, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[ +340 ms] Result: {type: FileSystem, name: legacyapp, uri:
file:///data/user/0/app.legacy.legacyapp.legacyapp/code_cache/legacyappERMSPT/legacyapp/}
[   +2 ms] DevFS: Created new filesystem on the device (file:///data/user/0/app.legacy.legacyapp.legacyapp/code_cache/legacyappERMSPT/legacyapp/)
[   +9 ms] Updating assets
[ +956 ms] Syncing files to device DRA LX5...
[   +2 ms] Scanning asset files
[  +27 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[  +11 ms] /home/pato/development/flutter/bin/cache/dart-sdk/bin/dart
/home/pato/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/pato/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.DMRRUL/app.dill --packages /home/pato/IdeaProjects/legacyapp/.packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +15 ms] <- compile package:legacyapp/main.dart

[  +37 ms] E/flutter (30627): [ERROR:flutter/shell/common/shell.cc(202)] Dart Error: Unhandled exception:
[        ] E/flutter (30627): PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type:
com.pichillilorenzo/flutter_inappwebview
[        ] E/flutter (30627): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
[        ] E/flutter (30627): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
[        ] E/flutter (30627): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
[        ] E/flutter (30627): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/flutter (30627): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/flutter (30627): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/flutter (30627): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (30627): 	at android.os.MessageQueue.next(MessageQueue.java:366)
[        ] E/flutter (30627): 	at android.os.Looper.loop(Looper.java:144)
[        ] E/flutter (30627): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
[        ] E/flutter (30627): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (30627): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
[        ] E/flutter (30627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[        ] E/flutter (30627): , null)
[        ] E/flutter (30627): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter (30627): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] E/flutter (30627): <asynchronous suspension>
[        ] E/flutter (30627): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
[        ] E/flutter (30627): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
[        ] E/flutter (30627): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
[        ] E/flutter (30627): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
[        ] E/flutter (30627): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
[        ] E/flutter (30627): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
[        ] E/flutter (30627): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (30627): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #10     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] E/flutter (30627): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (30627): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #14     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] E/flutter (30627): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
[        ] E/flutter (30627): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #18     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
[        ] E/flutter (30627): #19     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] E/flutter (30627): #20     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
[        ] E/flutter (30627): #21     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
[        ] E/flutter (30627): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (30627): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (30627): #26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
[        ] E/flutter (30627): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (30627): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (30627): #30     RenderProxyBoxMixin.perf
```

**Comment by pichillilorenzo** [comment]
Released new version `3.0.0`!
