### ISSUE TITLE
Some times ChromeCustomTabsActivity crash in onCreate 

### ISSUE THREAD

**Issue by pinball83** [pichillilorenzo/flutter_inappwebview#322]
## Environment

**Flutter version:** 1.12.13+hotfix.9
**Plugin version:**  2.1.0+1
**Android version:**  mainly Android 8, 9, 10

**Device information:**  HUAWEI

## Description

Launch ChromeSafariBrowser did not crash application

Launch ChromeSafariBrowser did crash application irregularly

## Steps to reproduce

Its difficult to reproduce, because of flaky nature of bug. Some times I can reproduce installing HUAWEI browser and make it system default. Open link and return back to application and again open link and some times crashed

## Stacktrace/Logcat 
```
Caused by java.lang.NullPointerException: Attempt to read from field 'java.util.Map com.pichillilorenzo.flutter_inappwebview.f.e' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity.onCreate(:50)
       at android.app.Activity.performCreate(Activity.java:7383)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap12()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by pichillilorenzo** [comment]
Try the latest version `3.2.0` and let me know! Thanks!
