### ISSUE TITLE
App Crash when Chrome is disable 

### ISSUE THREAD

**Issue by samin-fs** [pichillilorenzo/flutter_inappwebview#397]
I'm using ChromSfariBrowser. When I disable chrome, the app is crash with this error:

`android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://oauth.... pkg=com.android.chrome (has extras) }`

also, the app crash when I resume the app, I believe the issue is in InAppBrowserActivity of the plugin line 424;
if (options.hideUrlBar)
options are null when the app is resumed

**Comment by pichillilorenzo** [comment]
`android.content.ActivityNotFoundException: No Activity found to handle Intent` says that there aren't any packages to be able to load your "https://oauth.deriv.app/..." using Android Chrome Custom Tabs feature.
As I said here https://github.com/pichillilorenzo/flutter_inappwebview/issues/391#issuecomment-643744131, I will add the possibility to check if the Android Chrome Custom Tabs feature is available or not.

**Comment by whatamelon** [comment]
Hi @pichillilorenzo, my physical device's default browser is 'Whale'.
And I just open chrome browser in android, app gonna crash.

below here is my crash log. hope it will be help for your solving problem.


--------------------------

W/ActivityThread(26597): handleWindowVisibility: no activity for token android.os.BinderProxy@74191c0
D/PhoneWindow(26597): windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
I/SensorManager(26597): registerListenerImpl() [Sensor: LGE Accelerometer, Rate: 66667, SensorEventListener: com.facebook.appevents.codeless.ViewIndexingTrigger@c0e4cbf] by com.facebook.appevents.codeless.CodelessManager.onActivityResumed():95
D/OneSignal(26597): curActivity is NOW: com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity:com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity@a6e204a
I/TouchFilterInputStageHelper(26597): [needTouchEventFilter] Displayid : 0
D/BezellessGripSuppressionFilter(26597): getdisplaysize, x : 1440 y : 2880
I/flutter (26597): 2020-07-02 00:00:00.0
I/flutter (26597): 2020-06-29 00:00:00.0
D/AndroidRuntime(26597): Shutting down VM
E/AndroidRuntime(26597): FATAL EXCEPTION: main
E/AndroidRuntime(26597): Process: com.memory.and.fitchoo, PID: 26597
E/AndroidRuntime(26597): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=null pkg=com.android.chrome (has extras) }
E/AndroidRuntime(26597):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
E/AndroidRuntime(26597):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
E/AndroidRuntime(26597):        at android.app.Activity.startActivityForResult(Activity.java:4602)
E/AndroidRuntime(26597):        at android.app.Activity.startActivityForResult(Activity.java:4560)
E/AndroidRuntime(26597):        at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:37)
E/AndroidRuntime(26597):        at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity$1.onCustomTabsConnected(ChromeCustomTabsActivity.java:76)
E/AndroidRuntime(26597):        at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.CustomTabActivityHelper.onServiceConnected(CustomTabActivityHelper.java:113)
E/AndroidRuntime(26597):        at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ServiceConnection.onCustomTabsServiceConnected(ServiceConnection.java:24)
E/AndroidRuntime(26597):        at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
E/AndroidRuntime(26597):        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1792)
E/AndroidRuntime(26597):        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1824)
E/AndroidRuntime(26597):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(26597):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26597):        at android.os.Looper.loop(Looper.java:205)
E/AndroidRuntime(26597):        at android.app.ActivityThread.main(ActivityThread.java:6991)
E/AndroidRuntime(26597):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26597):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(26597):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
I/flutter (26597): 2020-05-05 00:00:00.0
I/Process (26597): Sending signal. PID: 26597 SIG: 9
Lost connection to device.

**Comment by Henry-ZP** [comment]
I'm using ChromeSafariBrowser. When I disable Chrome, the app crashes
