### ISSUE TITLE
Crashing when click default context menu which provided by other apps[InAppWebView]

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#443]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   v1.17.1  |
| Plugin version       |  v4.0.0+4  |
| Android version      |  Android 10 (API 29)   |
| iOS version          |   -    |
| Xcode version        |   - |

Device information:  GM1910

## Description
You can see the picture below.
* The three crashing menu item(in red rectangle) is  provided by Google translate, Firefox and Wikipedia
* The others on the left(in green rectangle) are works well, these are provided by Android.

**Expected behavior:** 

**Current behavior:** 
Crashed.
BTW, it works fine in **InAppBrowser**.

## Steps to reproduce
Just do not provide a **contextMenu** argument  in **InAppWebView**.

## Images
![Screenshot_20200708-182616](https://user-images.githubusercontent.com/3091033/86909102-2a525180-c14a-11ea-9a4b-31242c996fcc.jpg)

## Stacktrace/Logcat
```
D/AndroidRuntime( 8674): Shutting down VM
E/AndroidRuntime( 8674): Process: com.pichillilorenzo.flutter_inappwebviewexample, PID: 8674
E/AndroidRuntime( 8674): java.lang.RuntimeException: This method is only implemented for Activity-based Contexts. Check canStartActivityForResult() before calling.
E/AndroidRuntime( 8674):        at android.content.Context.startActivityForResult(Context.java:1847)
E/AndroidRuntime( 8674):        at android.content.ContextWrapper.startActivityForResult(ContextWrapper.java:395)
E/AndroidRuntime( 8674):        at android.content.ContextWrapper.startActivityForResult(ContextWrapper.java:395)
E/AndroidRuntime( 8674):        at android.content.ContextWrapper.startActivityForResult(ContextWrapper.java:395)
E/AndroidRuntime( 8674):        at android.view.View.startActivityForResult(View.java:7425)
E/AndroidRuntime( 8674):        at android.webkit.WebView.access$1201(WebView.java:106)
E/AndroidRuntime( 8674):        at android.webkit.WebView$PrivateAccess.super_startActivityForResult(WebView.java:2437)
E/AndroidRuntime( 8674):        at y5.a(PG:5)
E/AndroidRuntime( 8674):        at wl.onActionItemClicked(PG:16)
E/AndroidRuntime( 8674):        at Mz.onActionItemClicked(PG:1)
E/AndroidRuntime( 8674):        at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView$11.onClick(InAppWebView.java:1721)
E/AndroidRuntime( 8674):        at android.view.View.performClick(View.java:7201)
E/AndroidRuntime( 8674):        at android.view.View.performClickInternal(View.java:7170)
E/AndroidRuntime( 8674):        at android.view.View.access$3500(View.java:806)
E/AndroidRuntime( 8674):        at android.view.View$PerformClick.run(View.java:27582)
E/AndroidRuntime( 8674):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8674):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8674):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8674):        at android.app.ActivityThread.main(ActivityThread.java:7710)
E/AndroidRuntime( 8674):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8674):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 8674):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process ( 8674): Sending signal. PID: 8674 SIG: 9
Lost connection to device.
```

---
How can i hide these menu which provides by other apps?
Or may be i should to construct my custom context menu from scratch?

Thank you.

**Comment by ozyl** [comment]
You can modify this method in the **InAppWebView** class,hope this helps.
```
public ActionMode rebuildActionMode(
          final ActionMode actionMode,
          final ActionMode.Callback callback
  ) {
    boolean hasBeenRemovedAndRebuilt = false;
    if (floatingContextMenu != null) {
      hideContextMenu();
      hasBeenRemovedAndRebuilt = true;
    }
    if (actionMode == null) {
      return null;
    }

    Menu actionMenu = actionMode.getMenu();
    if (options.disableContextMenu) {
      actionMenu.clear();
      return actionMode;
    }

    floatingContextMenu = (LinearLayout) LayoutInflater.from(this.getContext())
            .inflate(R.layout.floating_action_mode, this, false);
    HorizontalScrollView horizontalScrollView = (HorizontalScrollView) floatingContextMenu.getChildAt(0);
    LinearLayout menuItemListLayout = (LinearLayout) horizontalScrollView.getChildAt(0);

    List<Map<String, Object>> customMenuItems = new ArrayList<>();
    ContextMenuOptions contextMenuOptions = new ContextMenuOptions();
    if (contextMenu != null) {
      customMenuItems = (List<Map<String, Object>>) contextMenu.get("menuItems");
      Map<String, Object> contextMenuOptionsMap = (Map<String, Object>) contextMenu.get("options");
     if (contextMenuOptionsMap != null) {
       contextMenuOptions.parse(contextMenuOptionsMap);
     }
    }
    customMenuItems = customMenuItems == null ? new ArrayList<Map<String, Object>>() : customMenuItems;

    if (contextMenuOptions.hideDefaultSystemContextMenuItems == null || !contextMenuOptions.hideDefaultSystemContextMenuItems) {
      for (int i = 0; i < actionMenu.size(); i++) {
        final MenuItem menuItem = actionMenu.getItem(i);
        //edit here start
        if (menuItem.getIntent()!=null){
          continue;
        }
        //edit here start end
        final int itemId = menuItem.getItemId();
        final String itemTitle = menuItem.getTitle().toString();
        TextView text = (TextView) LayoutInflater.from(this.getContext())
                .inflate(R.layout.floating_action_mode_item, this, false);
        text.setText(itemTitle);
        text.setOnClickListener(new OnClickListener() {
          @Override
          public void onClick(View v) {
            hideContextMenu();
            callback.onActionItemClicked(actionMode, menuItem);

            Map<String, Object> obj = new HashMap<>();
            if (inAppBrowserActivity != null)
              obj.put("uuid", inAppBrowserActivity.uuid);
            obj.put("androidId", itemId);
            obj.put("iosId", null);
            obj.put("title", itemTitle);
            channel.invokeMethod("onContextMenuActionItemClicked", obj);
          }
        });
        if (floatingContextMenu != null) {
          menuItemListLayout.addView(text);
        }
      }
    }

    for (final Map<String, Object> menuItem : customMenuItems) {
      final int itemId = (int) menuItem.get("androidId");
      final String itemTitle = (String) menuItem.get("title");
      TextView text = (TextView) LayoutInflater.from(this.getContext())
              .inflate(R.layout.floating_action_mode_item, this, false);
      text.setText(itemTitle);
      text.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
          hideContextMenu();

          Map<String, Object> obj = new HashMap<>();
          if (inAppBrowserActivity != null)
            obj.put("uuid", inAppBrowserActivity.uuid);
          obj.put("androidId", itemId);
          obj.put("iosId", null);
          obj.put("title", itemTitle);
          channel.invokeMethod("onContextMenuActionItemClicked", obj);
        }
      });
      if (floatingContextMenu != null) {
        menuItemListLayout.addView(text);

      }
    }

    final int x = (lastTouch != null) ? lastTouch.x : 0;
    final int y = (lastTouch != null) ? lastTouch.y : 0;
    contextMenuPoint = new Point(x, y);

    if (floatingContextMenu != null) {
      floatingContextMenu.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {

        @Override
        public void onGlobalLayout() {
          if (floatingContextMenu != null) {
            floatingContextMenu.getViewTreeObserver().removeOnGlobalLayoutListener(this);
            if (getSettings().getJavaScriptEnabled()) {
              onScrollStopped();
            } else {
              onFloatingActionGlobalLayout(x, y);
            }
          }
        }
      });
      addView(floatingContextMenu, new LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT, x, y));
      if (hasBeenRemovedAndRebuilt) {
        sendOnCreateContextMenuEvent();
      }
      if (checkContextMenuShouldBeClosedTask != null) {
        checkContextMenuShouldBeClosedTask.run();
      }
    }
    actionMenu.clear();

    return actionMode;
  }

```

**Comment by Doflatango** [comment]
Closed, this issue no longer exists in hybrid composition.
