### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference

### ISSUE THREAD

**Issue by toda-bps** [pichillilorenzo/flutter_inappwebview#450]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 1.20.0-8.0.pre.41 |
| Plugin version       | 4.0.0+4 |
| Android version      | 9.1.0.325 |
| iOS version          |               |
| Xcode version        |               |

Device information: 

SHT-W09

## Description

**Expected behavior:** 

App does not crash.

**Current behavior:** 

Crash with `'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference`.

## Steps to reproduce

1. Repeatedly open and close InAppBrowser.
2. Sometimes my app crashes.

## Stacktrace/Logcat   

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapp, PID: 27791
    java.lang.RuntimeException: Unable to destroy activity {com.example.myapp/com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5176)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5195)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
        at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.t(Unknown Source:34)
        at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onDestroy(Unknown Source:0)
        at android.app.Activity.performDestroy(Activity.java:7737)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1327)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5195) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
```

**Comment by samin-fs** [comment]
@pichillilorenzo I have the same issue, would you please help?
