### ISSUE TITLE
Keyboard getting dismissed in landscape mode and sometimes the webview is crashing

### ISSUE THREAD

**Issue by VikasJilla** [pichillilorenzo/flutter_inappwebview#454]
**Below are the logs I am able to see when keyboard gets dismissed:**
--------------------------------------------------------------------------------
W/IInputConnectionWrapper(30387): getExtractedText on inactive InputConnection
E/Surface (30387): getSlotFromBufferLocked: unknown buffer: 0xb94a87c0
W/IInputConnectionWrapper(30387): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(30387): requestCursorAnchorInfo on inactive InputConnection
W/IInputConnectionWrapper(30387): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(30387): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(30387): getExtractedText on inactive InputConnection

**Sometimes along with auto dismiss of keyboard the below error is coming up and the website in webview is getting stuck:**
----------------------------------------------------------------------------------------------------------------------------------------
I/flutter (30387): Log.DEBUG : =================== CAUGHT DART ERROR
I/flutter (30387): Log.ERROR : 'package:flutter/src/services/platform_views.dart': Failed assertion: line 554 pos 12: '!size.isEmpty': is not true.
[38;5;244mI/flutter (30387): Stack Trace: #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)[39;49m
[38;5;244mI/flutter (30387): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)[39;49m
[38;5;244mI/flutter (30387): #2      AndroidViewController.setSize[39;49m
[38;5;244mI/flutter (30387): #3      RenderAndroidView._sizePlatformView[39;49m
I/flutter (30387): <asynchronous suspension>
[38;5;244mI/flutter (30387): #4      RenderAndroidView.performResize[39;49m
[38;5;244mI/flutter (30387): #5      RenderObject.layout[39;49m
[38;5;244mI/flutter (30387): #6      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter (30387): #7      RenderObject.layout[39;49m
[38;5;244mI/flutter (30387): #8      MultiChildLayoutDelegate.layoutChild[39;49m
[38;5;244mI/flutter (30387): #9      _ScaffoldLayout.performLayout[39;49m
I/flutter (30387): #10     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_
[38;5;244mI/flutter (30387): Log.INFO : #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)[39;49m
[38;5;244mI/flutter (30387): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)[39;49m
[38;5;244mI/flutter (30387): #2      AndroidViewController.setSize[39;49m
[38;5;244mI/flutter (30387): #3      RenderAndroidView._sizePlatformView[39;49m
I/flutter (30387): <asynchronous suspension>
[38;5;244mI/flutter (30387): #4      RenderAndroidView.performResize[39;49m
[38;5;244mI/flutter (30387): #5      RenderObject.layout[39;49m
[38;5;244mI/flutter (30387): #6      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter (30387): #7      RenderObject.layout[39;49m
[38;5;244mI/flutter (30387): #8      MultiChildLayoutDelegate.layoutChild[39;49m
[38;5;244mI/flutter (30387): #9      _ScaffoldLayout.performLayout[39;49m
I/flutter (30387): #10     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart)

**It would be great if I could get some help**

**Comment by VikasJilla** [comment]
Removing Scaffold as parent and using container solved this issue.
