### ISSUE TITLE
NVM CAUSED BY ANOTHER PLUGIN

### ISSUE THREAD

**Issue by panndoraBoo** [pichillilorenzo/flutter_inappwebview#554]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have run the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 1.20.1              |
| Plugin version       | 4.0.0+4     |
| Android version      | 10              |
| iOS version          |        -       |
| Xcode version        |       -        |

Device information: Samsung Galaxy S9+

## Description

**Expected behavior:** 
On startup, the in-app web browser is opened. After successfully loading a certain webpage, the browser should hide and the app starts. On a debug android build, this all works fine. On IOS it works fine too in debug and release.
**Current behavior:** 
When used in an Android release build when the browser hides a few seconds go by at which time the whole app crashes. Crashlytics shows 
java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.pichillilorenzo.flutter_inappwebview.InAppBrowser.a.e' on a null object reference
## Steps to reproduce
Create a release build with the in-app browser hiding after loading a website.

## Stacktrace/Logcat 
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.pichillilorenzo.flutter_inappwebview.InAppBrowser.a.e' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onCreateOptionsMenu(InAppBrowserActivity.java:76)
       at android.app.Activity.onCreatePanelMenu(Activity.java:4119)
       at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
       at androidx.appcompat.app.AppCompatDelegateImpl.b(AppCompatDelegateImpl.java:124)
       at androidx.appcompat.app.AppCompatDelegateImpl.f(AppCompatDelegateImpl.java:61)
       at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:22)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8125)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by pafciu17** [comment]
@panndoraBoo Interesting, which plugin was causing the error and do you know why? I'm asking as it seems I'm having problem.
