### ISSUE TITLE
How to handle the combined sliding of webview and native widgets

### ISSUE THREAD

**Issue by YouCii** [pichillilorenzo/flutter_inappwebview#61]
I want to put a InAppWebView into a Column in SingleChildScrollView, but it cause the page disappear.
I use those code to test.
```dart
  @override
  Widget childBuild(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: CupertinoNavigationBar(leading: Icon(Icons.arrow_back_ios, color: AppColors.THEME, size: 18)),
      body: SingleChildScrollView(
        child: Column(children: <Widget>[Text("title"), _buildWebView()]),
      ),
    );
  }

  Widget _buildWebView() {
    return Expanded(
      child: InAppWebView(initialUrl: 'https://github.com/pichillilorenzo/flutter_inappbrowser'),
    );
  }
```

Then I think that as long as I can get the InAppWebView's height, I can solve this problem by wrapping a Container. 

Can i **get the InAppWebView's height**?

**Comment by YouCii** [comment]
#35 There is an same problem here.

**Comment by YouCii** [comment]
My leadership has again urged the progress of the project. Anyone can help me?

**Comment by pichillilorenzo** [comment]
did you try to put `InAppWebView` inside a Container?
```dart
  Widget _buildWebView() {
    return Expanded(
      child: Container(
        child: InAppWebView(initialUrl: 'https://github.com/pichillilorenzo/flutter_inappbrowser'),
      )
    );
  }
```

**Comment by YouCii** [comment]
Yes, I tried it, but it is the same as before. 

Today i am going to try the way of get the height by JS functions and then get the height through JavaScriptHandler. Hope it works,

**Comment by pichillilorenzo** [comment]
Do you have this problem only on one platform or both Android and iOS?

**Comment by YouCii** [comment]
The above problem is on Android.
When i try it on IOS, the webview is not show at all.  This is the suspicious log.
```
(Flutter) [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
```

**Comment by pichillilorenzo** [comment]
Ok!
For iOS, as said on the [README.md](https://github.com/pichillilorenzo/flutter_inappbrowser#inappwebview-class):

> To use InAppWebView class on iOS you need to opt-in for the embedded views preview by adding a boolean property to the app's Info.plist file, with the key io.flutter.embedded_views_preview and the value YES.

**Comment by YouCii** [comment]
After editing the Info.plist file, WebView is normally displayed on IOS, but it has the same problem as Android.

**Comment by pichillilorenzo** [comment]
Ok, so maybe it is something related to `SingleChildScrollView`. If you run my example, does it work?

**Comment by YouCii** [comment]
The example works well before i do this:
```
Widget build(BuildContext context) {
    return SingleChildScrollView(...);
}
```

In fact, `SingleChildScrollView` is not necessary. I just want to think of the `InAppWebView` as an item in a list so that it can slide together with other Widgets. 

As long as we can achieve this, anything is fine, regardless of `SingleChildScrollView`.

**Comment by YouCii** [comment]
I tried to set the height manually like this: 
```dart
Container(
      height: _webHeight,
      child: InAppWebView(
        initialData: InAppWebViewInitialData(_newsContentBean.content),
        onWebViewCreated: (InAppWebViewController controller) {
          webViewController = controller;
        },
      ),
    );
```
But when the height is greater than 5,500, the app crash without any log. 
When I set the height of an empty container, there is no problem.

**Comment by peekpt** [comment]
This problems happens to me. 
I get the html content chopped or if I set an height will crash at some dimension. I wanted to use this inside a CustomScrollView, I tried everything and there's no way I could get it working. 
I think it needs its parent to have an height, so it an take that height to render content.

**Comment by YouCii** [comment]
I got the error log thrown when setting the height to above 5460: 
```
Launching lib/main.dart on HUAWEI NXT AL10 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device HUAWEI NXT AL10...
I/hwaps   ( 6903): JNI_OnLoad
D/HwCust  ( 6903): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
D/HwSensorManager( 6903): HwSensorManager version: 1.0.0
I/cr_BrowserStartup( 6903): Initializing chromium process, singleProcess=true
W/GooglePlayServicesUtil( 6903): Google Play Store is missing.
W/GooglePlayServicesUtil( 6903): Google Play Store is missing.
W/GooglePlayServicesUtil( 6903): Google Play Store is missing.
I/art     ( 6903): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$6>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
I/art     ( 6903):   at com.android.webview.chromium.WebViewContentsClientAdapter com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebViewContentsClientAdapter(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:328)
I/art     ( 6903):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
I/art     ( 6903):   at void com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebView.<init>(android.content.Context, java.lang.Object, int, com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebViewOptions) (InAppWebView.java:92)
I/art     ( 6903):   at void com.pichillilorenzo.flutter_inappbrowser.FlutterWebView.<init>(io.flutter.plugin.common.PluginRegistry$Registrar, int, java.util.HashMap) (FlutterWebView.java:51)
I/art     ( 6903):   at io.flutter.plugin.platform.PlatformView com.pichillilorenzo.flutter_inappbrowser.FlutterWebViewFactory.create(android.content.Context, int, java.lang.Object) (FlutterWebViewFactory.java:29)
I/art     ( 6903):   at void io.flutter.plugin.platform.SingleViewPresentation.onCreate(android.os.Bundle) (SingleViewPresentation.java:130)
I/art     ( 6903):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:524)
I/art     ( 6903):   at void android.app.Dialog.show() (Dialog.java:385)
I/art     ( 6903):   at void android.app.Presentation.show() (Presentation.java:235)
I/art     ( 6903):   at void io.flutter.plugin.platform.VirtualDisplayController.<init>(android.content.Context, android.hardware.display.VirtualDisplay, io.flutter.plugin.platform.PlatformViewFactory, android.view.Surface, io.flutter.view.TextureRegistry$SurfaceTextureEntry, int, java.lang.Object) (VirtualDisplayController.java:75)
I/art     ( 6903):   at io.flutter.plugin.platform.VirtualDisplayController io.flutter.plugin.platform.VirtualDisplayController.create(android.content.Context, io.flutter.plugin.platform.PlatformViewFactory, io.flutter.view.TextureRegistry$SurfaceTextureEntry, int, int, int, java.lang.Object) (VirtualDisplayController.java:47)
I/art     ( 6903):   at void io.flutter.plugin.platform.PlatformViewsController.createPlatformView(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (PlatformViewsController.java:179)
I/art     ( 6903):   at void io.flutter.plugin.platform.PlatformViewsController.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (PlatformViewsController.java:118)
I/art     ( 6903):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/art     ( 6903):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/art     ( 6903):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/art     ( 6903):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     ( 6903):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:356)
I/art     ( 6903):   at void android.os.Looper.loop() (Looper.java:138)
I/art     ( 6903):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
I/art     ( 6903):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     ( 6903):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
I/art     ( 6903):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
I/art     ( 6903): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/system/app/WebViewGoogle/WebViewGoogle.apk"],nativeLibraryDirectories=[/system/app/WebViewGoogle/lib/arm64, /system/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
I/art     ( 6903):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     ( 6903):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     ( 6903):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     ( 6903):   at com.android.webview.chromium.WebViewContentsClientAdapter com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebViewContentsClientAdapter(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:328)
I/art     ( 6903):   at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
I/art     ( 6903):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
I/art     ( 6903):   at void com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebView.<init>(android.content.Context, java.lang.Object, int, com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebViewOptions) (InAppWebView.java:92)
I/art     ( 6903):   at void com.pichillilorenzo.flutter_inappbrowser.FlutterWebView.<init>(io.flutter.plugin.common.PluginRegistry$Registrar, int, java.util.HashMap) (FlutterWebView.java:51)
I/art     ( 6903):   at io.flutter.plugin.platform.PlatformView com.pichillilorenzo.flutter_inappbrowser.FlutterWebViewFactory.create(android.content.Context, int, java.lang.Object) (FlutterWebViewFactory.java:29)
I/art     ( 6903):   at void io.flutter.plugin.platform.SingleViewPresentation.onCreate(android.os.Bundle) (SingleViewPresentation.java:130)
I/art     ( 6903):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:524)
I/art     ( 6903):   at void android.app.Dialog.show() (Dialog.java:385)
I/art     ( 6903):   at void android.app.Presentation.show() (Presentation.java:235)
I/art     ( 6903):   at void io.flutter.plugin.platform.VirtualDisplayController.<init>(android.content.Context, android.hardware.display.VirtualDisplay, io.flutter.plugin.platform.PlatformViewFactory, android.view.Surface, io.flutter.view.TextureRegistry$SurfaceTextureEntry, int, java.lang.Object) (VirtualDisplayController.java:75)
I/art     ( 6903):   at io.flutter.plugin.platform.VirtualDisplayController io.flutter.plugin.platform.VirtualDisplayController.create(android.content.Context, io.flutter.plugin.platform.PlatformViewFactory, io.flutter.view.TextureRegistry$SurfaceTextureEntry, int, int, int, java.lang.Object) (VirtualDisplayController.java:47)
I/art     ( 6903):   at void io.flutter.plugin.platform.PlatformViewsController.createPlatformView(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (PlatformViewsController.java:179)
I/art     ( 6903):   at void io.flutter.plugin.platform.PlatformViewsController.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (PlatformViewsController.java:118)
I/art     ( 6903):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/art     ( 6903):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/art     ( 6903):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/art     ( 6903):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     ( 6903):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:356)
I/art     ( 6903):   at void android.os.Looper.loop() (Looper.java:138)
I/art     ( 6903):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
I/art     ( 6903):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     ( 6903):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
I/art     ( 6903):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
I/art     ( 6903): 
D/NetworkSecurityConfig( 6903): No Network Security Config specified, using platform default
V/AudioManager( 6903): isWiredHeadsetOn...
W/cr_media( 6903): Requires BLUETOOTH permission
D/HwRTBlurUtils( 6903): check blur style for HwPhoneWindow-, themeResId : 0x0103023e, context : android.app.Presentation$3@ad9a49e, Nhwext : 0, get Blur : disable with , null
D/HwRTBlurUtils( 6903): check blur style for HwPhoneWindow-, themeResId : 0x0103023e, context : android.app.Presentation$3@ad9a49e, Nhwext : 0, get Blur : disable with , null
I/HwPointEventFilter( 6903): support AFT
E/cr_SafeBrowsingApi( 6903): Unable to determine user opt-in preference
E/libEGL  ( 6903): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
W/VideoCapabilities( 6903): Unrecognized profile/level 1/32 for video/mp4v-es
I/VideoCapabilities( 6903): Unsupported profile 16384 for video/mp4v-es
I/VideoCapabilities( 6903): Unsupported profile 16384 for video/mp4v-es
W/VideoCapabilities( 6903): Unsupported mime video/x-pn-realvideo
W/VideoCapabilities( 6903): Unsupported mime video/mpeg
W/VideoCapabilities( 6903): Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities( 6903): Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities( 6903): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 6903): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities( 6903): Unsupported mime video/vc1
W/VideoCapabilities( 6903): Unsupported mime video/x-flv
D/mali_winsys( 6903): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
I/VideoCapabilities( 6903): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 6903): HW encoder for video/avc is not available on this device.
D/HwuiUseBinaryProgram( 6903): Key: 34359738400 has not found in mBinaryEntries, Compile it.
E/GLConsumer( 6903): [SurfaceTexture-0-6903-0] bindTextureImage: error binding external image: 0x501
E/flutter ( 6903): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter ( 6903): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter ( 6903): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
E/flutter ( 6903): 
F/flutter ( 6903): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(130)] Check failed: CheckException(env). 
W/google-breakpad( 6903): ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad( 6903): Chrome build fingerprint:
W/google-breakpad( 6903): 2.2.2
W/google-breakpad( 6903): 8
W/google-breakpad( 6903): ### ### ### ### ### ### ### ### ### ### ### ### ###
F/libc    ( 6903): Fatal signal 6 (SIGABRT), code -6 in tid 6927 (Thread-8)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B596:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 6903, tid: 6927, name: Thread-8  >>> com.cns.ecnsflutter <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(130)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   0000000000001b0f  x2   0000000000000006  x3   0000000000000008
    x4   000000000000017e  x5   0000008000000000  x6   000000705d29a000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  0004965e493fbdb3
    x16  000000705a808ec8  x17  000000705a7b1c28  x18  00000000ebad6082  x19  00000070511d24f8
    x20  0000000000000006  x21  00000070511d2450  x22  0000000000000000  x23  000000701eeedf40
    x24  0000000000000024  x25  0000000000000000  x26  0000007050e11970  x27  000000704e369d58
    x28  0000000000000001  x29  00000070511d0310  x30  000000705a7af0d0
    sp   00000070511d02f0  pc   000000705a7b1c30  pstate 0000000060000000
backtrace:
    #00 pc 000000000006bc30  /system/lib64/libc.so (tgkill+8)
    #01 pc 00000000000690cc  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023e68  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c8ec  /system/lib64/libc.so (abort+52)
    #04 pc 0000000000cb8484  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #05 pc 0000000000c98308  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #06 pc 0000000000cb523c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #07 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #08 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #09 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #10 pc 0000000000cb2964  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #11 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #12 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #13 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #14 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #15 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #16 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #17 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #18 pc 0000000000cb3994  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #19 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #20 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #21 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #22 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #23 pc 0000000000cb2e4c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #24 pc 0000000000cb5348  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #25 pc 0000000000cb30e0  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #26 pc 0000000000cb1e00  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #27 pc 0000000000ce2568  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #28 pc 0000000000ce2958  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #29 pc 0000000000ce2b1c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #30 pc 0000000000ce283c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #31 pc 0000000000ce2a54  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #32 pc 0000000000cb98bc  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #33 pc 0000000000cbb4ac  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #34 pc 0000000000018500  /vendor/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+852)
    #35 pc 00000000000180fc  /vendor/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
    #36 pc 0000000000011088  /system/lib64/libandroid.so (ALooper_pollOnce+100)
    #37 pc 0000000000cbb57c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #38 pc 0000000000cb88bc  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #39 pc 0000000000cb9e3c  /data/app/com.cns.ecnsflutter-2/lib/arm64/libflutter.so (offset 0xc90000)
    #40 pc 00000000000688d4  /system/lib64/libc.so (_ZL15__pthread_startPv+196)
    #41 pc 000000000001db00  /system/lib64/libc.so (__start_thread+16)
Lost connection to device.

```

**Comment by rolends1986** [comment]
halo!
my solution...
![image](https://user-images.githubusercontent.com/11939619/60775460-f8349b00-a155-11e9-8b2d-504ab03d436a.png)
1,Define JavaScript get dom size
2,Call JavaScript Fun at Dart runtime
3,Change container height

**Comment by YouCii** [comment]
@rolends1986 Yes, this is my final solution too, but have you ever find that the app running on Android will crash when the height exceeds a certain value ?

**Comment by rolends1986** [comment]
> @rolends1986 Yes, this is my final solution too, but have you ever find that the app running on Android will crash when the height exceeds a certain value ?
@YouCii 
你要初始设置一个适合的值，用于在load回调之前，我的htmlHeight初始设置为500

**Comment by mobikats** [comment]
Hello, I have this exact same problem, but I am struggling to read your image of your JavaScript solution above (I need to zoom in a lot to get the text big enough but then it is very blurry), I'm hoping a kind soul here would share the text file please?
