### ISSUE TITLE
Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by Ali1Ammar** [pichillilorenzo/flutter_inappwebview#642]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    1.22        |
| Plugin version       |        master    |
| Android version      |    10           |

Device information:  Galaxy J6+

## Description

**Expected behavior:** 
everythings work fine

**Current behavior:** 
app crash on startup on Galaxy J6+ i get it from crashlytics also  real user reported to me 

```
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.CookieManager.getInstance(CookieManager.java:47)
       at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>(MyCookieManager.java:17)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.a(InAppWebViewFlutterPlugin.java:46)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.a(InAppWebViewFlutterPlugin.java:22)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.a(FlutterEnginePluginRegistry.java:79)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
       at com.sjaj.iq.MainActivity.configureFlutterEngine(MainActivity.java:5)
       at io.flutter.embedding.android.FlutterFragment.a(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.a(FlutterActivityAndFragmentDelegate.java:64)
       at io.flutter.embedding.android.FlutterFragment.b(FlutterFragment.java:12)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:21)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:435)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:206)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:18)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:36)
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:111)
       at androidx.fragment.app.FragmentManagerImpl.c(FragmentManagerImpl.java:88)
       at androidx.fragment.app.FragmentManagerImpl.q(FragmentManagerImpl.java:21)
       at androidx.fragment.app.FragmentManagerImpl.d(FragmentManagerImpl.java:9)
       at androidx.fragment.app.FragmentManagerImpl.f(FragmentManagerImpl.java:6)
       at androidx.fragment.app.FragmentController.a(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:15)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7978)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

```
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.CookieManager.getInstance(CookieManager.java:47)
       at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>(MyCookieManager.java:17)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.a(InAppWebViewFlutterPlugin.java:46)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.a(InAppWebViewFlutterPlugin.java:22)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.a(FlutterEnginePluginRegistry.java:79)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
       at com.sjaj.iq.MainActivity.configureFlutterEngine(MainActivity.java:5)
       at io.flutter.embedding.android.FlutterFragment.a(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.a(FlutterActivityAndFragmentDelegate.java:64)
       at io.flutter.embedding.android.FlutterFragment.b(FlutterFragment.java:12)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:21)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:435)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:206)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:18)
       at androidx.fragment.app.FragmentTransition.a(FragmentTransition.java:36)
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:111)
       at androidx.fragment.app.FragmentManagerImpl.c(FragmentManagerImpl.java:88)
       at androidx.fragment.app.FragmentManagerImpl.q(FragmentManagerImpl.java:21)
       at androidx.fragment.app.FragmentManagerImpl.d(FragmentManagerImpl.java:9)
       at androidx.fragment.app.FragmentManagerImpl.f(FragmentManagerImpl.java:6)
       at androidx.fragment.app.FragmentController.a(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:15)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7978)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

error title at crashlytics
` com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init> `

**Comment by Bunny1376** [comment]
same issue in flutter 2.2.2
android version 12
