### ISSUE TITLE
App closes if I exit file selection without selecting an image

### ISSUE THREAD

**Issue by Shubhankt1** [pichillilorenzo/flutter_inappwebview#656]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.22.5|
| Plugin version       |^4.0.0+4|
| Android version      |8+|
| iOS version          |               |
| Xcode version        |12.4 |

Device information: Any android device

## Description

**Expected behavior:** I should be able to go back to the webiview rather than getting thrown out of the app.

**Current behavior:** Inside a webview, when I try to upload an image for HTML inputs such as `<input type="file" accept="image/*" capture>` and after the Camera/Files opens and I try to go back without selecting any image, the app closes completely without any crash message/popup on the screen.

## Steps to reproduce

Inside the webview
1. Click on HTML input button (for `type=image`)
2. Select camera or file
3. press on back button without selecting anything. The app will get closed completely.

## Stacktrace/Logcat   
I'm not sure if this stack trace belongs to the current problem, but this is the only time when app gets destroyed.

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.tipotapp.tipotapp/com.example.flutter_app.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method e.e.a.b.c, parameter activity
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4521)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4539)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
```
Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method e.e.a.b.c, parameter activity
       at com.lyokone.location.FlutterLocationService.a(FlutterLocationService.java:2)
       at com.lyokone.location.LocationPlugin.a(LocationPlugin.java:51)
       at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java)
       at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:52)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:58)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:10)
       at android.app.Activity.performDestroy(Activity.java:7524)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4506)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4539)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent {  }} to activity {com.tipotapp.tipotapp/com.example.flutter_app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4423)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:14)
       at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:43)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:2)
       at android.app.Activity.dispatchActivityResult(Activity.java:7590)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4416)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by boucoding** [comment]
Stuck at this too

**Comment by pichillilorenzo** [comment]
Have you tried latest version?
