### ISSUE TITLE
useHybridComposition: true App crash

### ISSUE THREAD

**Issue by klaszlo8207** [pichillilorenzo/flutter_inappwebview#717]
I am on android10

When I use this line:

useHybridComposition: true

I got this error and my app is died:

java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
E/AndroidRuntime(29687): 	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
E/AndroidRuntime(29687): 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
E/AndroidRuntime(29687): 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
E/AndroidRuntime(29687): 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:113)
E/AndroidRuntime(29687): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1573)
E/AndroidRuntime(29687): 	at io.flutter.embedding.android.FlutterImageView.onDraw(FlutterImageView.java:242)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21651)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21520)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4604)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21518)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4604)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21518)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4604)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21518)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4604)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21518)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4604)
E/AndroidRuntime(29687): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
E/AndroidRuntime(29687): 	at android.view.View.draw(View.java:21654)
E/AndroidRuntime(29687): 	at com.android.internal.policy.DecorView.draw(DecorView.java:1005)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4019)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3923)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3703)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2992)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
E/AndroidRuntime(29687): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
E/AndroidRuntime(29687): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
E/AndroidRuntime(29687): 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
E/AndroidRuntime(29687): 	at android.view.Choreographer.doFrame(Choreographer.java:776)
E/AndroidRuntime(29687): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
E/AndroidRuntime(29687): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(29687): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(29687): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(29687): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/AndroidRuntime(29687): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(29687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

when useHybridComposition: false

It is working, but I can't see video picture on the youtube video only sounds

**Comment by klaszlo8207** [comment]
android:hardwareAccelerated="true" added to activity solved, closed
