### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by bhtri** [pichillilorenzo/flutter_inappwebview#718]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.1          |
| Plugin version       |     ^5.1.0+4          |
| Android version      |    4.1           |
| iOS version          |     iOS-13-0 (simulator)          |
| Xcode version        |     12.4, Build version 12D4e          |

Device information: 

## Description

I want to try to use the InAppWebView widget (like the following code), the error of losing connection to the device appears.
I have tried searching but it does not seem like the case I am having
Thank you very much

## Steps to reproduce

`flutter run`

## My code   
<details>
<summary>My code</summary>

```
class _Example extends State<Example> {
  InAppWebViewController _webViewController;
  InAppWebViewGroupOptions _options = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      useShouldOverrideUrlLoading: true,
      mediaPlaybackRequiresUserGesture: false,
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
    ios: IOSInAppWebViewOptions(
      allowsInlineMediaPlayback: true,
    ),
  );

  @override
  Widget build(BuildContext context) {
    Widget webview = InAppWebView(
      initialUrlRequest: URLRequest(url: Uri.parse('https://flutter.dev')),
      // initialFile: "assets/html/example5.html",
      initialOptions: _options,
      onWebViewCreated: (controller) {
        _webViewController = controller;
      },
      onConsoleMessage: (controller, consoleMessage) {
        print('Flutter side: InAppWebView::onConsoleMessage');
        print(consoleMessage.message);
      },
    );

    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(
          title: Text('Exampel'),
        ),
        body: Container(
          child: Column(
            children: <Widget>[
              combobox,
              SizedBox(height: 10),
              webview,
              SizedBox(height: 10),
              btnLogin,
            ],
          ),
        ),
      ),
    );
  }
```

</details>

## Stacktrace/Logcat   
<details>
<summary>Logs</summary>

```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build failed due to concurrent builds, will retry in 2 seconds.
Running Xcode build...
 └─Compiling, linking and signing...                         5.1s
Xcode build done.                                           39.4s

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderConstrainedBox object was given an infinite size during layout.
This probably means that it is a render object that tries to be as big as possible, but it was put
inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: RenderFlex#9aece relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: Column ← Container ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
    CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#e52a3 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    PhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=796.0)
  size: MISSING
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
The constraints that applied to the RenderConstrainedBox were:
  BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
The exact size it was given was:
  Size(414.0, Infinity)
See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

The relevant error-causing widget was:
  UiKitView
  file:///Users/home/SourceCode/develop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.1.0+4/lib/src/in_app_webview/in_app_webview.dart:433:14

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2216:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2310:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:2002:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:2004:6)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:282:7)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#6      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
#7      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:830:43)
#8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:932:32)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:925:7)
#12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
#13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#18     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1371:11)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#26     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
#27     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#28     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#41     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3362:13)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#45     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#54     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:546:11)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#60     RenderView.performLayout (package:flutter/src/rendering/view.dart:153:14)
#61     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1641:7)
#62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
#63     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#64     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#65     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#66     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#67     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#68     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#df8fc relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT:
  creator: SizedBox.expand ← UiKitView ← InAppWebView ← Column ← Container ← _BodyBuilder ← MediaQuery
    ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
    AnimatedDefaultTextStyle ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
  size: Size(414.0, Infinity)
  additionalConstraints: BoxConstraints(biggest)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.

Another exception was thrown: SemanticsNode#5(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), invisible) (with null) tried to set a non-finite rect.

Another exception was thrown: Bad state: Future already completed

Another exception was thrown: RenderUiKitView object was given an infinite size during layout.

Another exception was thrown: RenderUiKitView object was given an infinite size during layout.

Another exception was thrown: SemanticsNode#5(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), invisible) (with null) tried to set a non-finite rect.
Lost connection to device.
```

</details>

**Comment by nilotpalkapri** [comment]
Try this,
`body: Container(
          height: MediaQuery.of(context).size.height;
          child: Column(
            children: <Widget>[
              combobox,
              SizedBox(height: 10),
              webview,
              SizedBox(height: 10),
              btnLogin,
            ],
          ),
        ),`

**Comment by bhtri** [comment]
Thank you @nilotpalkapri , I tried your way and it worked.
I have just touched Flutter recently, so can you explain to me why wrap `InAppWebView` widget in a `Container` widget with height works properly?

**Comment by nilotpalkapri** [comment]
It's because webview has infinite hight just like singlechildscrollview widget.
