### ISSUE TITLE
java.lang.NullPointerException: com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewRenderProcessClient$1.success(InAppWebViewRenderProcessClient.java:37)

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#757]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.3          |
| Plugin version       |     5.2.1+1          |
| Android version      |     10          |
| iOS version          |               |
| Xcode version        |               |

Device information: 
MIUI 12.0.2

Seems happens when loading a page for a long time.

## Stacktrace/Logcat   
```
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): Failed to handle method call result
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewRenderProcessClient$1.success(InAppWebViewRenderProcessClient.java:37)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:210)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:105)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:829)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at android.os.Looper.loop(Looper.java:180)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_2(11684): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by pichillilorenzo** [comment]
Oh wow, I forgot to put a test on possible `null` value! Thanks for reporting this!
