### ISSUE TITLE
App Crashed (InAppBrowserActivity.java line 34)

### ISSUE THREAD

**Issue by shinsenter** [pichillilorenzo/flutter_inappwebview#777]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.27.0-5.0.pre.39             |
| Plugin version       |  4.0.0             |
| Android version      |  8~10             |
| iOS version          |  △             |
| Xcode version        |  △             |

Device information: 

```
30% Sony
17% SHARP
15% FUJITSU
14% KYOCERA
12% HUAWEI
4% OUKITEL
4% Samsung
3% OPPO
<1% motorola
```

## Description

**Expected behavior:** 
No crashes

**Current behavior:** 
From Firebase Crashlytics

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4963)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4992)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:359)
       at android.app.ActivityThread.main(ActivityThread.java:7418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.dispose(InAppBrowserActivity.java:34)
       at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onDestroy(InAppBrowserActivity.java)
       at android.app.Activity.performDestroy(Activity.java:8048)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4948)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4992)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:359)
       at android.app.ActivityThread.main(ActivityThread.java:7418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

## Steps to reproduce

Could not reproduce.

**Comment by pichillilorenzo** [comment]
This is fixed with the new version 5. Version 4 is not supported anymore.

**Comment by shinsenter** [comment]
@pichillilorenzo 
Crashes also happened with the latest version #794
