### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by dkunkic** [pichillilorenzo/flutter_inappwebview#801]
-  I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
-  I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
-  I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
-  I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.3          |
| Plugin version       |     5.3.0          |
| Android version      |      8 - 11         |

Device information:  Samsung - mostly Galaxy A51, Galaxy A50
Huawei Mate 10 Lite, LG Velvet, Sony Xperia XZ Premium

## Description

I don't know how to reproduce it, but I get this error on Firebase Crashlytics.

**Current behavior:** 
Here is the log from the Firebase 

       Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3556)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
       

       Caused by java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onCreate(ChromeCustomTabsActivity.java:42)
       at android.app.Activity.performCreate(Activity.java:7955)
       at android.app.Activity.performCreate(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by pichillilorenzo** [comment]
It should be impossible that when creating an instance of the `ChromeSafariBrowser`, the `java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference` could happen.
It doesn't make any sense to me, as a `ChromeSafariBrowserManager` native class is always instantiated before starting a new `ChromeCustomTabsActivity`, otherwise, it couldn't do that.
Could you post the code you are using about the `ChromeSafariBrowser` class? How are you using it? Where do you call it? Thanks

**Comment by dkunkic** [comment]
I'm using InAppWebView as a widget, and then in shouldOverrideUrlLoading method, depending on which url I get, I open the browser.

InAppWebView(
                              initialUrlRequest: URLRequest(
                                  url: Uri.parse(UrlConstants.liveTickerUrl)),
                              initialOptions: InAppWebViewGroupOptions(
                                  android: AndroidInAppWebViewOptions(
                                      verticalScrollbarPosition:
                                          AndroidVerticalScrollbarPosition
                                              .SCROLLBAR_POSITION_RIGHT),
                                  crossPlatform: InAppWebViewOptions(
                                    supportZoom: false,
                                    useShouldOverrideUrlLoading: true,
                                  )),
                              onWebViewCreated: (controller) {
                                webView = controller;
                                // Hide Progress Indicator
                                loadingIndicatorVisible.value = false;
                              },
                              shouldOverrideUrlLoading:
                                  (controller, navigationActionPolicy) async {
                                var url = navigationActionPolicy.request.url!;

                                if (url
                                    .toString()
                                    .trim()
                                    .contains(UrlConstants.aditionUrl.trim())) {
                                  chromeSafariBrowser.open(url: url);
                                  return NavigationActionPolicy.CANCEL;
                                }

                                return NavigationActionPolicy.ALLOW;
                              }),
<img width="477" alt="Screenshot 2021-04-14 at 15 12 07" src="https://user-images.githubusercontent.com/13023358/114716082-00126d80-9d34-11eb-9321-93b574479555.png">
<img width="504" alt="Screenshot 2021-04-14 at 15 12 48" src="https://user-images.githubusercontent.com/13023358/114716087-00ab0400-9d34-11eb-99c1-2cdbdc608c9b.png">

**Comment by MathieuBa** [comment]
Hello, I've got the same crash on Android version 7 using ChromeSafariBrowser.

The crash intervene when the host is blocked by an htaccess but working otherwise.

```
2697-2697/my.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app.dev, PID: 2697
    java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app.dev/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onCreate(ChromeCustomTabsActivity.java:52)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```


My code :
    ```
    ChromeSafariBrowser _browser = new ChromeSafariBrowser();

    ...

    await _browser.open(
        url: uri,
        options: ChromeSafariBrowserClassOptions(
          android: AndroidChromeCustomTabsOptions(
            addDefaultShareMenuItem: false,
            enableUrlBarHiding: true,
            showTitle: false,
            toolbarBackgroundColor: Colors.black,
          ),
          ios: IOSSafariOptions(barCollapsingEnabled: true, dismissButtonStyle: IOSSafariDismissButtonStyle.CANCEL),
        ),
      );
```

**Comment by shinsenter** [comment]
Same #794

**Comment by dkunkic** [comment]
> Hello, I've got the same crash on Android version 7 using ChromeSafariBrowser.
> 
> The crash intervene when the host is blocked by an htaccess but working otherwise.
> 
> ```
> 2697-2697/my.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: my.app.dev, PID: 2697
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app.dev/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
>         at android.app.ActivityThread.-wrap14(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:154)
>         at android.app.ActivityThread.main(ActivityThread.java:6682)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
>      Caused by: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
>        at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onCreate(ChromeCustomTabsActivity.java:52)
>         at android.app.Activity.performCreate(Activity.java:6942)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
>         at android.app.ActivityThread.-wrap14(ActivityThread.java) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:154) 
>         at android.app.ActivityThread.main(ActivityThread.java:6682) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
> ```
> 
> My code :
> 
> ```
>     ChromeSafariBrowser _browser = new ChromeSafariBrowser();
>     ...
>     await _browser.open(
>         url: uri,
>         options: ChromeSafariBrowserClassOptions(
>           android: AndroidChromeCustomTabsOptions(
>             addDefaultShareMenuItem: false,
>             enableUrlBarHiding: true,
>             showTitle: false,
>             toolbarBackgroundColor: Colors.black,
>           ),
>           ios: IOSSafariOptions(barCollapsingEnabled: true, dismissButtonStyle: IOSSafariDismissButtonStyle.CANCEL),
>         ),
>       );
> ```

Can you please give me more information on how to reproduce the bug. Thanks!

**Comment by JasonSheedy** [comment]
I'm seeing the same issue reported in crashlytics on a variety of devices. Has there been any progress identifying the root cause @pichillilorenzo Looking at the source for ChromeCustomTabsActivity I can see there's a lot of potential for this to be returned as null. I'm not sure how this is set in the Bundle, but it seems if the managerId is not set this will result in an NPE. 

`
Bundle b = getIntent().getExtras();
    assert b != null;
    id = b.getString("id");

    String managerId = b.getString("managerId");
    manager = (ChromeSafariBrowserManager) ChromeSafariBrowserManager.shared.get(managerId);
`

**Comment by andredealmei** [comment]
is there any workaround for this ?

**Comment by pichillilorenzo** [comment]
Have you tried the latest version of the plugin? There shouldn't be that error anymore

**Comment by sarunyool** [comment]
@diegoalex 
Hello, I would like to follow up your issue. 
We have been getting the same logs as you recently. 
Have you updated to the latest version? 
Do you still get the same crash log?


Thank you in advance.

**Comment by SanguleAKB** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.example.demonews, PID: 30777
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demonews/com.example.demonews.ui.MainActivity}: android.view.InflateException: Binary XML file line #75 in com.example.demonews:layout/activity_main: Binary XML file line #75 in com.example.demonews:layout/activity_main: Error inflating class fragment
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3766)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3914)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2417)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8194)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #75 in com.example.demonews:layout/activity_main: Binary XML file line #75 in com.example.demonews:layout/activity_main: Error inflating class fragment
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #75 in com.example.demonews:layout/activity_main: Error inflating class fragment
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property viewModel has not been initialized
                                                                                                    	at com.example.demonews.ui.MainActivity.getViewModel(MainActivity.kt:20)
                                                                                                    	at com.example.demonews.ui.Fragments.BreakingNewsFragment.onViewCreated(BreakingNewsFragment.kt:28)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:410)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:271)
                                                                                                    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
                                                                                                    	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
                                                                                                    	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:247)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:226)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.example.demonews.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:66)
2024-02-25 22:23:01.823 30777-30777 AndroidRuntime          com.example.demonews                 E  	at com.example.demonews.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:60)
                                                                                                    	at com.example.demonews.ui.MainActivity.onCreate(MainActivity.kt:24)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8575)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8554)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1419)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3747)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3914)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2417)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8194)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
2024-02-25 22:23:01.834 30777-30777 Process                 com.example.demonews                 I  Sending signal. PID: 30777 SIG: 9

**Comment by SanguleAKB** [comment]
### I found this error continuously.
