### ISSUE TITLE
NullPointerException: exit when the request is loading, please fix it

### ISSUE THREAD

**Issue by LinChengChun** [pichillilorenzo/flutter_inappwebview#82]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebView.destroy()' on a null object reference
W/System.err(26220): 	at com.pichillilorenzo.flutter_inappbrowser.FlutterWebView$1.onPageFinished(FlutterWebView.java:227)
W/System.err(26220): 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:690)
W/System.err(26220): 	at org.chromium.android_webview.AwWebContentsObserver.didFinishLoad(AwWebContentsObserver.java:44)
W/System.err(26220): 	at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didFinishLoad(WebContentsObserverProxy.java:162)
W/System.err(26220): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(26220): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(26220): 	at android.os.Handler.dispatchMessage(Handler.java:111)
W/System.err(26220): 	at android.os.Looper.loop(Looper.java:194)
W/System.err(26220): 	at android.app.ActivityThread.main(ActivityThread.java:5889)
W/System.err(26220): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(26220): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(26220): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
W/System.err(26220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
F/chromium(26220): [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report
W/google-breakpad(26220): ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad(26220): Chrome build fingerprint:
W/google-breakpad(26220): 1.0.0
W/google-breakpad(26220): 1
W/google-breakpad(26220): ### ### ### ### ### ### ### ### ### ### ### ### ###

**Comment by LinChengChun** [comment]
Tx
