### ISSUE TITLE
Webview is crashing 

### ISSUE THREAD

**Issue by rahuldev91** [pichillilorenzo/flutter_inappwebview#836]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |          2.0.6      |
| Plugin version       |        5.3.2       |
| Android version      |     7          |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Xioami
OPPO
LAVA

## Description

**Expected behavior:** 
App should work in all devices 

**Current behavior:** 
Webview is crashing on some devices, lots of crash logs are reported in crashlytics

## Steps to reproduce
Unable to reproduce crash logs are coming for the play store app

<img width="1135" alt="Screenshot 2021-05-10 at 11 00 03 AM" src="https://user-images.githubusercontent.com/66363362/117610191-f1767500-b17e-11eb-8d10-b4d7293c609c.png">
<img width="417" alt="Screenshot 2021-05-10 at 11 01 12 AM" src="https://user-images.githubusercontent.com/66363362/117610270-11a63400-b17f-11eb-9ccd-7c61e7fd4124.png">

Logs

```
PhysicalDisplayAndroid.java line 97
org.chromium.ui.display.PhysicalDisplayAndroid.updateFromDisplay

```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
       at org.chromium.ui.display.PhysicalDisplayAndroid.updateFromDisplay(PhysicalDisplayAndroid.java:97)
       at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:174)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:553)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

```

**Comment by And96** [comment]
For me, app crash when opened from external intent if Hybrid Composition is enabled.

**Comment by mcmc2014** [comment]
I also have this problem,happened when the layout was resized
