### ISSUE TITLE
ApplicationNotResponding

### ISSUE THREAD

**Issue by vishnukvmd** [pichillilorenzo/flutter_inappwebview#855]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.0.6           |
| Plugin version       |    5.3.2           |
| Android version      |    6.0           |
| WebView version | 90.0.4430.210 |
| iOS version          |     -          |
| Xcode version        |     -          |

Device information: LG-X240

## Description

**Expected behavior:** 
App starts normally.

**Current behavior:** 
Repeatedly results in an ANR with the following crash log:
```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 4000 ms.
    at J.N.M1Y_XVCN(chromium-SystemWebViewGoogle.aab-stable-443021003)
    at org.chromium.content.browser.BrowserStartupControllerImpl.a(chromium-SystemWebViewGoogle.aab-stable-443021003:2)
    at org.chromium.content.browser.BrowserStartupControllerImpl.g(chromium-SystemWebViewGoogle.aab-stable-443021003:8)
    at L7.run(chromium-SystemWebViewGoogle.aab-stable-443021003:23)
    at org.chromium.base.ThreadUtils.f(chromium-SystemWebViewGoogle.aab-stable-443021003:2)
    at mu0.i(chromium-SystemWebViewGoogle.aab-stable-443021003:31)
    at mu0.b(chromium-SystemWebViewGoogle.aab-stable-443021003:17)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.getWebStorage(chromium-SystemWebViewGoogle.aab-stable-443021003:4)
    at android.webkit.WebStorage.getInstance(WebStorage.java:194)
    at com.pichillilorenzo.flutter_inappwebview.MyWebStorage.<init>
    at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine
    at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine
    at io.flutter.embedding.engine.c.a
    at io.flutter.plugins.GeneratedPluginRegistrant.registerWith
    at java.lang.reflect.Method.invoke(Method.java)
    at io.flutter.embedding.engine.h.h.a.a
    at io.flutter.embedding.android.j.i
    at io.flutter.embedding.android.i.i
    at io.flutter.embedding.android.e.k
    at io.flutter.embedding.android.i.A0
    at androidx.fragment.app.Fragment.f1
    at androidx.fragment.app.u.c
    at androidx.fragment.app.u.m
    at androidx.fragment.app.n.d0
    at androidx.fragment.app.n.c1
    at androidx.fragment.app.n.a0
    at androidx.fragment.app.n.S
    at androidx.fragment.app.n.y
    at androidx.fragment.app.i.c
    at androidx.fragment.app.e.onStart
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
    at android.app.Activity.performStart(Activity.java:6364)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5765)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

## Steps to reproduce
The app is reproducibly stuck in ANR on LG-X240 with this error log.

**Comment by marcqtan** [comment]
have you managed to fix this? experiencing same problem: @pichillilorenzo 

I cannot reproduce this but in production many users are experiencing this problem. When app is started it will just show a white screen. 

I saw this stacktrace in Play Console Vitals Information.


```
trace below:
 #00  pc 0000000001a00674  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 00000000024025e0  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002103f70  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002106374  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 00000000017b7af0  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002e10cf0  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002e10ad4  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002e0f4ec  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (???)
  #00  pc 0000000002e100ac  /data/app/com.google.android.webview-NX370BtKX9xVdllmWZwsEQ==/base.apk!libmonochrome.so (Java_J_N_M1Y_1XVCN+120)
  at J.N.M1Y_XVCN (Native method)
  at org.chromium.content.browser.BrowserStartupControllerImpl.a (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at org.chromium.content.browser.BrowserStartupControllerImpl.g (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at C8.run (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at org.chromium.base.ThreadUtils.f (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at TA0.g (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at TA0.b (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at com.android.webview.chromium.WebViewChromiumFactoryProvider.getWebStorage (chromium-TrichromeWebViewGoogle.aab-stable-463807433)
  at android.webkit.WebStorage.getInstance (WebStorage.java:194)
  at com.pichillilorenzo.flutter_inappwebview.MyWebStorage.<init> (MyWebStorage.java:29)
  at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine (InAppWebViewFlutterPlugin.java:89)
  at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine (InAppWebViewFlutterPlugin.java:68)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add (FlutterEngineConnectionRegistry.java:143)
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:24)
  at java.lang.reflect.Method.invoke (Native method)
  at io.flutter.embedding.engine.FlutterEngine.registerPlugins (FlutterEngine.java:414)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:345)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:260)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:240)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:160)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:151)
  at com.ryanheise.audioservice.AudioServicePlugin.getFlutterEngine (AudioServicePlugin.java:68)
  at com.ryanheise.audioservice.AudioService.onCreate (AudioService.java:286)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4273)
  at android.app.ActivityThread.access$1900 (ActivityThread.java:239)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2029)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7899)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:960)
```
