### ISSUE TITLE
App occasionally crashes when webview is open on android

### ISSUE THREAD

**Issue by jay2jp** [pichillilorenzo/flutter_inappwebview#944]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.2.3         |
| Plugin version       |         5.3.2      |
| Android version      |          10     |
| iOS version          |      N/A         |
| Xcode version        |          N/A     |

Device information: Samsung/Motorola

## Description

I use this plugin to do some document scanning and id verification via an Iframe in my app. Recently my crash reporting software has been showing some odd behavior when some users are in the webview.  I cant really give a way to replicate it but I can provide some details that crashlytics outputs. 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/17814331/129493301-5d6153c2-09ed-466a-b306-f684c87b0698.png">

```
Caused by java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onCreate(ChromeCustomTabsActivity.java:52)
       at android.app.Activity.performCreate(Activity.java:7822)
       at android.app.Activity.performCreate(Activity.java:7811)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.app/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by ScottMacDougall** [comment]
Same issue. I have a number of these errors logged, but I can never reproduce it myself.
